/* SPDX-FileCopyrightText: 2026 Accemic Technologies GmbH
 * SPDX-License-Identifier: ISC
 * GENERATED by gen_program.py -- do not edit by hand.
 */
#ifndef RV_FUNCS_H
#define RV_FUNCS_H

#define RV_N_FUNCS 100
#define RV_N_CAP   25

typedef void (*rv_fn_t)(void);
extern rv_fn_t const rv_table[RV_N_FUNCS];
extern rv_fn_t const rv_cap_table[RV_N_CAP];
void rv_lock_order(void);
extern unsigned rv_local_sum;
extern unsigned rv_private;
extern unsigned rv_actcap_issued;

#endif /* RV_FUNCS_H */
