/* SPDX-FileCopyrightText: 2026 Accemic Technologies GmbH
 * SPDX-License-Identifier: ISC
 *
 * GENERATED by gen_program.py -- do not edit by hand.
 * Regenerate with:  py gen_program.py
 *
 * Every function below has EXACTLY ten instrumented sites, so 100 functions
 * fill 1000 of the encoder's 1023 watchpoint slots. Two shapes:
 *
 *   account  takes a lock (or does not, depending on the mode) and does a
 *            read-modify-write on the shared account -- this is where the
 *            races live
 *   ring     single-producer/single-consumer queue traffic -- correct by
 *            construction, and therefore the CONTRAST: a detector that
 *            reports a race here is wrong
 *
 * The mode is read from shared memory at run time, so ONE binary and ONE
 * watchpoint table serve all five scenarios. That is what makes comparing
 * them honest: nothing else changed between the runs.
 */

#include "rv_shared.h"
#include "rv_tags.h"
#include "rv_site.h"
#include "rv_funcs.h"

#define SH RV_SHARED

/* Peterson's algorithm, inlined per call site so every transaction gets its
 * OWN acquire/release program counters -- a shared out-of-line lock function
 * would give all 100 transactions the same three addresses, and the analysis
 * could no longer say WHICH transaction took the lock.
 *
 * The spin loop itself is deliberately NOT instrumented (see rv_site.h): it
 * hits the same two addresses as fast as the core can issue, and under
 * contention it would drown every other event in the stream.
 */
#define RV_ACQUIRE(lk, me, other, s_try, s_ok)                              \
	do {                                                                    \
		RV_ST(&SH->lock[lk].flag[me], 1u, s_try);                           \
		SH->lock[lk].turn = (other);                                        \
		while (SH->lock[lk].flag[other] && SH->lock[lk].turn == (other)) {   \
			/* uninstrumented on purpose */                                 \
		}                                                                   \
		RV_MARK(s_ok);                                                      \
		/* Runtime truth through ACT-CAP: the lock id the program is        \
		 * ACTUALLY using, computed at run time. The ACT-ST tag of this     \
		 * same event was fixed when the table was loaded and cannot know   \
		 * a lock the mode chose at run time -- which is exactly the        \
		 * wrong-lock scenario. The monitors prefer runtime sync events     \
		 * whenever any are present in the stream. */                       \
		RV_ACTCAP(RV_ACT_CMD_DAQ_PC_CURR, RV_ACT_SINK_AXIS,                 \
		          RV_TAG_SYNC(1u, RV_SYNC_ACQ_OK, (lk), (s_ok)));           \
	} while (0)

#define RV_RELEASE(lk, me, s_rel)                                           \
	do {                                                                    \
		RV_ST(&SH->lock[lk].flag[me], 0u, s_rel);                           \
		RV_ACTCAP(RV_ACT_CMD_DAQ_PC_CURR, RV_ACT_SINK_AXIS,                 \
		          RV_TAG_SYNC(1u, RV_SYNC_RELEASE, (lk), (s_rel)));         \
	} while (0)

unsigned rv_local_sum;
unsigned rv_private;
unsigned rv_actcap_issued;

void rv_t000(void)
{
	unsigned h, t, v, p;

	RV_MARK(0);
	RV_LD(h, &SH->ring_head, 1);
	RV_LD(t, &SH->ring_tail, 2);
	RV_MARK(7);
	if (h != t) {
		RV_LD(v, &SH->ring[t % RV_RING_SLOTS], 3);
		rv_local_sum += v;
		RV_ST(&SH->ring_tail, (t + 1u) % RV_RING_SLOTS, 4);
	}
	RV_LD(p, &rv_private, 5);
	RV_ST(&rv_private, p + 1u, 6);
	RV_ST(&SH->seq, p, 8);
	RV_MARK(9);
}

void rv_t000_cap(void)
{
	unsigned w;
	/* The tag is COMPUTED here -- an ACT-ST trigger could only ever carry
	 * the constant its table entry was loaded with. */
	w = RV_ACT_WORD(RV_ACT_CMD_DAQ_PC_CURR, RV_ACT_SINK_AXIS,
	                RV_TAG_VALUE(SH->ring_head & RV_VALUE_MASK));
	RV_ACTCAP_AT(10, w);
	w = RV_ACT_WORD(RV_ACT_CMD_DAQ_PC_CURR, RV_ACT_SINK_AXIS,
	                RV_TAG_VALUE(SH->balance & RV_VALUE_MASK));
	RV_ACTCAP_AT(11, w);
	rv_actcap_issued += 2u;
}

void rv_t001(void)
{
	unsigned h, t, v, p;

	RV_MARK(12);
	RV_LD(h, &SH->ring_head, 13);
	RV_LD(t, &SH->ring_tail, 14);
	RV_MARK(19);
	if (h != t) {
		RV_LD(v, &SH->ring[t % RV_RING_SLOTS], 15);
		rv_local_sum += v;
		RV_ST(&SH->ring_tail, (t + 1u) % RV_RING_SLOTS, 16);
	}
	RV_LD(p, &rv_private, 17);
	RV_ST(&rv_private, p + 1u, 18);
	RV_ST(&SH->seq, p, 20);
	RV_MARK(21);
}

void rv_t002(void)
{
	unsigned h, t, v, p;

	RV_MARK(22);
	RV_LD(h, &SH->ring_head, 23);
	RV_LD(t, &SH->ring_tail, 24);
	RV_MARK(29);
	if (h != t) {
		RV_LD(v, &SH->ring[t % RV_RING_SLOTS], 25);
		rv_local_sum += v;
		RV_ST(&SH->ring_tail, (t + 1u) % RV_RING_SLOTS, 26);
	}
	RV_LD(p, &rv_private, 27);
	RV_ST(&rv_private, p + 1u, 28);
	RV_ST(&SH->seq, p, 30);
	RV_MARK(31);
}

void rv_t003(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(32);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 33, 34);
	}
	RV_LD(v, &SH->balance, 35);
	v += 4u;
	RV_ST(&SH->balance, v, 36);
	RV_LD(c, &SH->count, 37);
	RV_ST(&SH->count, c + 1u, 38);
	RV_ST(&SH->checksum, (c ^ v) + 3u, 39);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 40);
	}
	RV_MARK(41);
	rv_local_sum += 4u;
}

void rv_t004(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(42);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 43, 44);
	}
	RV_LD(v, &SH->balance, 45);
	v += 5u;
	RV_ST(&SH->balance, v, 46);
	RV_LD(c, &SH->count, 47);
	RV_ST(&SH->count, c + 1u, 48);
	RV_ST(&SH->checksum, (c ^ v) + 4u, 49);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 50);
	}
	RV_MARK(51);
	rv_local_sum += 5u;
}

void rv_t004_cap(void)
{
	unsigned w;
	/* The tag is COMPUTED here -- an ACT-ST trigger could only ever carry
	 * the constant its table entry was loaded with. */
	w = RV_ACT_WORD(RV_ACT_CMD_DAQ_PC_CURR, RV_ACT_SINK_AXIS,
	                RV_TAG_VALUE(SH->ring_head & RV_VALUE_MASK));
	RV_ACTCAP_AT(52, w);
	w = RV_ACT_WORD(RV_ACT_CMD_DAQ_PC_CURR, RV_ACT_SINK_AXIS,
	                RV_TAG_VALUE(SH->balance & RV_VALUE_MASK));
	RV_ACTCAP_AT(53, w);
	rv_actcap_issued += 2u;
}

void rv_t005(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(54);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 55, 56);
	}
	RV_LD(v, &SH->balance, 57);
	v += 6u;
	RV_ST(&SH->balance, v, 58);
	RV_LD(c, &SH->count, 59);
	RV_ST(&SH->count, c + 1u, 60);
	RV_ST(&SH->checksum, (c ^ v) + 5u, 61);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 62);
	}
	RV_MARK(63);
	rv_local_sum += 6u;
}

void rv_t006(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(64);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 65, 66);
	}
	RV_LD(v, &SH->balance, 67);
	v += 7u;
	RV_ST(&SH->balance, v, 68);
	RV_LD(c, &SH->count, 69);
	RV_ST(&SH->count, c + 1u, 70);
	RV_ST(&SH->checksum, (c ^ v) + 6u, 71);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 72);
	}
	RV_MARK(73);
	rv_local_sum += 7u;
}

void rv_t007(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(74);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 75, 76);
	}
	RV_LD(v, &SH->balance, 77);
	v += 1u;
	RV_ST(&SH->balance, v, 78);
	RV_LD(c, &SH->count, 79);
	RV_ST(&SH->count, c + 1u, 80);
	RV_ST(&SH->checksum, (c ^ v) + 7u, 81);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 82);
	}
	RV_MARK(83);
	rv_local_sum += 1u;
}

void rv_t008(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(84);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 85, 86);
	}
	RV_LD(v, &SH->balance, 87);
	v += 2u;
	RV_ST(&SH->balance, v, 88);
	RV_LD(c, &SH->count, 89);
	RV_ST(&SH->count, c + 1u, 90);
	RV_ST(&SH->checksum, (c ^ v) + 8u, 91);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 92);
	}
	RV_MARK(93);
	rv_local_sum += 2u;
}

void rv_t008_cap(void)
{
	unsigned w;
	/* The tag is COMPUTED here -- an ACT-ST trigger could only ever carry
	 * the constant its table entry was loaded with. */
	w = RV_ACT_WORD(RV_ACT_CMD_DAQ_PC_CURR, RV_ACT_SINK_AXIS,
	                RV_TAG_VALUE(SH->ring_head & RV_VALUE_MASK));
	RV_ACTCAP_AT(94, w);
	w = RV_ACT_WORD(RV_ACT_CMD_DAQ_PC_CURR, RV_ACT_SINK_AXIS,
	                RV_TAG_VALUE(SH->balance & RV_VALUE_MASK));
	RV_ACTCAP_AT(95, w);
	rv_actcap_issued += 2u;
}

void rv_t009(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(96);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 97, 98);
	}
	RV_LD(v, &SH->balance, 99);
	v += 3u;
	RV_ST(&SH->balance, v, 100);
	RV_LD(c, &SH->count, 101);
	RV_ST(&SH->count, c + 1u, 102);
	RV_ST(&SH->checksum, (c ^ v) + 9u, 103);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 104);
	}
	RV_MARK(105);
	rv_local_sum += 3u;
}

void rv_t010(void)
{
	unsigned h, t, v, p;

	RV_MARK(106);
	RV_LD(h, &SH->ring_head, 107);
	RV_LD(t, &SH->ring_tail, 108);
	RV_MARK(113);
	if (h != t) {
		RV_LD(v, &SH->ring[t % RV_RING_SLOTS], 109);
		rv_local_sum += v;
		RV_ST(&SH->ring_tail, (t + 1u) % RV_RING_SLOTS, 110);
	}
	RV_LD(p, &rv_private, 111);
	RV_ST(&rv_private, p + 1u, 112);
	RV_ST(&SH->seq, p, 114);
	RV_MARK(115);
}

void rv_t011(void)
{
	unsigned h, t, v, p;

	RV_MARK(116);
	RV_LD(h, &SH->ring_head, 117);
	RV_LD(t, &SH->ring_tail, 118);
	RV_MARK(123);
	if (h != t) {
		RV_LD(v, &SH->ring[t % RV_RING_SLOTS], 119);
		rv_local_sum += v;
		RV_ST(&SH->ring_tail, (t + 1u) % RV_RING_SLOTS, 120);
	}
	RV_LD(p, &rv_private, 121);
	RV_ST(&rv_private, p + 1u, 122);
	RV_ST(&SH->seq, p, 124);
	RV_MARK(125);
}

void rv_t012(void)
{
	unsigned h, t, v, p;

	RV_MARK(126);
	RV_LD(h, &SH->ring_head, 127);
	RV_LD(t, &SH->ring_tail, 128);
	RV_MARK(133);
	if (h != t) {
		RV_LD(v, &SH->ring[t % RV_RING_SLOTS], 129);
		rv_local_sum += v;
		RV_ST(&SH->ring_tail, (t + 1u) % RV_RING_SLOTS, 130);
	}
	RV_LD(p, &rv_private, 131);
	RV_ST(&rv_private, p + 1u, 132);
	RV_ST(&SH->seq, p, 134);
	RV_MARK(135);
}

void rv_t012_cap(void)
{
	unsigned w;
	/* The tag is COMPUTED here -- an ACT-ST trigger could only ever carry
	 * the constant its table entry was loaded with. */
	w = RV_ACT_WORD(RV_ACT_CMD_DAQ_PC_CURR, RV_ACT_SINK_AXIS,
	                RV_TAG_VALUE(SH->ring_head & RV_VALUE_MASK));
	RV_ACTCAP_AT(136, w);
	w = RV_ACT_WORD(RV_ACT_CMD_DAQ_PC_CURR, RV_ACT_SINK_AXIS,
	                RV_TAG_VALUE(SH->balance & RV_VALUE_MASK));
	RV_ACTCAP_AT(137, w);
	rv_actcap_issued += 2u;
}

void rv_t013(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(138);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 139, 140);
	}
	RV_LD(v, &SH->balance, 141);
	v += 7u;
	RV_ST(&SH->balance, v, 142);
	RV_LD(c, &SH->count, 143);
	RV_ST(&SH->count, c + 1u, 144);
	RV_ST(&SH->checksum, (c ^ v) + 13u, 145);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 146);
	}
	RV_MARK(147);
	rv_local_sum += 7u;
}

void rv_t014(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(148);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 149, 150);
	}
	RV_LD(v, &SH->balance, 151);
	v += 1u;
	RV_ST(&SH->balance, v, 152);
	RV_LD(c, &SH->count, 153);
	RV_ST(&SH->count, c + 1u, 154);
	RV_ST(&SH->checksum, (c ^ v) + 14u, 155);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 156);
	}
	RV_MARK(157);
	rv_local_sum += 1u;
}

void rv_t015(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(158);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 159, 160);
	}
	RV_LD(v, &SH->balance, 161);
	v += 2u;
	RV_ST(&SH->balance, v, 162);
	RV_LD(c, &SH->count, 163);
	RV_ST(&SH->count, c + 1u, 164);
	RV_ST(&SH->checksum, (c ^ v) + 15u, 165);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 166);
	}
	RV_MARK(167);
	rv_local_sum += 2u;
}

void rv_t016(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(168);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 169, 170);
	}
	RV_LD(v, &SH->balance, 171);
	v += 3u;
	RV_ST(&SH->balance, v, 172);
	RV_LD(c, &SH->count, 173);
	RV_ST(&SH->count, c + 1u, 174);
	RV_ST(&SH->checksum, (c ^ v) + 16u, 175);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 176);
	}
	RV_MARK(177);
	rv_local_sum += 3u;
}

void rv_t016_cap(void)
{
	unsigned w;
	/* The tag is COMPUTED here -- an ACT-ST trigger could only ever carry
	 * the constant its table entry was loaded with. */
	w = RV_ACT_WORD(RV_ACT_CMD_DAQ_PC_CURR, RV_ACT_SINK_AXIS,
	                RV_TAG_VALUE(SH->ring_head & RV_VALUE_MASK));
	RV_ACTCAP_AT(178, w);
	w = RV_ACT_WORD(RV_ACT_CMD_DAQ_PC_CURR, RV_ACT_SINK_AXIS,
	                RV_TAG_VALUE(SH->balance & RV_VALUE_MASK));
	RV_ACTCAP_AT(179, w);
	rv_actcap_issued += 2u;
}

void rv_t017(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(180);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 181, 182);
	}
	RV_LD(v, &SH->balance, 183);
	v += 4u;
	RV_ST(&SH->balance, v, 184);
	RV_LD(c, &SH->count, 185);
	RV_ST(&SH->count, c + 1u, 186);
	RV_ST(&SH->checksum, (c ^ v) + 17u, 187);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 188);
	}
	RV_MARK(189);
	rv_local_sum += 4u;
}

void rv_t018(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(190);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 191, 192);
	}
	RV_LD(v, &SH->balance, 193);
	v += 5u;
	RV_ST(&SH->balance, v, 194);
	RV_LD(c, &SH->count, 195);
	RV_ST(&SH->count, c + 1u, 196);
	RV_ST(&SH->checksum, (c ^ v) + 18u, 197);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 198);
	}
	RV_MARK(199);
	rv_local_sum += 5u;
}

void rv_t019(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(200);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 201, 202);
	}
	RV_LD(v, &SH->balance, 203);
	v += 6u;
	RV_ST(&SH->balance, v, 204);
	RV_LD(c, &SH->count, 205);
	RV_ST(&SH->count, c + 1u, 206);
	RV_ST(&SH->checksum, (c ^ v) + 19u, 207);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 208);
	}
	RV_MARK(209);
	rv_local_sum += 6u;
}

void rv_t020(void)
{
	unsigned h, t, v, p;

	RV_MARK(210);
	RV_LD(h, &SH->ring_head, 211);
	RV_LD(t, &SH->ring_tail, 212);
	RV_MARK(217);
	if (h != t) {
		RV_LD(v, &SH->ring[t % RV_RING_SLOTS], 213);
		rv_local_sum += v;
		RV_ST(&SH->ring_tail, (t + 1u) % RV_RING_SLOTS, 214);
	}
	RV_LD(p, &rv_private, 215);
	RV_ST(&rv_private, p + 1u, 216);
	RV_ST(&SH->seq, p, 218);
	RV_MARK(219);
}

void rv_t020_cap(void)
{
	unsigned w;
	/* The tag is COMPUTED here -- an ACT-ST trigger could only ever carry
	 * the constant its table entry was loaded with. */
	w = RV_ACT_WORD(RV_ACT_CMD_DAQ_PC_CURR, RV_ACT_SINK_AXIS,
	                RV_TAG_VALUE(SH->ring_head & RV_VALUE_MASK));
	RV_ACTCAP_AT(220, w);
	w = RV_ACT_WORD(RV_ACT_CMD_DAQ_PC_CURR, RV_ACT_SINK_AXIS,
	                RV_TAG_VALUE(SH->balance & RV_VALUE_MASK));
	RV_ACTCAP_AT(221, w);
	rv_actcap_issued += 2u;
}

void rv_t021(void)
{
	unsigned h, t, v, p;

	RV_MARK(222);
	RV_LD(h, &SH->ring_head, 223);
	RV_LD(t, &SH->ring_tail, 224);
	RV_MARK(229);
	if (h != t) {
		RV_LD(v, &SH->ring[t % RV_RING_SLOTS], 225);
		rv_local_sum += v;
		RV_ST(&SH->ring_tail, (t + 1u) % RV_RING_SLOTS, 226);
	}
	RV_LD(p, &rv_private, 227);
	RV_ST(&rv_private, p + 1u, 228);
	RV_ST(&SH->seq, p, 230);
	RV_MARK(231);
}

void rv_t022(void)
{
	unsigned h, t, v, p;

	RV_MARK(232);
	RV_LD(h, &SH->ring_head, 233);
	RV_LD(t, &SH->ring_tail, 234);
	RV_MARK(239);
	if (h != t) {
		RV_LD(v, &SH->ring[t % RV_RING_SLOTS], 235);
		rv_local_sum += v;
		RV_ST(&SH->ring_tail, (t + 1u) % RV_RING_SLOTS, 236);
	}
	RV_LD(p, &rv_private, 237);
	RV_ST(&rv_private, p + 1u, 238);
	RV_ST(&SH->seq, p, 240);
	RV_MARK(241);
}

void rv_t023(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(242);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 243, 244);
	}
	RV_LD(v, &SH->balance, 245);
	v += 3u;
	RV_ST(&SH->balance, v, 246);
	RV_LD(c, &SH->count, 247);
	RV_ST(&SH->count, c + 1u, 248);
	RV_ST(&SH->checksum, (c ^ v) + 23u, 249);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 250);
	}
	RV_MARK(251);
	rv_local_sum += 3u;
}

void rv_t024(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(252);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 253, 254);
	}
	RV_LD(v, &SH->balance, 255);
	v += 4u;
	RV_ST(&SH->balance, v, 256);
	RV_LD(c, &SH->count, 257);
	RV_ST(&SH->count, c + 1u, 258);
	RV_ST(&SH->checksum, (c ^ v) + 24u, 259);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 260);
	}
	RV_MARK(261);
	rv_local_sum += 4u;
}

void rv_t024_cap(void)
{
	unsigned w;
	/* The tag is COMPUTED here -- an ACT-ST trigger could only ever carry
	 * the constant its table entry was loaded with. */
	w = RV_ACT_WORD(RV_ACT_CMD_DAQ_PC_CURR, RV_ACT_SINK_AXIS,
	                RV_TAG_VALUE(SH->ring_head & RV_VALUE_MASK));
	RV_ACTCAP_AT(262, w);
	w = RV_ACT_WORD(RV_ACT_CMD_DAQ_PC_CURR, RV_ACT_SINK_AXIS,
	                RV_TAG_VALUE(SH->balance & RV_VALUE_MASK));
	RV_ACTCAP_AT(263, w);
	rv_actcap_issued += 2u;
}

void rv_t025(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(264);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 265, 266);
	}
	RV_LD(v, &SH->balance, 267);
	v += 5u;
	RV_ST(&SH->balance, v, 268);
	RV_LD(c, &SH->count, 269);
	RV_ST(&SH->count, c + 1u, 270);
	RV_ST(&SH->checksum, (c ^ v) + 25u, 271);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 272);
	}
	RV_MARK(273);
	rv_local_sum += 5u;
}

void rv_t026(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(274);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 275, 276);
	}
	RV_LD(v, &SH->balance, 277);
	v += 6u;
	RV_ST(&SH->balance, v, 278);
	RV_LD(c, &SH->count, 279);
	RV_ST(&SH->count, c + 1u, 280);
	RV_ST(&SH->checksum, (c ^ v) + 26u, 281);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 282);
	}
	RV_MARK(283);
	rv_local_sum += 6u;
}

void rv_t027(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(284);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 285, 286);
	}
	RV_LD(v, &SH->balance, 287);
	v += 7u;
	RV_ST(&SH->balance, v, 288);
	RV_LD(c, &SH->count, 289);
	RV_ST(&SH->count, c + 1u, 290);
	RV_ST(&SH->checksum, (c ^ v) + 27u, 291);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 292);
	}
	RV_MARK(293);
	rv_local_sum += 7u;
}

void rv_t028(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(294);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 295, 296);
	}
	RV_LD(v, &SH->balance, 297);
	v += 1u;
	RV_ST(&SH->balance, v, 298);
	RV_LD(c, &SH->count, 299);
	RV_ST(&SH->count, c + 1u, 300);
	RV_ST(&SH->checksum, (c ^ v) + 28u, 301);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 302);
	}
	RV_MARK(303);
	rv_local_sum += 1u;
}

void rv_t028_cap(void)
{
	unsigned w;
	/* The tag is COMPUTED here -- an ACT-ST trigger could only ever carry
	 * the constant its table entry was loaded with. */
	w = RV_ACT_WORD(RV_ACT_CMD_DAQ_PC_CURR, RV_ACT_SINK_AXIS,
	                RV_TAG_VALUE(SH->ring_head & RV_VALUE_MASK));
	RV_ACTCAP_AT(304, w);
	w = RV_ACT_WORD(RV_ACT_CMD_DAQ_PC_CURR, RV_ACT_SINK_AXIS,
	                RV_TAG_VALUE(SH->balance & RV_VALUE_MASK));
	RV_ACTCAP_AT(305, w);
	rv_actcap_issued += 2u;
}

void rv_t029(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(306);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 307, 308);
	}
	RV_LD(v, &SH->balance, 309);
	v += 2u;
	RV_ST(&SH->balance, v, 310);
	RV_LD(c, &SH->count, 311);
	RV_ST(&SH->count, c + 1u, 312);
	RV_ST(&SH->checksum, (c ^ v) + 29u, 313);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 314);
	}
	RV_MARK(315);
	rv_local_sum += 2u;
}

void rv_t030(void)
{
	unsigned h, t, v, p;

	RV_MARK(316);
	RV_LD(h, &SH->ring_head, 317);
	RV_LD(t, &SH->ring_tail, 318);
	RV_MARK(323);
	if (h != t) {
		RV_LD(v, &SH->ring[t % RV_RING_SLOTS], 319);
		rv_local_sum += v;
		RV_ST(&SH->ring_tail, (t + 1u) % RV_RING_SLOTS, 320);
	}
	RV_LD(p, &rv_private, 321);
	RV_ST(&rv_private, p + 1u, 322);
	RV_ST(&SH->seq, p, 324);
	RV_MARK(325);
}

void rv_t031(void)
{
	unsigned h, t, v, p;

	RV_MARK(326);
	RV_LD(h, &SH->ring_head, 327);
	RV_LD(t, &SH->ring_tail, 328);
	RV_MARK(333);
	if (h != t) {
		RV_LD(v, &SH->ring[t % RV_RING_SLOTS], 329);
		rv_local_sum += v;
		RV_ST(&SH->ring_tail, (t + 1u) % RV_RING_SLOTS, 330);
	}
	RV_LD(p, &rv_private, 331);
	RV_ST(&rv_private, p + 1u, 332);
	RV_ST(&SH->seq, p, 334);
	RV_MARK(335);
}

void rv_t032(void)
{
	unsigned h, t, v, p;

	RV_MARK(336);
	RV_LD(h, &SH->ring_head, 337);
	RV_LD(t, &SH->ring_tail, 338);
	RV_MARK(343);
	if (h != t) {
		RV_LD(v, &SH->ring[t % RV_RING_SLOTS], 339);
		rv_local_sum += v;
		RV_ST(&SH->ring_tail, (t + 1u) % RV_RING_SLOTS, 340);
	}
	RV_LD(p, &rv_private, 341);
	RV_ST(&rv_private, p + 1u, 342);
	RV_ST(&SH->seq, p, 344);
	RV_MARK(345);
}

void rv_t032_cap(void)
{
	unsigned w;
	/* The tag is COMPUTED here -- an ACT-ST trigger could only ever carry
	 * the constant its table entry was loaded with. */
	w = RV_ACT_WORD(RV_ACT_CMD_DAQ_PC_CURR, RV_ACT_SINK_AXIS,
	                RV_TAG_VALUE(SH->ring_head & RV_VALUE_MASK));
	RV_ACTCAP_AT(346, w);
	w = RV_ACT_WORD(RV_ACT_CMD_DAQ_PC_CURR, RV_ACT_SINK_AXIS,
	                RV_TAG_VALUE(SH->balance & RV_VALUE_MASK));
	RV_ACTCAP_AT(347, w);
	rv_actcap_issued += 2u;
}

void rv_t033(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(348);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 349, 350);
	}
	RV_LD(v, &SH->balance, 351);
	v += 6u;
	RV_ST(&SH->balance, v, 352);
	RV_LD(c, &SH->count, 353);
	RV_ST(&SH->count, c + 1u, 354);
	RV_ST(&SH->checksum, (c ^ v) + 33u, 355);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 356);
	}
	RV_MARK(357);
	rv_local_sum += 6u;
}

void rv_t034(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(358);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 359, 360);
	}
	RV_LD(v, &SH->balance, 361);
	v += 7u;
	RV_ST(&SH->balance, v, 362);
	RV_LD(c, &SH->count, 363);
	RV_ST(&SH->count, c + 1u, 364);
	RV_ST(&SH->checksum, (c ^ v) + 34u, 365);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 366);
	}
	RV_MARK(367);
	rv_local_sum += 7u;
}

void rv_t035(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(368);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 369, 370);
	}
	RV_LD(v, &SH->balance, 371);
	v += 1u;
	RV_ST(&SH->balance, v, 372);
	RV_LD(c, &SH->count, 373);
	RV_ST(&SH->count, c + 1u, 374);
	RV_ST(&SH->checksum, (c ^ v) + 35u, 375);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 376);
	}
	RV_MARK(377);
	rv_local_sum += 1u;
}

void rv_t036(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(378);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 379, 380);
	}
	RV_LD(v, &SH->balance, 381);
	v += 2u;
	RV_ST(&SH->balance, v, 382);
	RV_LD(c, &SH->count, 383);
	RV_ST(&SH->count, c + 1u, 384);
	RV_ST(&SH->checksum, (c ^ v) + 36u, 385);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 386);
	}
	RV_MARK(387);
	rv_local_sum += 2u;
}

void rv_t036_cap(void)
{
	unsigned w;
	/* The tag is COMPUTED here -- an ACT-ST trigger could only ever carry
	 * the constant its table entry was loaded with. */
	w = RV_ACT_WORD(RV_ACT_CMD_DAQ_PC_CURR, RV_ACT_SINK_AXIS,
	                RV_TAG_VALUE(SH->ring_head & RV_VALUE_MASK));
	RV_ACTCAP_AT(388, w);
	w = RV_ACT_WORD(RV_ACT_CMD_DAQ_PC_CURR, RV_ACT_SINK_AXIS,
	                RV_TAG_VALUE(SH->balance & RV_VALUE_MASK));
	RV_ACTCAP_AT(389, w);
	rv_actcap_issued += 2u;
}

void rv_t037(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(390);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 391, 392);
	}
	RV_LD(v, &SH->balance, 393);
	v += 3u;
	RV_ST(&SH->balance, v, 394);
	RV_LD(c, &SH->count, 395);
	RV_ST(&SH->count, c + 1u, 396);
	RV_ST(&SH->checksum, (c ^ v) + 37u, 397);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 398);
	}
	RV_MARK(399);
	rv_local_sum += 3u;
}

void rv_t038(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(400);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 401, 402);
	}
	RV_LD(v, &SH->balance, 403);
	v += 4u;
	RV_ST(&SH->balance, v, 404);
	RV_LD(c, &SH->count, 405);
	RV_ST(&SH->count, c + 1u, 406);
	RV_ST(&SH->checksum, (c ^ v) + 38u, 407);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 408);
	}
	RV_MARK(409);
	rv_local_sum += 4u;
}

void rv_t039(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(410);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 411, 412);
	}
	RV_LD(v, &SH->balance, 413);
	v += 5u;
	RV_ST(&SH->balance, v, 414);
	RV_LD(c, &SH->count, 415);
	RV_ST(&SH->count, c + 1u, 416);
	RV_ST(&SH->checksum, (c ^ v) + 39u, 417);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 418);
	}
	RV_MARK(419);
	rv_local_sum += 5u;
}

void rv_t040(void)
{
	unsigned h, t, v, p;

	RV_MARK(420);
	RV_LD(h, &SH->ring_head, 421);
	RV_LD(t, &SH->ring_tail, 422);
	RV_MARK(427);
	if (h != t) {
		RV_LD(v, &SH->ring[t % RV_RING_SLOTS], 423);
		rv_local_sum += v;
		RV_ST(&SH->ring_tail, (t + 1u) % RV_RING_SLOTS, 424);
	}
	RV_LD(p, &rv_private, 425);
	RV_ST(&rv_private, p + 1u, 426);
	RV_ST(&SH->seq, p, 428);
	RV_MARK(429);
}

void rv_t040_cap(void)
{
	unsigned w;
	/* The tag is COMPUTED here -- an ACT-ST trigger could only ever carry
	 * the constant its table entry was loaded with. */
	w = RV_ACT_WORD(RV_ACT_CMD_DAQ_PC_CURR, RV_ACT_SINK_AXIS,
	                RV_TAG_VALUE(SH->ring_head & RV_VALUE_MASK));
	RV_ACTCAP_AT(430, w);
	w = RV_ACT_WORD(RV_ACT_CMD_DAQ_PC_CURR, RV_ACT_SINK_AXIS,
	                RV_TAG_VALUE(SH->balance & RV_VALUE_MASK));
	RV_ACTCAP_AT(431, w);
	rv_actcap_issued += 2u;
}

void rv_t041(void)
{
	unsigned h, t, v, p;

	RV_MARK(432);
	RV_LD(h, &SH->ring_head, 433);
	RV_LD(t, &SH->ring_tail, 434);
	RV_MARK(439);
	if (h != t) {
		RV_LD(v, &SH->ring[t % RV_RING_SLOTS], 435);
		rv_local_sum += v;
		RV_ST(&SH->ring_tail, (t + 1u) % RV_RING_SLOTS, 436);
	}
	RV_LD(p, &rv_private, 437);
	RV_ST(&rv_private, p + 1u, 438);
	RV_ST(&SH->seq, p, 440);
	RV_MARK(441);
}

void rv_t042(void)
{
	unsigned h, t, v, p;

	RV_MARK(442);
	RV_LD(h, &SH->ring_head, 443);
	RV_LD(t, &SH->ring_tail, 444);
	RV_MARK(449);
	if (h != t) {
		RV_LD(v, &SH->ring[t % RV_RING_SLOTS], 445);
		rv_local_sum += v;
		RV_ST(&SH->ring_tail, (t + 1u) % RV_RING_SLOTS, 446);
	}
	RV_LD(p, &rv_private, 447);
	RV_ST(&rv_private, p + 1u, 448);
	RV_ST(&SH->seq, p, 450);
	RV_MARK(451);
}

void rv_t043(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(452);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 453, 454);
	}
	RV_LD(v, &SH->balance, 455);
	v += 2u;
	RV_ST(&SH->balance, v, 456);
	RV_LD(c, &SH->count, 457);
	RV_ST(&SH->count, c + 1u, 458);
	RV_ST(&SH->checksum, (c ^ v) + 43u, 459);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 460);
	}
	RV_MARK(461);
	rv_local_sum += 2u;
}

void rv_t044(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(462);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 463, 464);
	}
	RV_LD(v, &SH->balance, 465);
	v += 3u;
	RV_ST(&SH->balance, v, 466);
	RV_LD(c, &SH->count, 467);
	RV_ST(&SH->count, c + 1u, 468);
	RV_ST(&SH->checksum, (c ^ v) + 44u, 469);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 470);
	}
	RV_MARK(471);
	rv_local_sum += 3u;
}

void rv_t044_cap(void)
{
	unsigned w;
	/* The tag is COMPUTED here -- an ACT-ST trigger could only ever carry
	 * the constant its table entry was loaded with. */
	w = RV_ACT_WORD(RV_ACT_CMD_DAQ_PC_CURR, RV_ACT_SINK_AXIS,
	                RV_TAG_VALUE(SH->ring_head & RV_VALUE_MASK));
	RV_ACTCAP_AT(472, w);
	w = RV_ACT_WORD(RV_ACT_CMD_DAQ_PC_CURR, RV_ACT_SINK_AXIS,
	                RV_TAG_VALUE(SH->balance & RV_VALUE_MASK));
	RV_ACTCAP_AT(473, w);
	rv_actcap_issued += 2u;
}

void rv_t045(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(474);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 475, 476);
	}
	RV_LD(v, &SH->balance, 477);
	v += 4u;
	RV_ST(&SH->balance, v, 478);
	RV_LD(c, &SH->count, 479);
	RV_ST(&SH->count, c + 1u, 480);
	RV_ST(&SH->checksum, (c ^ v) + 45u, 481);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 482);
	}
	RV_MARK(483);
	rv_local_sum += 4u;
}

void rv_t046(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(484);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 485, 486);
	}
	RV_LD(v, &SH->balance, 487);
	v += 5u;
	RV_ST(&SH->balance, v, 488);
	RV_LD(c, &SH->count, 489);
	RV_ST(&SH->count, c + 1u, 490);
	RV_ST(&SH->checksum, (c ^ v) + 46u, 491);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 492);
	}
	RV_MARK(493);
	rv_local_sum += 5u;
}

void rv_t047(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(494);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 495, 496);
	}
	RV_LD(v, &SH->balance, 497);
	v += 6u;
	RV_ST(&SH->balance, v, 498);
	RV_LD(c, &SH->count, 499);
	RV_ST(&SH->count, c + 1u, 500);
	RV_ST(&SH->checksum, (c ^ v) + 47u, 501);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 502);
	}
	RV_MARK(503);
	rv_local_sum += 6u;
}

void rv_t048(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(504);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 505, 506);
	}
	RV_LD(v, &SH->balance, 507);
	v += 7u;
	RV_ST(&SH->balance, v, 508);
	RV_LD(c, &SH->count, 509);
	RV_ST(&SH->count, c + 1u, 510);
	RV_ST(&SH->checksum, (c ^ v) + 48u, 511);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 512);
	}
	RV_MARK(513);
	rv_local_sum += 7u;
}

void rv_t048_cap(void)
{
	unsigned w;
	/* The tag is COMPUTED here -- an ACT-ST trigger could only ever carry
	 * the constant its table entry was loaded with. */
	w = RV_ACT_WORD(RV_ACT_CMD_DAQ_PC_CURR, RV_ACT_SINK_AXIS,
	                RV_TAG_VALUE(SH->ring_head & RV_VALUE_MASK));
	RV_ACTCAP_AT(514, w);
	w = RV_ACT_WORD(RV_ACT_CMD_DAQ_PC_CURR, RV_ACT_SINK_AXIS,
	                RV_TAG_VALUE(SH->balance & RV_VALUE_MASK));
	RV_ACTCAP_AT(515, w);
	rv_actcap_issued += 2u;
}

void rv_t049(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(516);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 517, 518);
	}
	RV_LD(v, &SH->balance, 519);
	v += 1u;
	RV_ST(&SH->balance, v, 520);
	RV_LD(c, &SH->count, 521);
	RV_ST(&SH->count, c + 1u, 522);
	RV_ST(&SH->checksum, (c ^ v) + 49u, 523);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 524);
	}
	RV_MARK(525);
	rv_local_sum += 1u;
}

void rv_t050(void)
{
	unsigned h, t, v, p;

	RV_MARK(526);
	RV_LD(h, &SH->ring_head, 527);
	RV_LD(t, &SH->ring_tail, 528);
	RV_MARK(533);
	if (h != t) {
		RV_LD(v, &SH->ring[t % RV_RING_SLOTS], 529);
		rv_local_sum += v;
		RV_ST(&SH->ring_tail, (t + 1u) % RV_RING_SLOTS, 530);
	}
	RV_LD(p, &rv_private, 531);
	RV_ST(&rv_private, p + 1u, 532);
	RV_ST(&SH->seq, p, 534);
	RV_MARK(535);
}

void rv_t051(void)
{
	unsigned h, t, v, p;

	RV_MARK(536);
	RV_LD(h, &SH->ring_head, 537);
	RV_LD(t, &SH->ring_tail, 538);
	RV_MARK(543);
	if (h != t) {
		RV_LD(v, &SH->ring[t % RV_RING_SLOTS], 539);
		rv_local_sum += v;
		RV_ST(&SH->ring_tail, (t + 1u) % RV_RING_SLOTS, 540);
	}
	RV_LD(p, &rv_private, 541);
	RV_ST(&rv_private, p + 1u, 542);
	RV_ST(&SH->seq, p, 544);
	RV_MARK(545);
}

void rv_t052(void)
{
	unsigned h, t, v, p;

	RV_MARK(546);
	RV_LD(h, &SH->ring_head, 547);
	RV_LD(t, &SH->ring_tail, 548);
	RV_MARK(553);
	if (h != t) {
		RV_LD(v, &SH->ring[t % RV_RING_SLOTS], 549);
		rv_local_sum += v;
		RV_ST(&SH->ring_tail, (t + 1u) % RV_RING_SLOTS, 550);
	}
	RV_LD(p, &rv_private, 551);
	RV_ST(&rv_private, p + 1u, 552);
	RV_ST(&SH->seq, p, 554);
	RV_MARK(555);
}

void rv_t052_cap(void)
{
	unsigned w;
	/* The tag is COMPUTED here -- an ACT-ST trigger could only ever carry
	 * the constant its table entry was loaded with. */
	w = RV_ACT_WORD(RV_ACT_CMD_DAQ_PC_CURR, RV_ACT_SINK_AXIS,
	                RV_TAG_VALUE(SH->ring_head & RV_VALUE_MASK));
	RV_ACTCAP_AT(556, w);
	w = RV_ACT_WORD(RV_ACT_CMD_DAQ_PC_CURR, RV_ACT_SINK_AXIS,
	                RV_TAG_VALUE(SH->balance & RV_VALUE_MASK));
	RV_ACTCAP_AT(557, w);
	rv_actcap_issued += 2u;
}

void rv_t053(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(558);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 559, 560);
	}
	RV_LD(v, &SH->balance, 561);
	v += 5u;
	RV_ST(&SH->balance, v, 562);
	RV_LD(c, &SH->count, 563);
	RV_ST(&SH->count, c + 1u, 564);
	RV_ST(&SH->checksum, (c ^ v) + 53u, 565);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 566);
	}
	RV_MARK(567);
	rv_local_sum += 5u;
}

void rv_t054(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(568);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 569, 570);
	}
	RV_LD(v, &SH->balance, 571);
	v += 6u;
	RV_ST(&SH->balance, v, 572);
	RV_LD(c, &SH->count, 573);
	RV_ST(&SH->count, c + 1u, 574);
	RV_ST(&SH->checksum, (c ^ v) + 54u, 575);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 576);
	}
	RV_MARK(577);
	rv_local_sum += 6u;
}

void rv_t055(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(578);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 579, 580);
	}
	RV_LD(v, &SH->balance, 581);
	v += 7u;
	RV_ST(&SH->balance, v, 582);
	RV_LD(c, &SH->count, 583);
	RV_ST(&SH->count, c + 1u, 584);
	RV_ST(&SH->checksum, (c ^ v) + 55u, 585);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 586);
	}
	RV_MARK(587);
	rv_local_sum += 7u;
}

void rv_t056(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(588);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 589, 590);
	}
	RV_LD(v, &SH->balance, 591);
	v += 1u;
	RV_ST(&SH->balance, v, 592);
	RV_LD(c, &SH->count, 593);
	RV_ST(&SH->count, c + 1u, 594);
	RV_ST(&SH->checksum, (c ^ v) + 56u, 595);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 596);
	}
	RV_MARK(597);
	rv_local_sum += 1u;
}

void rv_t056_cap(void)
{
	unsigned w;
	/* The tag is COMPUTED here -- an ACT-ST trigger could only ever carry
	 * the constant its table entry was loaded with. */
	w = RV_ACT_WORD(RV_ACT_CMD_DAQ_PC_CURR, RV_ACT_SINK_AXIS,
	                RV_TAG_VALUE(SH->ring_head & RV_VALUE_MASK));
	RV_ACTCAP_AT(598, w);
	w = RV_ACT_WORD(RV_ACT_CMD_DAQ_PC_CURR, RV_ACT_SINK_AXIS,
	                RV_TAG_VALUE(SH->balance & RV_VALUE_MASK));
	RV_ACTCAP_AT(599, w);
	rv_actcap_issued += 2u;
}

void rv_t057(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(600);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 601, 602);
	}
	RV_LD(v, &SH->balance, 603);
	v += 2u;
	RV_ST(&SH->balance, v, 604);
	RV_LD(c, &SH->count, 605);
	RV_ST(&SH->count, c + 1u, 606);
	RV_ST(&SH->checksum, (c ^ v) + 57u, 607);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 608);
	}
	RV_MARK(609);
	rv_local_sum += 2u;
}

void rv_t058(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(610);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 611, 612);
	}
	RV_LD(v, &SH->balance, 613);
	v += 3u;
	RV_ST(&SH->balance, v, 614);
	RV_LD(c, &SH->count, 615);
	RV_ST(&SH->count, c + 1u, 616);
	RV_ST(&SH->checksum, (c ^ v) + 58u, 617);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 618);
	}
	RV_MARK(619);
	rv_local_sum += 3u;
}

void rv_t059(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(620);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 621, 622);
	}
	RV_LD(v, &SH->balance, 623);
	v += 4u;
	RV_ST(&SH->balance, v, 624);
	RV_LD(c, &SH->count, 625);
	RV_ST(&SH->count, c + 1u, 626);
	RV_ST(&SH->checksum, (c ^ v) + 59u, 627);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 628);
	}
	RV_MARK(629);
	rv_local_sum += 4u;
}

void rv_t060(void)
{
	unsigned h, t, v, p;

	RV_MARK(630);
	RV_LD(h, &SH->ring_head, 631);
	RV_LD(t, &SH->ring_tail, 632);
	RV_MARK(637);
	if (h != t) {
		RV_LD(v, &SH->ring[t % RV_RING_SLOTS], 633);
		rv_local_sum += v;
		RV_ST(&SH->ring_tail, (t + 1u) % RV_RING_SLOTS, 634);
	}
	RV_LD(p, &rv_private, 635);
	RV_ST(&rv_private, p + 1u, 636);
	RV_ST(&SH->seq, p, 638);
	RV_MARK(639);
}

void rv_t060_cap(void)
{
	unsigned w;
	/* The tag is COMPUTED here -- an ACT-ST trigger could only ever carry
	 * the constant its table entry was loaded with. */
	w = RV_ACT_WORD(RV_ACT_CMD_DAQ_PC_CURR, RV_ACT_SINK_AXIS,
	                RV_TAG_VALUE(SH->ring_head & RV_VALUE_MASK));
	RV_ACTCAP_AT(640, w);
	w = RV_ACT_WORD(RV_ACT_CMD_DAQ_PC_CURR, RV_ACT_SINK_AXIS,
	                RV_TAG_VALUE(SH->balance & RV_VALUE_MASK));
	RV_ACTCAP_AT(641, w);
	rv_actcap_issued += 2u;
}

void rv_t061(void)
{
	unsigned h, t, v, p;

	RV_MARK(642);
	RV_LD(h, &SH->ring_head, 643);
	RV_LD(t, &SH->ring_tail, 644);
	RV_MARK(649);
	if (h != t) {
		RV_LD(v, &SH->ring[t % RV_RING_SLOTS], 645);
		rv_local_sum += v;
		RV_ST(&SH->ring_tail, (t + 1u) % RV_RING_SLOTS, 646);
	}
	RV_LD(p, &rv_private, 647);
	RV_ST(&rv_private, p + 1u, 648);
	RV_ST(&SH->seq, p, 650);
	RV_MARK(651);
}

void rv_t062(void)
{
	unsigned h, t, v, p;

	RV_MARK(652);
	RV_LD(h, &SH->ring_head, 653);
	RV_LD(t, &SH->ring_tail, 654);
	RV_MARK(659);
	if (h != t) {
		RV_LD(v, &SH->ring[t % RV_RING_SLOTS], 655);
		rv_local_sum += v;
		RV_ST(&SH->ring_tail, (t + 1u) % RV_RING_SLOTS, 656);
	}
	RV_LD(p, &rv_private, 657);
	RV_ST(&rv_private, p + 1u, 658);
	RV_ST(&SH->seq, p, 660);
	RV_MARK(661);
}

void rv_t063(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(662);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 663, 664);
	}
	RV_LD(v, &SH->balance, 665);
	v += 1u;
	RV_ST(&SH->balance, v, 666);
	RV_LD(c, &SH->count, 667);
	RV_ST(&SH->count, c + 1u, 668);
	RV_ST(&SH->checksum, (c ^ v) + 63u, 669);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 670);
	}
	RV_MARK(671);
	rv_local_sum += 1u;
}

void rv_t064(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(672);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 673, 674);
	}
	RV_LD(v, &SH->balance, 675);
	v += 2u;
	RV_ST(&SH->balance, v, 676);
	RV_LD(c, &SH->count, 677);
	RV_ST(&SH->count, c + 1u, 678);
	RV_ST(&SH->checksum, (c ^ v) + 64u, 679);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 680);
	}
	RV_MARK(681);
	rv_local_sum += 2u;
}

void rv_t064_cap(void)
{
	unsigned w;
	/* The tag is COMPUTED here -- an ACT-ST trigger could only ever carry
	 * the constant its table entry was loaded with. */
	w = RV_ACT_WORD(RV_ACT_CMD_DAQ_PC_CURR, RV_ACT_SINK_AXIS,
	                RV_TAG_VALUE(SH->ring_head & RV_VALUE_MASK));
	RV_ACTCAP_AT(682, w);
	w = RV_ACT_WORD(RV_ACT_CMD_DAQ_PC_CURR, RV_ACT_SINK_AXIS,
	                RV_TAG_VALUE(SH->balance & RV_VALUE_MASK));
	RV_ACTCAP_AT(683, w);
	rv_actcap_issued += 2u;
}

void rv_t065(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(684);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 685, 686);
	}
	RV_LD(v, &SH->balance, 687);
	v += 3u;
	RV_ST(&SH->balance, v, 688);
	RV_LD(c, &SH->count, 689);
	RV_ST(&SH->count, c + 1u, 690);
	RV_ST(&SH->checksum, (c ^ v) + 65u, 691);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 692);
	}
	RV_MARK(693);
	rv_local_sum += 3u;
}

void rv_t066(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(694);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 695, 696);
	}
	RV_LD(v, &SH->balance, 697);
	v += 4u;
	RV_ST(&SH->balance, v, 698);
	RV_LD(c, &SH->count, 699);
	RV_ST(&SH->count, c + 1u, 700);
	RV_ST(&SH->checksum, (c ^ v) + 66u, 701);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 702);
	}
	RV_MARK(703);
	rv_local_sum += 4u;
}

void rv_t067(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(704);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 705, 706);
	}
	RV_LD(v, &SH->balance, 707);
	v += 5u;
	RV_ST(&SH->balance, v, 708);
	RV_LD(c, &SH->count, 709);
	RV_ST(&SH->count, c + 1u, 710);
	RV_ST(&SH->checksum, (c ^ v) + 67u, 711);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 712);
	}
	RV_MARK(713);
	rv_local_sum += 5u;
}

void rv_t068(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(714);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 715, 716);
	}
	RV_LD(v, &SH->balance, 717);
	v += 6u;
	RV_ST(&SH->balance, v, 718);
	RV_LD(c, &SH->count, 719);
	RV_ST(&SH->count, c + 1u, 720);
	RV_ST(&SH->checksum, (c ^ v) + 68u, 721);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 722);
	}
	RV_MARK(723);
	rv_local_sum += 6u;
}

void rv_t068_cap(void)
{
	unsigned w;
	/* The tag is COMPUTED here -- an ACT-ST trigger could only ever carry
	 * the constant its table entry was loaded with. */
	w = RV_ACT_WORD(RV_ACT_CMD_DAQ_PC_CURR, RV_ACT_SINK_AXIS,
	                RV_TAG_VALUE(SH->ring_head & RV_VALUE_MASK));
	RV_ACTCAP_AT(724, w);
	w = RV_ACT_WORD(RV_ACT_CMD_DAQ_PC_CURR, RV_ACT_SINK_AXIS,
	                RV_TAG_VALUE(SH->balance & RV_VALUE_MASK));
	RV_ACTCAP_AT(725, w);
	rv_actcap_issued += 2u;
}

void rv_t069(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(726);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 727, 728);
	}
	RV_LD(v, &SH->balance, 729);
	v += 7u;
	RV_ST(&SH->balance, v, 730);
	RV_LD(c, &SH->count, 731);
	RV_ST(&SH->count, c + 1u, 732);
	RV_ST(&SH->checksum, (c ^ v) + 69u, 733);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 734);
	}
	RV_MARK(735);
	rv_local_sum += 7u;
}

void rv_t070(void)
{
	unsigned h, t, v, p;

	RV_MARK(736);
	RV_LD(h, &SH->ring_head, 737);
	RV_LD(t, &SH->ring_tail, 738);
	RV_MARK(743);
	if (h != t) {
		RV_LD(v, &SH->ring[t % RV_RING_SLOTS], 739);
		rv_local_sum += v;
		RV_ST(&SH->ring_tail, (t + 1u) % RV_RING_SLOTS, 740);
	}
	RV_LD(p, &rv_private, 741);
	RV_ST(&rv_private, p + 1u, 742);
	RV_ST(&SH->seq, p, 744);
	RV_MARK(745);
}

void rv_t071(void)
{
	unsigned h, t, v, p;

	RV_MARK(746);
	RV_LD(h, &SH->ring_head, 747);
	RV_LD(t, &SH->ring_tail, 748);
	RV_MARK(753);
	if (h != t) {
		RV_LD(v, &SH->ring[t % RV_RING_SLOTS], 749);
		rv_local_sum += v;
		RV_ST(&SH->ring_tail, (t + 1u) % RV_RING_SLOTS, 750);
	}
	RV_LD(p, &rv_private, 751);
	RV_ST(&rv_private, p + 1u, 752);
	RV_ST(&SH->seq, p, 754);
	RV_MARK(755);
}

void rv_t072(void)
{
	unsigned h, t, v, p;

	RV_MARK(756);
	RV_LD(h, &SH->ring_head, 757);
	RV_LD(t, &SH->ring_tail, 758);
	RV_MARK(763);
	if (h != t) {
		RV_LD(v, &SH->ring[t % RV_RING_SLOTS], 759);
		rv_local_sum += v;
		RV_ST(&SH->ring_tail, (t + 1u) % RV_RING_SLOTS, 760);
	}
	RV_LD(p, &rv_private, 761);
	RV_ST(&rv_private, p + 1u, 762);
	RV_ST(&SH->seq, p, 764);
	RV_MARK(765);
}

void rv_t072_cap(void)
{
	unsigned w;
	/* The tag is COMPUTED here -- an ACT-ST trigger could only ever carry
	 * the constant its table entry was loaded with. */
	w = RV_ACT_WORD(RV_ACT_CMD_DAQ_PC_CURR, RV_ACT_SINK_AXIS,
	                RV_TAG_VALUE(SH->ring_head & RV_VALUE_MASK));
	RV_ACTCAP_AT(766, w);
	w = RV_ACT_WORD(RV_ACT_CMD_DAQ_PC_CURR, RV_ACT_SINK_AXIS,
	                RV_TAG_VALUE(SH->balance & RV_VALUE_MASK));
	RV_ACTCAP_AT(767, w);
	rv_actcap_issued += 2u;
}

void rv_t073(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(768);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 769, 770);
	}
	RV_LD(v, &SH->balance, 771);
	v += 4u;
	RV_ST(&SH->balance, v, 772);
	RV_LD(c, &SH->count, 773);
	RV_ST(&SH->count, c + 1u, 774);
	RV_ST(&SH->checksum, (c ^ v) + 73u, 775);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 776);
	}
	RV_MARK(777);
	rv_local_sum += 4u;
}

void rv_t074(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(778);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 779, 780);
	}
	RV_LD(v, &SH->balance, 781);
	v += 5u;
	RV_ST(&SH->balance, v, 782);
	RV_LD(c, &SH->count, 783);
	RV_ST(&SH->count, c + 1u, 784);
	RV_ST(&SH->checksum, (c ^ v) + 74u, 785);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 786);
	}
	RV_MARK(787);
	rv_local_sum += 5u;
}

void rv_t075(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(788);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 789, 790);
	}
	RV_LD(v, &SH->balance, 791);
	v += 6u;
	RV_ST(&SH->balance, v, 792);
	RV_LD(c, &SH->count, 793);
	RV_ST(&SH->count, c + 1u, 794);
	RV_ST(&SH->checksum, (c ^ v) + 75u, 795);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 796);
	}
	RV_MARK(797);
	rv_local_sum += 6u;
}

void rv_t076(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(798);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 799, 800);
	}
	RV_LD(v, &SH->balance, 801);
	v += 7u;
	RV_ST(&SH->balance, v, 802);
	RV_LD(c, &SH->count, 803);
	RV_ST(&SH->count, c + 1u, 804);
	RV_ST(&SH->checksum, (c ^ v) + 76u, 805);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 806);
	}
	RV_MARK(807);
	rv_local_sum += 7u;
}

void rv_t076_cap(void)
{
	unsigned w;
	/* The tag is COMPUTED here -- an ACT-ST trigger could only ever carry
	 * the constant its table entry was loaded with. */
	w = RV_ACT_WORD(RV_ACT_CMD_DAQ_PC_CURR, RV_ACT_SINK_AXIS,
	                RV_TAG_VALUE(SH->ring_head & RV_VALUE_MASK));
	RV_ACTCAP_AT(808, w);
	w = RV_ACT_WORD(RV_ACT_CMD_DAQ_PC_CURR, RV_ACT_SINK_AXIS,
	                RV_TAG_VALUE(SH->balance & RV_VALUE_MASK));
	RV_ACTCAP_AT(809, w);
	rv_actcap_issued += 2u;
}

void rv_t077(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(810);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 811, 812);
	}
	RV_LD(v, &SH->balance, 813);
	v += 1u;
	RV_ST(&SH->balance, v, 814);
	RV_LD(c, &SH->count, 815);
	RV_ST(&SH->count, c + 1u, 816);
	RV_ST(&SH->checksum, (c ^ v) + 77u, 817);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 818);
	}
	RV_MARK(819);
	rv_local_sum += 1u;
}

void rv_t078(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(820);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 821, 822);
	}
	RV_LD(v, &SH->balance, 823);
	v += 2u;
	RV_ST(&SH->balance, v, 824);
	RV_LD(c, &SH->count, 825);
	RV_ST(&SH->count, c + 1u, 826);
	RV_ST(&SH->checksum, (c ^ v) + 78u, 827);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 828);
	}
	RV_MARK(829);
	rv_local_sum += 2u;
}

void rv_t079(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(830);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 831, 832);
	}
	RV_LD(v, &SH->balance, 833);
	v += 3u;
	RV_ST(&SH->balance, v, 834);
	RV_LD(c, &SH->count, 835);
	RV_ST(&SH->count, c + 1u, 836);
	RV_ST(&SH->checksum, (c ^ v) + 79u, 837);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 838);
	}
	RV_MARK(839);
	rv_local_sum += 3u;
}

void rv_t080(void)
{
	unsigned h, t, v, p;

	RV_MARK(840);
	RV_LD(h, &SH->ring_head, 841);
	RV_LD(t, &SH->ring_tail, 842);
	RV_MARK(847);
	if (h != t) {
		RV_LD(v, &SH->ring[t % RV_RING_SLOTS], 843);
		rv_local_sum += v;
		RV_ST(&SH->ring_tail, (t + 1u) % RV_RING_SLOTS, 844);
	}
	RV_LD(p, &rv_private, 845);
	RV_ST(&rv_private, p + 1u, 846);
	RV_ST(&SH->seq, p, 848);
	RV_MARK(849);
}

void rv_t080_cap(void)
{
	unsigned w;
	/* The tag is COMPUTED here -- an ACT-ST trigger could only ever carry
	 * the constant its table entry was loaded with. */
	w = RV_ACT_WORD(RV_ACT_CMD_DAQ_PC_CURR, RV_ACT_SINK_AXIS,
	                RV_TAG_VALUE(SH->ring_head & RV_VALUE_MASK));
	RV_ACTCAP_AT(850, w);
	w = RV_ACT_WORD(RV_ACT_CMD_DAQ_PC_CURR, RV_ACT_SINK_AXIS,
	                RV_TAG_VALUE(SH->balance & RV_VALUE_MASK));
	RV_ACTCAP_AT(851, w);
	rv_actcap_issued += 2u;
}

void rv_t081(void)
{
	unsigned h, t, v, p;

	RV_MARK(852);
	RV_LD(h, &SH->ring_head, 853);
	RV_LD(t, &SH->ring_tail, 854);
	RV_MARK(859);
	if (h != t) {
		RV_LD(v, &SH->ring[t % RV_RING_SLOTS], 855);
		rv_local_sum += v;
		RV_ST(&SH->ring_tail, (t + 1u) % RV_RING_SLOTS, 856);
	}
	RV_LD(p, &rv_private, 857);
	RV_ST(&rv_private, p + 1u, 858);
	RV_ST(&SH->seq, p, 860);
	RV_MARK(861);
}

void rv_t082(void)
{
	unsigned h, t, v, p;

	RV_MARK(862);
	RV_LD(h, &SH->ring_head, 863);
	RV_LD(t, &SH->ring_tail, 864);
	RV_MARK(869);
	if (h != t) {
		RV_LD(v, &SH->ring[t % RV_RING_SLOTS], 865);
		rv_local_sum += v;
		RV_ST(&SH->ring_tail, (t + 1u) % RV_RING_SLOTS, 866);
	}
	RV_LD(p, &rv_private, 867);
	RV_ST(&rv_private, p + 1u, 868);
	RV_ST(&SH->seq, p, 870);
	RV_MARK(871);
}

void rv_t083(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(872);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 873, 874);
	}
	RV_LD(v, &SH->balance, 875);
	v += 7u;
	RV_ST(&SH->balance, v, 876);
	RV_LD(c, &SH->count, 877);
	RV_ST(&SH->count, c + 1u, 878);
	RV_ST(&SH->checksum, (c ^ v) + 83u, 879);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 880);
	}
	RV_MARK(881);
	rv_local_sum += 7u;
}

void rv_t084(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(882);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 883, 884);
	}
	RV_LD(v, &SH->balance, 885);
	v += 1u;
	RV_ST(&SH->balance, v, 886);
	RV_LD(c, &SH->count, 887);
	RV_ST(&SH->count, c + 1u, 888);
	RV_ST(&SH->checksum, (c ^ v) + 84u, 889);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 890);
	}
	RV_MARK(891);
	rv_local_sum += 1u;
}

void rv_t084_cap(void)
{
	unsigned w;
	/* The tag is COMPUTED here -- an ACT-ST trigger could only ever carry
	 * the constant its table entry was loaded with. */
	w = RV_ACT_WORD(RV_ACT_CMD_DAQ_PC_CURR, RV_ACT_SINK_AXIS,
	                RV_TAG_VALUE(SH->ring_head & RV_VALUE_MASK));
	RV_ACTCAP_AT(892, w);
	w = RV_ACT_WORD(RV_ACT_CMD_DAQ_PC_CURR, RV_ACT_SINK_AXIS,
	                RV_TAG_VALUE(SH->balance & RV_VALUE_MASK));
	RV_ACTCAP_AT(893, w);
	rv_actcap_issued += 2u;
}

void rv_t085(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(894);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 895, 896);
	}
	RV_LD(v, &SH->balance, 897);
	v += 2u;
	RV_ST(&SH->balance, v, 898);
	RV_LD(c, &SH->count, 899);
	RV_ST(&SH->count, c + 1u, 900);
	RV_ST(&SH->checksum, (c ^ v) + 85u, 901);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 902);
	}
	RV_MARK(903);
	rv_local_sum += 2u;
}

void rv_t086(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(904);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 905, 906);
	}
	RV_LD(v, &SH->balance, 907);
	v += 3u;
	RV_ST(&SH->balance, v, 908);
	RV_LD(c, &SH->count, 909);
	RV_ST(&SH->count, c + 1u, 910);
	RV_ST(&SH->checksum, (c ^ v) + 86u, 911);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 912);
	}
	RV_MARK(913);
	rv_local_sum += 3u;
}

void rv_t087(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(914);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 915, 916);
	}
	RV_LD(v, &SH->balance, 917);
	v += 4u;
	RV_ST(&SH->balance, v, 918);
	RV_LD(c, &SH->count, 919);
	RV_ST(&SH->count, c + 1u, 920);
	RV_ST(&SH->checksum, (c ^ v) + 87u, 921);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 922);
	}
	RV_MARK(923);
	rv_local_sum += 4u;
}

void rv_t088(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(924);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 925, 926);
	}
	RV_LD(v, &SH->balance, 927);
	v += 5u;
	RV_ST(&SH->balance, v, 928);
	RV_LD(c, &SH->count, 929);
	RV_ST(&SH->count, c + 1u, 930);
	RV_ST(&SH->checksum, (c ^ v) + 88u, 931);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 932);
	}
	RV_MARK(933);
	rv_local_sum += 5u;
}

void rv_t088_cap(void)
{
	unsigned w;
	/* The tag is COMPUTED here -- an ACT-ST trigger could only ever carry
	 * the constant its table entry was loaded with. */
	w = RV_ACT_WORD(RV_ACT_CMD_DAQ_PC_CURR, RV_ACT_SINK_AXIS,
	                RV_TAG_VALUE(SH->ring_head & RV_VALUE_MASK));
	RV_ACTCAP_AT(934, w);
	w = RV_ACT_WORD(RV_ACT_CMD_DAQ_PC_CURR, RV_ACT_SINK_AXIS,
	                RV_TAG_VALUE(SH->balance & RV_VALUE_MASK));
	RV_ACTCAP_AT(935, w);
	rv_actcap_issued += 2u;
}

void rv_t089(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(936);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 937, 938);
	}
	RV_LD(v, &SH->balance, 939);
	v += 6u;
	RV_ST(&SH->balance, v, 940);
	RV_LD(c, &SH->count, 941);
	RV_ST(&SH->count, c + 1u, 942);
	RV_ST(&SH->checksum, (c ^ v) + 89u, 943);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 944);
	}
	RV_MARK(945);
	rv_local_sum += 6u;
}

void rv_t090(void)
{
	unsigned h, t, v, p;

	RV_MARK(946);
	RV_LD(h, &SH->ring_head, 947);
	RV_LD(t, &SH->ring_tail, 948);
	RV_MARK(953);
	if (h != t) {
		RV_LD(v, &SH->ring[t % RV_RING_SLOTS], 949);
		rv_local_sum += v;
		RV_ST(&SH->ring_tail, (t + 1u) % RV_RING_SLOTS, 950);
	}
	RV_LD(p, &rv_private, 951);
	RV_ST(&rv_private, p + 1u, 952);
	RV_ST(&SH->seq, p, 954);
	RV_MARK(955);
}

void rv_t091(void)
{
	unsigned h, t, v, p;

	RV_MARK(956);
	RV_LD(h, &SH->ring_head, 957);
	RV_LD(t, &SH->ring_tail, 958);
	RV_MARK(963);
	if (h != t) {
		RV_LD(v, &SH->ring[t % RV_RING_SLOTS], 959);
		rv_local_sum += v;
		RV_ST(&SH->ring_tail, (t + 1u) % RV_RING_SLOTS, 960);
	}
	RV_LD(p, &rv_private, 961);
	RV_ST(&rv_private, p + 1u, 962);
	RV_ST(&SH->seq, p, 964);
	RV_MARK(965);
}

void rv_t092(void)
{
	unsigned h, t, v, p;

	RV_MARK(966);
	RV_LD(h, &SH->ring_head, 967);
	RV_LD(t, &SH->ring_tail, 968);
	RV_MARK(973);
	if (h != t) {
		RV_LD(v, &SH->ring[t % RV_RING_SLOTS], 969);
		rv_local_sum += v;
		RV_ST(&SH->ring_tail, (t + 1u) % RV_RING_SLOTS, 970);
	}
	RV_LD(p, &rv_private, 971);
	RV_ST(&rv_private, p + 1u, 972);
	RV_ST(&SH->seq, p, 974);
	RV_MARK(975);
}

void rv_t092_cap(void)
{
	unsigned w;
	/* The tag is COMPUTED here -- an ACT-ST trigger could only ever carry
	 * the constant its table entry was loaded with. */
	w = RV_ACT_WORD(RV_ACT_CMD_DAQ_PC_CURR, RV_ACT_SINK_AXIS,
	                RV_TAG_VALUE(SH->ring_head & RV_VALUE_MASK));
	RV_ACTCAP_AT(976, w);
	w = RV_ACT_WORD(RV_ACT_CMD_DAQ_PC_CURR, RV_ACT_SINK_AXIS,
	                RV_TAG_VALUE(SH->balance & RV_VALUE_MASK));
	RV_ACTCAP_AT(977, w);
	rv_actcap_issued += 2u;
}

void rv_t093(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(978);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 979, 980);
	}
	RV_LD(v, &SH->balance, 981);
	v += 3u;
	RV_ST(&SH->balance, v, 982);
	RV_LD(c, &SH->count, 983);
	RV_ST(&SH->count, c + 1u, 984);
	RV_ST(&SH->checksum, (c ^ v) + 93u, 985);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 986);
	}
	RV_MARK(987);
	rv_local_sum += 3u;
}

void rv_t094(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(988);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 989, 990);
	}
	RV_LD(v, &SH->balance, 991);
	v += 4u;
	RV_ST(&SH->balance, v, 992);
	RV_LD(c, &SH->count, 993);
	RV_ST(&SH->count, c + 1u, 994);
	RV_ST(&SH->checksum, (c ^ v) + 94u, 995);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 996);
	}
	RV_MARK(997);
	rv_local_sum += 4u;
}

void rv_t095(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(998);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 999, 1000);
	}
	RV_LD(v, &SH->balance, 1001);
	v += 5u;
	RV_ST(&SH->balance, v, 1002);
	RV_LD(c, &SH->count, 1003);
	RV_ST(&SH->count, c + 1u, 1004);
	RV_ST(&SH->checksum, (c ^ v) + 95u, 1005);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 1006);
	}
	RV_MARK(1007);
	rv_local_sum += 5u;
}

void rv_t096(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(1008);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 1009, 1010);
	}
	RV_LD(v, &SH->balance, 1011);
	v += 6u;
	RV_ST(&SH->balance, v, 1012);
	RV_LD(c, &SH->count, 1013);
	RV_ST(&SH->count, c + 1u, 1014);
	RV_ST(&SH->checksum, (c ^ v) + 96u, 1015);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 1016);
	}
	RV_MARK(1017);
	rv_local_sum += 6u;
}

void rv_t096_cap(void)
{
	unsigned w;
	/* The tag is COMPUTED here -- an ACT-ST trigger could only ever carry
	 * the constant its table entry was loaded with. */
	w = RV_ACT_WORD(RV_ACT_CMD_DAQ_PC_CURR, RV_ACT_SINK_AXIS,
	                RV_TAG_VALUE(SH->ring_head & RV_VALUE_MASK));
	RV_ACTCAP_AT(1018, w);
	w = RV_ACT_WORD(RV_ACT_CMD_DAQ_PC_CURR, RV_ACT_SINK_AXIS,
	                RV_TAG_VALUE(SH->balance & RV_VALUE_MASK));
	RV_ACTCAP_AT(1019, w);
	rv_actcap_issued += 2u;
}

void rv_t097(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(1020);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 1021, 1022);
	}
	RV_LD(v, &SH->balance, 1023);
	v += 7u;
	RV_ST(&SH->balance, v, 1024);
	RV_LD(c, &SH->count, 1025);
	RV_ST(&SH->count, c + 1u, 1026);
	RV_ST(&SH->checksum, (c ^ v) + 97u, 1027);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 1028);
	}
	RV_MARK(1029);
	rv_local_sum += 7u;
}

void rv_t098(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(1030);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 1031, 1032);
	}
	RV_LD(v, &SH->balance, 1033);
	v += 1u;
	RV_ST(&SH->balance, v, 1034);
	RV_LD(c, &SH->count, 1035);
	RV_ST(&SH->count, c + 1u, 1036);
	RV_ST(&SH->checksum, (c ^ v) + 98u, 1037);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 1038);
	}
	RV_MARK(1039);
	rv_local_sum += 1u;
}

void rv_t099(void)
{
	unsigned v, c, lk;
	unsigned use_lock = (SH->mode != RV_MODE_RACE_OPEN);
	/* RV_MODE_RACE_WRONG_LOCK: each core takes a DIFFERENT lock, so both
	 * believe they are protected and neither excludes the other. */
	lk = (SH->mode == RV_MODE_RACE_WRONG_LOCK) ? 1u : 0u;

	RV_MARK(1040);
	if (use_lock) {
		RV_ACQUIRE(lk, 1u, 0u, 1041, 1042);
	}
	RV_LD(v, &SH->balance, 1043);
	v += 2u;
	RV_ST(&SH->balance, v, 1044);
	RV_LD(c, &SH->count, 1045);
	RV_ST(&SH->count, c + 1u, 1046);
	RV_ST(&SH->checksum, (c ^ v) + 99u, 1047);
	if (use_lock) {
		RV_RELEASE(lk, 1u, 1048);
	}
	RV_MARK(1049);
	rv_local_sum += 2u;
}

/* Lock-order scenario: the two cores take locks 3 and 2 in OPPOSITE order.
 * No deadlock is provoked -- the point is that the order graph is cyclic,
 * which a monitor can see in a run that happened to go well. The runtime
 * (ACT-CAP) sync tags are emitted alongside the static ones, so this
 * scenario stays visible under the monitors' runtime-preference rule. */
void rv_lock_order(void)
{
	RV_ST(&SH->lock[3u].flag[1u], 1u, 1050);
	RV_ACTCAP(RV_ACT_CMD_DAQ_PC_CURR, RV_ACT_SINK_AXIS,
	          RV_TAG_SYNC(1u, RV_SYNC_ACQ_OK, 3u, 0u));
	RV_ST(&SH->lock[2u].flag[1u], 1u, 1051);
	RV_ACTCAP(RV_ACT_CMD_DAQ_PC_CURR, RV_ACT_SINK_AXIS,
	          RV_TAG_SYNC(1u, RV_SYNC_ACQ_OK, 2u, 0u));
	RV_ST(&SH->lock[2u].flag[1u], 0u, 1052);
	RV_ACTCAP(RV_ACT_CMD_DAQ_PC_CURR, RV_ACT_SINK_AXIS,
	          RV_TAG_SYNC(1u, RV_SYNC_RELEASE, 2u, 0u));
	RV_ST(&SH->lock[3u].flag[1u], 0u, 1053);
	RV_ACTCAP(RV_ACT_CMD_DAQ_PC_CURR, RV_ACT_SINK_AXIS,
	          RV_TAG_SYNC(1u, RV_SYNC_RELEASE, 3u, 0u));
}

/* Dispatch table -- the transactions are reached through an
 * INDIRECT call, which is what makes RV_MODE_CFI_SKIP a real
 * forward-edge CFI violation rather than a mislabelled branch. */
rv_fn_t const rv_table[RV_N_FUNCS] = {
	rv_t000,
	rv_t001,
	rv_t002,
	rv_t003,
	rv_t004,
	rv_t005,
	rv_t006,
	rv_t007,
	rv_t008,
	rv_t009,
	rv_t010,
	rv_t011,
	rv_t012,
	rv_t013,
	rv_t014,
	rv_t015,
	rv_t016,
	rv_t017,
	rv_t018,
	rv_t019,
	rv_t020,
	rv_t021,
	rv_t022,
	rv_t023,
	rv_t024,
	rv_t025,
	rv_t026,
	rv_t027,
	rv_t028,
	rv_t029,
	rv_t030,
	rv_t031,
	rv_t032,
	rv_t033,
	rv_t034,
	rv_t035,
	rv_t036,
	rv_t037,
	rv_t038,
	rv_t039,
	rv_t040,
	rv_t041,
	rv_t042,
	rv_t043,
	rv_t044,
	rv_t045,
	rv_t046,
	rv_t047,
	rv_t048,
	rv_t049,
	rv_t050,
	rv_t051,
	rv_t052,
	rv_t053,
	rv_t054,
	rv_t055,
	rv_t056,
	rv_t057,
	rv_t058,
	rv_t059,
	rv_t060,
	rv_t061,
	rv_t062,
	rv_t063,
	rv_t064,
	rv_t065,
	rv_t066,
	rv_t067,
	rv_t068,
	rv_t069,
	rv_t070,
	rv_t071,
	rv_t072,
	rv_t073,
	rv_t074,
	rv_t075,
	rv_t076,
	rv_t077,
	rv_t078,
	rv_t079,
	rv_t080,
	rv_t081,
	rv_t082,
	rv_t083,
	rv_t084,
	rv_t085,
	rv_t086,
	rv_t087,
	rv_t088,
	rv_t089,
	rv_t090,
	rv_t091,
	rv_t092,
	rv_t093,
	rv_t094,
	rv_t095,
	rv_t096,
	rv_t097,
	rv_t098,
	rv_t099,
};

rv_fn_t const rv_cap_table[RV_N_CAP] = {
	rv_t000_cap,
	rv_t004_cap,
	rv_t008_cap,
	rv_t012_cap,
	rv_t016_cap,
	rv_t020_cap,
	rv_t024_cap,
	rv_t028_cap,
	rv_t032_cap,
	rv_t036_cap,
	rv_t040_cap,
	rv_t044_cap,
	rv_t048_cap,
	rv_t052_cap,
	rv_t056_cap,
	rv_t060_cap,
	rv_t064_cap,
	rv_t068_cap,
	rv_t072_cap,
	rv_t076_cap,
	rv_t080_cap,
	rv_t084_cap,
	rv_t088_cap,
	rv_t092_cap,
	rv_t096_cap,
};
