// SPDX-FileCopyrightText: 2026 Accemic Technologies GmbH
// SPDX-License-Identifier: CERN-OHL-S-2.0 OR LicenseRef-Accemic-Commercial

// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package ct_soc_regs_pkg;

    localparam CT_SOC_REGS_DATA_WIDTH = 32;
    localparam CT_SOC_REGS_MIN_ADDR_WIDTH = 13;
    localparam CT_SOC_REGS_SIZE = 'h1008;

    typedef struct {
        logic [31:0] next;
    } ct_soc_periph__clint__mtimelo__Value__in_t;

    typedef struct {
        ct_soc_periph__clint__mtimelo__Value__in_t Value;
    } ct_soc_periph__clint__mtimelo__in_t;

    typedef struct {
        logic [31:0] next;
    } ct_soc_periph__clint__mtimehi__Value__in_t;

    typedef struct {
        ct_soc_periph__clint__mtimehi__Value__in_t Value;
    } ct_soc_periph__clint__mtimehi__in_t;

    typedef struct {
        ct_soc_periph__clint__mtimelo__in_t mtimelo;
        ct_soc_periph__clint__mtimehi__in_t mtimehi;
    } ct_soc_periph__clint__in_t;

    typedef struct {
        ct_soc_periph__clint__in_t clint;
    } ct_soc_periph__in_t;

    typedef struct {
        logic value;
    } ct_soc_periph__clint__msip__Pending__out_t;

    typedef struct {
        ct_soc_periph__clint__msip__Pending__out_t Pending;
    } ct_soc_periph__clint__msip__out_t;

    typedef struct {
        logic [31:0] value;
    } ct_soc_periph__clint__mtimecmplo__Value__out_t;

    typedef struct {
        ct_soc_periph__clint__mtimecmplo__Value__out_t Value;
    } ct_soc_periph__clint__mtimecmplo__out_t;

    typedef struct {
        logic [31:0] value;
    } ct_soc_periph__clint__mtimecmphi__Value__out_t;

    typedef struct {
        ct_soc_periph__clint__mtimecmphi__Value__out_t Value;
    } ct_soc_periph__clint__mtimecmphi__out_t;

    typedef struct {
        ct_soc_periph__clint__msip__out_t msip;
        ct_soc_periph__clint__mtimecmplo__out_t mtimecmplo;
        ct_soc_periph__clint__mtimecmphi__out_t mtimecmphi;
    } ct_soc_periph__clint__out_t;

    typedef struct {
        logic value;
    } ct_soc_periph__intc__trigger__Set__out_t;

    typedef struct {
        ct_soc_periph__intc__trigger__Set__out_t Set;
    } ct_soc_periph__intc__trigger__out_t;

    typedef struct {
        logic value;
    } ct_soc_periph__intc__enable__Enable__out_t;

    typedef struct {
        ct_soc_periph__intc__enable__Enable__out_t Enable;
    } ct_soc_periph__intc__enable__out_t;

    typedef struct {
        ct_soc_periph__intc__trigger__out_t trigger;
        ct_soc_periph__intc__enable__out_t enable;
    } ct_soc_periph__intc__out_t;

    typedef struct {
        ct_soc_periph__clint__out_t clint;
        ct_soc_periph__intc__out_t intc;
    } ct_soc_periph__out_t;
endpackage
