// SPDX-FileCopyrightText: 2026 Accemic Technologies GmbH
// SPDX-License-Identifier: CERN-OHL-S-2.0 OR LicenseRef-Accemic-Commercial

// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

module ct_soc_regs (
        input wire clk,
        input wire rst,

        output logic s_axil_awready,
        input wire s_axil_awvalid,
        input wire [12:0] s_axil_awaddr,
        input wire [2:0] s_axil_awprot,
        output logic s_axil_wready,
        input wire s_axil_wvalid,
        input wire [31:0] s_axil_wdata,
        input wire [3:0]s_axil_wstrb,
        input wire s_axil_bready,
        output logic s_axil_bvalid,
        output logic [1:0] s_axil_bresp,
        output logic s_axil_arready,
        input wire s_axil_arvalid,
        input wire [12:0] s_axil_araddr,
        input wire [2:0] s_axil_arprot,
        input wire s_axil_rready,
        output logic s_axil_rvalid,
        output logic [31:0] s_axil_rdata,
        output logic [1:0] s_axil_rresp,

        input ct_soc_regs_pkg::ct_soc_periph__in_t hwif_in,
        output ct_soc_regs_pkg::ct_soc_periph__out_t hwif_out
    );

    //--------------------------------------------------------------------------
    // CPU Bus interface logic
    //--------------------------------------------------------------------------
    logic cpuif_req;
    logic cpuif_req_is_wr;
    logic [12:0] cpuif_addr;
    logic [31:0] cpuif_wr_data;
    logic [31:0] cpuif_wr_biten;
    logic cpuif_req_stall_wr;
    logic cpuif_req_stall_rd;

    logic cpuif_rd_ack;
    logic cpuif_rd_err;
    logic [31:0] cpuif_rd_data;

    logic cpuif_wr_ack;
    logic cpuif_wr_err;

    // Max Outstanding Transactions: 2
    logic [1:0] axil_n_in_flight;
    logic axil_prev_was_rd;
    logic axil_arvalid;
    logic [12:0] axil_araddr;
    logic axil_ar_accept;
    logic axil_awvalid;
    logic [12:0] axil_awaddr;
    logic axil_wvalid;
    logic [31:0] axil_wdata;
    logic [3:0] axil_wstrb;
    logic axil_aw_accept;
    logic axil_resp_acked;

    // Transaction request acceptance
    always_ff @(posedge clk) begin
        if(rst) begin
            axil_prev_was_rd <= '0;
            axil_arvalid <= '0;
            axil_araddr <= '0;
            axil_awvalid <= '0;
            axil_awaddr <= '0;
            axil_wvalid <= '0;
            axil_wdata <= '0;
            axil_wstrb <= '0;
            axil_n_in_flight <= '0;
        end else begin
            // AR* acceptance register
            if(axil_ar_accept) begin
                axil_prev_was_rd <= '1;
                axil_arvalid <= '0;
            end
            if(s_axil_arvalid && s_axil_arready) begin
                axil_arvalid <= '1;
                axil_araddr <= s_axil_araddr;
            end

            // AW* & W* acceptance registers
            if(axil_aw_accept) begin
                axil_prev_was_rd <= '0;
                axil_awvalid <= '0;
                axil_wvalid <= '0;
            end
            if(s_axil_awvalid && s_axil_awready) begin
                axil_awvalid <= '1;
                axil_awaddr <= s_axil_awaddr;
            end
            if(s_axil_wvalid && s_axil_wready) begin
                axil_wvalid <= '1;
                axil_wdata <= s_axil_wdata;
                axil_wstrb <= s_axil_wstrb;
            end

            // Keep track of in-flight transactions
            if((axil_ar_accept || axil_aw_accept) && !axil_resp_acked) begin
                axil_n_in_flight <= axil_n_in_flight + 1'b1;
            end else if(!(axil_ar_accept || axil_aw_accept) && axil_resp_acked) begin
                axil_n_in_flight <= axil_n_in_flight - 1'b1;
            end
        end
    end

    always_comb begin
        s_axil_arready = (!axil_arvalid || axil_ar_accept);
        s_axil_awready = (!axil_awvalid || axil_aw_accept);
        s_axil_wready = (!axil_wvalid || axil_aw_accept);
    end

    // Request dispatch
    always_comb begin
        cpuif_wr_data = axil_wdata;
        for(int i=0; i<4; i++) begin
            cpuif_wr_biten[i*8 +: 8] = {8{axil_wstrb[i]}};
        end
        cpuif_req = '0;
        cpuif_req_is_wr = '0;
        cpuif_addr = '0;
        axil_ar_accept = '0;
        axil_aw_accept = '0;

        if(axil_n_in_flight < 2'd2) begin
            // Can safely issue more transactions without overwhelming response buffer
            if(axil_arvalid && !axil_prev_was_rd) begin
                cpuif_req = '1;
                cpuif_req_is_wr = '0;
                cpuif_addr = {axil_araddr[12:2], 2'b0};
                if(!cpuif_req_stall_rd) axil_ar_accept = '1;
            end else if(axil_awvalid && axil_wvalid) begin
                cpuif_req = '1;
                cpuif_req_is_wr = '1;
                cpuif_addr = {axil_awaddr[12:2], 2'b0};
                if(!cpuif_req_stall_wr) axil_aw_accept = '1;
            end else if(axil_arvalid) begin
                cpuif_req = '1;
                cpuif_req_is_wr = '0;
                cpuif_addr = {axil_araddr[12:2], 2'b0};
                if(!cpuif_req_stall_rd) axil_ar_accept = '1;
            end
        end
    end


    // AXI4-Lite Response Logic
    logic axil_resp_buffer_is_wr[2];
    logic axil_resp_buffer_err[2];
    logic [31:0] axil_resp_buffer_rdata[2];

    logic [1:0] axil_resp_wptr;
    logic [1:0] axil_resp_rptr;

    always_ff @(posedge clk) begin
        if(rst) begin
            for(int i=0; i<2; i++) begin
                axil_resp_buffer_is_wr[i] <= '0;
                axil_resp_buffer_err[i] <= '0;
                axil_resp_buffer_rdata[i] <= '0;
            end
            axil_resp_wptr <= '0;
            axil_resp_rptr <= '0;
        end else begin
            // Store responses in buffer until AXI response channel accepts them
            if(cpuif_rd_ack || cpuif_wr_ack) begin
                if(cpuif_rd_ack) begin
                    axil_resp_buffer_is_wr[axil_resp_wptr[0:0]] <= '0;
                    axil_resp_buffer_err[axil_resp_wptr[0:0]] <= cpuif_rd_err;
                    axil_resp_buffer_rdata[axil_resp_wptr[0:0]] <= cpuif_rd_data;

                end else if(cpuif_wr_ack) begin
                    axil_resp_buffer_is_wr[axil_resp_wptr[0:0]] <= '1;
                    axil_resp_buffer_err[axil_resp_wptr[0:0]] <= cpuif_wr_err;
                end
                axil_resp_wptr <= axil_resp_wptr + 1'b1;
            end

            // Advance read pointer when acknowledged
            if(axil_resp_acked) begin
                axil_resp_rptr <= axil_resp_rptr + 1'b1;
            end
        end
    end

    always_comb begin
        axil_resp_acked = '0;
        s_axil_bvalid = '0;
        s_axil_rvalid = '0;
        if(axil_resp_rptr != axil_resp_wptr) begin
            if(axil_resp_buffer_is_wr[axil_resp_rptr[0:0]]) begin
                s_axil_bvalid = '1;
                if(s_axil_bready) axil_resp_acked = '1;
            end else begin
                s_axil_rvalid = '1;
                if(s_axil_rready) axil_resp_acked = '1;
            end
        end

        s_axil_rdata = axil_resp_buffer_rdata[axil_resp_rptr[0:0]];
        if(axil_resp_buffer_err[axil_resp_rptr[0:0]]) begin
            s_axil_bresp = 2'b10;
            s_axil_rresp = 2'b10;
        end else begin
            s_axil_bresp = 2'b00;
            s_axil_rresp = 2'b00;
        end
    end

    logic cpuif_req_masked;

    // Read & write latencies are balanced. Stalls not required
    assign cpuif_req_stall_rd = '0;
    assign cpuif_req_stall_wr = '0;
    assign cpuif_req_masked = cpuif_req
                            & !(!cpuif_req_is_wr & cpuif_req_stall_rd)
                            & !(cpuif_req_is_wr & cpuif_req_stall_wr);

    //--------------------------------------------------------------------------
    // Address Decode
    //--------------------------------------------------------------------------
    typedef struct {
        struct {
            logic msip;
            logic mtimecmplo;
            logic mtimecmphi;
            logic mtimelo;
            logic mtimehi;
        } clint;
        struct {
            logic trigger;
            logic enable;
        } intc;
    } decoded_reg_strb_t;
    decoded_reg_strb_t decoded_reg_strb;
    logic decoded_err;
    logic [12:0] decoded_addr;
    logic decoded_req;
    logic decoded_req_is_wr;
    logic [31:0] decoded_wr_data;
    logic [31:0] decoded_wr_biten;

    always_comb begin
        automatic logic is_valid_addr;
        automatic logic is_valid_rw;
        is_valid_addr = '1; // No valid address check
        is_valid_rw = '1; // No valid RW check
        decoded_reg_strb.clint.msip = cpuif_req_masked & (cpuif_addr == 13'h0);
        decoded_reg_strb.clint.mtimecmplo = cpuif_req_masked & (cpuif_addr == 13'h4);
        decoded_reg_strb.clint.mtimecmphi = cpuif_req_masked & (cpuif_addr == 13'h8);
        decoded_reg_strb.clint.mtimelo = cpuif_req_masked & (cpuif_addr == 13'hc) & !cpuif_req_is_wr;
        decoded_reg_strb.clint.mtimehi = cpuif_req_masked & (cpuif_addr == 13'h10) & !cpuif_req_is_wr;
        decoded_reg_strb.intc.trigger = cpuif_req_masked & (cpuif_addr == 13'h1000);
        decoded_reg_strb.intc.enable = cpuif_req_masked & (cpuif_addr == 13'h1004);
        decoded_err = '0;
    end

    // Pass down signals to next stage
    assign decoded_addr = cpuif_addr;
    assign decoded_req = cpuif_req_masked;
    assign decoded_req_is_wr = cpuif_req_is_wr;
    assign decoded_wr_data = cpuif_wr_data;
    assign decoded_wr_biten = cpuif_wr_biten;

    //--------------------------------------------------------------------------
    // Field logic
    //--------------------------------------------------------------------------
    typedef struct {
        struct {
            struct {
                struct {
                    logic next;
                    logic load_next;
                } Pending;
            } msip;
            struct {
                struct {
                    logic [31:0] next;
                    logic load_next;
                } Value;
            } mtimecmplo;
            struct {
                struct {
                    logic [31:0] next;
                    logic load_next;
                } Value;
            } mtimecmphi;
        } clint;
        struct {
            struct {
                struct {
                    logic next;
                    logic load_next;
                } Set;
            } trigger;
            struct {
                struct {
                    logic next;
                    logic load_next;
                } Enable;
            } enable;
        } intc;
    } field_combo_t;
    field_combo_t field_combo;

    typedef struct {
        struct {
            struct {
                struct {
                    logic value;
                } Pending;
            } msip;
            struct {
                struct {
                    logic [31:0] value;
                } Value;
            } mtimecmplo;
            struct {
                struct {
                    logic [31:0] value;
                } Value;
            } mtimecmphi;
        } clint;
        struct {
            struct {
                struct {
                    logic value;
                } Set;
            } trigger;
            struct {
                struct {
                    logic value;
                } Enable;
            } enable;
        } intc;
    } field_storage_t;
    field_storage_t field_storage;

    // Field: ct_soc_periph.clint.msip.Pending
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.clint.msip.Pending.value;
        load_next_c = '0;
        if(decoded_reg_strb.clint.msip && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.clint.msip.Pending.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end
        field_combo.clint.msip.Pending.next = next_c;
        field_combo.clint.msip.Pending.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.clint.msip.Pending.value <= 1'h0;
        end else begin
            if(field_combo.clint.msip.Pending.load_next) begin
                field_storage.clint.msip.Pending.value <= field_combo.clint.msip.Pending.next;
            end
        end
    end
    assign hwif_out.clint.msip.Pending.value = field_storage.clint.msip.Pending.value;
    // Field: ct_soc_periph.clint.mtimecmplo.Value
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.clint.mtimecmplo.Value.value;
        load_next_c = '0;
        if(decoded_reg_strb.clint.mtimecmplo && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.clint.mtimecmplo.Value.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.clint.mtimecmplo.Value.next = next_c;
        field_combo.clint.mtimecmplo.Value.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.clint.mtimecmplo.Value.value <= 32'hffffffff;
        end else begin
            if(field_combo.clint.mtimecmplo.Value.load_next) begin
                field_storage.clint.mtimecmplo.Value.value <= field_combo.clint.mtimecmplo.Value.next;
            end
        end
    end
    assign hwif_out.clint.mtimecmplo.Value.value = field_storage.clint.mtimecmplo.Value.value;
    // Field: ct_soc_periph.clint.mtimecmphi.Value
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.clint.mtimecmphi.Value.value;
        load_next_c = '0;
        if(decoded_reg_strb.clint.mtimecmphi && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.clint.mtimecmphi.Value.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.clint.mtimecmphi.Value.next = next_c;
        field_combo.clint.mtimecmphi.Value.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.clint.mtimecmphi.Value.value <= 32'hffffffff;
        end else begin
            if(field_combo.clint.mtimecmphi.Value.load_next) begin
                field_storage.clint.mtimecmphi.Value.value <= field_combo.clint.mtimecmphi.Value.next;
            end
        end
    end
    assign hwif_out.clint.mtimecmphi.Value.value = field_storage.clint.mtimecmphi.Value.value;
    // Field: ct_soc_periph.intc.trigger.Set
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.intc.trigger.Set.value;
        load_next_c = '0;
        if(decoded_reg_strb.intc.trigger && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.intc.trigger.Set.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end
        field_combo.intc.trigger.Set.next = next_c;
        field_combo.intc.trigger.Set.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.intc.trigger.Set.value <= 1'h0;
        end else begin
            if(field_combo.intc.trigger.Set.load_next) begin
                field_storage.intc.trigger.Set.value <= field_combo.intc.trigger.Set.next;
            end
        end
    end
    assign hwif_out.intc.trigger.Set.value = field_storage.intc.trigger.Set.value;
    // Field: ct_soc_periph.intc.enable.Enable
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.intc.enable.Enable.value;
        load_next_c = '0;
        if(decoded_reg_strb.intc.enable && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.intc.enable.Enable.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end
        field_combo.intc.enable.Enable.next = next_c;
        field_combo.intc.enable.Enable.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.intc.enable.Enable.value <= 1'h0;
        end else begin
            if(field_combo.intc.enable.Enable.load_next) begin
                field_storage.intc.enable.Enable.value <= field_combo.intc.enable.Enable.next;
            end
        end
    end
    assign hwif_out.intc.enable.Enable.value = field_storage.intc.enable.Enable.value;

    //--------------------------------------------------------------------------
    // Write response
    //--------------------------------------------------------------------------
    assign cpuif_wr_ack = decoded_req & decoded_req_is_wr;
    // Writes are always granted with no error response
    assign cpuif_wr_err = '0;

    //--------------------------------------------------------------------------
    // Readback
    //--------------------------------------------------------------------------

    logic [12:0] rd_mux_addr;
    assign rd_mux_addr = decoded_addr;

    logic readback_err;
    logic readback_done;
    logic [31:0] readback_data;
    always_comb begin
        automatic logic [31:0] readback_data_var;
        readback_data_var = '0;
        if(rd_mux_addr == 13'h0) begin
            readback_data_var[0] = field_storage.clint.msip.Pending.value;
        end
        if(rd_mux_addr == 13'h4) begin
            readback_data_var[31:0] = field_storage.clint.mtimecmplo.Value.value;
        end
        if(rd_mux_addr == 13'h8) begin
            readback_data_var[31:0] = field_storage.clint.mtimecmphi.Value.value;
        end
        if(rd_mux_addr == 13'hc) begin
            readback_data_var[31:0] = hwif_in.clint.mtimelo.Value.next;
        end
        if(rd_mux_addr == 13'h10) begin
            readback_data_var[31:0] = hwif_in.clint.mtimehi.Value.next;
        end
        if(rd_mux_addr == 13'h1000) begin
            readback_data_var[0] = field_storage.intc.trigger.Set.value;
        end
        if(rd_mux_addr == 13'h1004) begin
            readback_data_var[0] = field_storage.intc.enable.Enable.value;
        end
        readback_data = readback_data_var;
        readback_done = decoded_req & ~decoded_req_is_wr;
        readback_err = '0;
    end

    assign cpuif_rd_ack = readback_done;
    assign cpuif_rd_data = readback_data;
    assign cpuif_rd_err = readback_err;
endmodule
