// SPDX-FileCopyrightText: 2026 Accemic Technologies GmbH
// SPDX-License-Identifier: CERN-OHL-S-2.0 OR LicenseRef-Accemic-Commercial

// vim: set ts=4 noet:
// -*- indent-tabs-mode: t; tab-width: 4 -*-
`default_nettype none

/**
 * @brief    Hardware-sequence replay: bisects encoder core against adapter path.
 *
 * @details
 *   Drives the EXACT instruction sequence of a hardware run -- oracle and
 *   pcinfo auto-generated by scripts/gen_replay.py into replay_seq.svh --
 *   through the simulated encoder with the EXACT hardware configuration
 *   (full compression suite, InstSyncMode=INSTRUCTIONS with Max=0).
 *
 *   Observed on hardware: after each VendorBP the next ICNT carrier is short
 *   by exactly two half-words ("ICNT adjust: 40 to -6" after three TCODE 56
 *   messages).
 *     - If the replay reproduces the error, the defect is in the ENCODER core
 *       and can be fixed in simulation.
 *     - If the replay stays clean, the defect is specific to the adapter path
 *       on that board.
 *
 *   Gates: scripts/cli_boardreplay_test.sh
 *     R0  >=1 periodic sync and >=1 VendorBP -> axis and feature were active
 *     R1  NexRv -bp decode against the captured pcinfo, PC comparison against
 *         the oracle prefix. "Decoded OK" plus an identical prefix means the
 *         encoder is clean (pointing at the adapter); an abort with an ICNT
 *         adjust means the defect reproduces here.
 */
module board_replay_tb;

	import cpu_model_pkg::*;

	ct_env #(
		.SPLIT_DATA_ACCESS   (0),
		.CYCLES_PER_INSTR    (1),
		.ATB_CLK_HALF_NS     (5),
		.PROC_CLK_HALF_NS    (5),
		.ATB_DUMP_PATH       ("board_replay_tb.atb.bin"),
		.TIP_DUMP_TXT_PATH   ("board_replay_tb.tip.txt"),
		.NEXRV_INFO_PATH     ("board_replay_tb.nexrv.info"),
		.EXPECTED_PCS_PATH   ("board_replay_tb.expected.pcs")
	) env ();

	`include "replay_seq.svh"

	initial begin
		$display("[board_replay_tb] %0t: waiting for reset release", $time);
		env.wait_for_reset_release();

		env.csr.clear();
		// Difference to the other legs: the hardware campaign never writes
		// trTsControl, so the reset default leaves timestamps ACTIVE and every
		// message carries a TSTAMP field. Reproduce that here:
		env.csr.Set_te_trTsControl_Active       (1'b1);
		// Captured configuration: sync on instructions, Max=0 (2^4 = 16).
		env.csr.Set_te_trTeControl_InstSyncMode (4'd6);
		env.csr.Set_te_trTeControl_InstSyncMax  (4'd0);
		env.csr.Set_te_trTeInstFeatures_InstEnBranchPrediction (1'b1);
		env.csr.Set_te_trTeInstFeatures_InstEnJumpTargetCache  (1'b1);
		env.csr.Set_te_trTeInstFeatures_InstEnImplicitReturn   (1'b1);
		env.csr.Set_te_trTeInstFeatures_InstEnRepeatedHistory  (1'b1);
		env.csr.Set_te_trTeInstFeatures_InstEnWideIcnt         (1'b1);
		env.csr.Set_te_trTeInstFeatures_InstEnRepeatBranch     (1'b1);
		env.csr.Set_te_trTeInstFeatures_InstEnIbhs             (1'b1);
		env.csr.Set_te_trTeInstFeatures_InstEnRepeatInstr      (1'b1);
		$display("[board_replay_tb] replaying captured config: full suite + sync every 16 instructions");
		env.csr.Set_te_trTeControl_Enable       (1'b1);
		env.csr.Set_te_trTeControl_InstTracing  (1'b1);
		env.csr.Set_te_trTeControl_Active       (1'b1);
		env.cpu.idle(20);

		replay_board_seq();

		env.cpu.exit_trace();
		env.cpu.idle(50);
		env.csr.Set_te_trTeControl_InstTracing (1'b0);
		env.cpu.idle(200);
		env.csr.Set_te_trTeControl_Enable      (1'b0);
		env.atb_force_flush = 1'b1;
		env.cpu.idle(4000);
		env.atb_force_flush = 1'b0;
		env.cpu.idle(500);
		env.csr.Set_te_trTeControl_Active(1'b0);
		env.cpu.idle(1000);

		if (env.atb_bytes_seen == 0) $error("[board_replay_tb] no ATB bytes observed");
		$display("[board_replay_tb] PASS (sim); decode gates in scripts/cli_boardreplay_test.sh");
		$finish;
	end

	// Hard timeout
	initial begin
		#40ms;
		$error("[board_replay_tb] TIMEOUT - test exceeded 40 ms wall time");
		$finish;
	end

endmodule
