// SPDX-FileCopyrightText: 2026 Accemic Technologies GmbH
// SPDX-License-Identifier: CERN-OHL-S-2.0 OR LicenseRef-Accemic-Commercial

// vim: set ts=4 noet:
// -*- indent-tabs-mode: t; tab-width: 4 -*-

// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package ct_kv260_ctrl_regs_pkg;

	localparam CT_KV260_CTRL_REGS_DATA_WIDTH = 32;
	localparam CT_KV260_CTRL_REGS_MIN_ADDR_WIDTH = 6;
	localparam CT_KV260_CTRL_REGS_SIZE = 'h3c;

	typedef struct {
		logic next;
	} ct_kv260_ctrl_periph__common__status__trace_wrapped__in_t;

	typedef struct {
		logic [30:0] next;
	} ct_kv260_ctrl_periph__common__status__top_status__in_t;

	typedef struct {
		ct_kv260_ctrl_periph__common__status__trace_wrapped__in_t trace_wrapped;
		ct_kv260_ctrl_periph__common__status__top_status__in_t top_status;
	} ct_kv260_ctrl_periph__common__status__in_t;

	typedef struct {
		logic [31:0] next;
	} ct_kv260_ctrl_periph__common__trace_beats__value__in_t;

	typedef struct {
		ct_kv260_ctrl_periph__common__trace_beats__value__in_t value;
	} ct_kv260_ctrl_periph__common__trace_beats__in_t;

	typedef struct {
		logic [31:0] next;
	} ct_kv260_ctrl_periph__common__trace_bytes__value__in_t;

	typedef struct {
		ct_kv260_ctrl_periph__common__trace_bytes__value__in_t value;
	} ct_kv260_ctrl_periph__common__trace_bytes__in_t;

	typedef struct {
		logic [31:0] next;
	} ct_kv260_ctrl_periph__common__axis_beats__value__in_t;

	typedef struct {
		ct_kv260_ctrl_periph__common__axis_beats__value__in_t value;
	} ct_kv260_ctrl_periph__common__axis_beats__in_t;

	typedef struct {
		logic [31:0] next;
	} ct_kv260_ctrl_periph__common__trace_bufsz__value__in_t;

	typedef struct {
		ct_kv260_ctrl_periph__common__trace_bufsz__value__in_t value;
	} ct_kv260_ctrl_periph__common__trace_bufsz__in_t;

	typedef struct {
		ct_kv260_ctrl_periph__common__status__in_t status;
		ct_kv260_ctrl_periph__common__trace_beats__in_t trace_beats;
		ct_kv260_ctrl_periph__common__trace_bytes__in_t trace_bytes;
		ct_kv260_ctrl_periph__common__axis_beats__in_t axis_beats;
		ct_kv260_ctrl_periph__common__trace_bufsz__in_t trace_bufsz;
	} ct_kv260_ctrl_periph__common__in_t;

	typedef struct {
		logic [31:0] next;
	} ct_kv260_ctrl_periph__sinks__ddr_base__value__in_t;

	typedef struct {
		ct_kv260_ctrl_periph__sinks__ddr_base__value__in_t value;
	} ct_kv260_ctrl_periph__sinks__ddr_base__in_t;

	typedef struct {
		logic [31:0] next;
	} ct_kv260_ctrl_periph__sinks__ddr_size__value__in_t;

	typedef struct {
		ct_kv260_ctrl_periph__sinks__ddr_size__value__in_t value;
	} ct_kv260_ctrl_periph__sinks__ddr_size__in_t;

	typedef struct {
		logic [31:0] next;
	} ct_kv260_ctrl_periph__sinks__ddr_wptr__value__in_t;

	typedef struct {
		ct_kv260_ctrl_periph__sinks__ddr_wptr__value__in_t value;
	} ct_kv260_ctrl_periph__sinks__ddr_wptr__in_t;

	typedef struct {
		logic next;
	} ct_kv260_ctrl_periph__sinks__sink_stat__ddr_full__in_t;

	typedef struct {
		logic next;
	} ct_kv260_ctrl_periph__sinks__sink_stat__ddr_axi_err__in_t;

	typedef struct {
		logic next;
	} ct_kv260_ctrl_periph__sinks__sink_stat__ddr_wrapped__in_t;

	typedef struct {
		logic next;
	} ct_kv260_ctrl_periph__sinks__sink_stat__uram_stopped__in_t;

	typedef struct {
		logic next;
	} ct_kv260_ctrl_periph__sinks__sink_stat__ddr_cfg_rej__in_t;

	typedef struct {
		ct_kv260_ctrl_periph__sinks__sink_stat__ddr_full__in_t ddr_full;
		ct_kv260_ctrl_periph__sinks__sink_stat__ddr_axi_err__in_t ddr_axi_err;
		ct_kv260_ctrl_periph__sinks__sink_stat__ddr_wrapped__in_t ddr_wrapped;
		ct_kv260_ctrl_periph__sinks__sink_stat__uram_stopped__in_t uram_stopped;
		ct_kv260_ctrl_periph__sinks__sink_stat__ddr_cfg_rej__in_t ddr_cfg_rej;
	} ct_kv260_ctrl_periph__sinks__sink_stat__in_t;

	typedef struct {
		logic [31:0] next;
	} ct_kv260_ctrl_periph__sinks__ddr_drops__value__in_t;

	typedef struct {
		ct_kv260_ctrl_periph__sinks__ddr_drops__value__in_t value;
	} ct_kv260_ctrl_periph__sinks__ddr_drops__in_t;

	typedef struct {
		logic [31:0] next;
	} ct_kv260_ctrl_periph__sinks__pib_drops__value__in_t;

	typedef struct {
		ct_kv260_ctrl_periph__sinks__pib_drops__value__in_t value;
	} ct_kv260_ctrl_periph__sinks__pib_drops__in_t;

	typedef struct {
		logic [31:0] next;
	} ct_kv260_ctrl_periph__sinks__ddr_beats__value__in_t;

	typedef struct {
		ct_kv260_ctrl_periph__sinks__ddr_beats__value__in_t value;
	} ct_kv260_ctrl_periph__sinks__ddr_beats__in_t;

	typedef struct {
		ct_kv260_ctrl_periph__sinks__ddr_base__in_t ddr_base;
		ct_kv260_ctrl_periph__sinks__ddr_size__in_t ddr_size;
		ct_kv260_ctrl_periph__sinks__ddr_wptr__in_t ddr_wptr;
		ct_kv260_ctrl_periph__sinks__sink_stat__in_t sink_stat;
		ct_kv260_ctrl_periph__sinks__ddr_drops__in_t ddr_drops;
		ct_kv260_ctrl_periph__sinks__pib_drops__in_t pib_drops;
		ct_kv260_ctrl_periph__sinks__ddr_beats__in_t ddr_beats;
	} ct_kv260_ctrl_periph__sinks__in_t;

	typedef struct {
		ct_kv260_ctrl_periph__common__in_t common;
		ct_kv260_ctrl_periph__sinks__in_t sinks;
	} ct_kv260_ctrl_periph__in_t;

	typedef struct {
		logic value;
	} ct_kv260_ctrl_periph__common__control__core_run__out_t;

	typedef struct {
		logic value;
	} ct_kv260_ctrl_periph__common__control__trace_clear__out_t;

	typedef struct {
		logic [29:0] value;
	} ct_kv260_ctrl_periph__common__control__top_ctrl__out_t;

	typedef struct {
		ct_kv260_ctrl_periph__common__control__core_run__out_t core_run;
		ct_kv260_ctrl_periph__common__control__trace_clear__out_t trace_clear;
		ct_kv260_ctrl_periph__common__control__top_ctrl__out_t top_ctrl;
	} ct_kv260_ctrl_periph__common__control__out_t;

	typedef struct {
		ct_kv260_ctrl_periph__common__control__out_t control;
	} ct_kv260_ctrl_periph__common__out_t;

	typedef struct {
		logic value;
	} ct_kv260_ctrl_periph__sinks__sink_ctrl__ddr_en__out_t;

	typedef struct {
		logic value;
	} ct_kv260_ctrl_periph__sinks__sink_ctrl__ddr_clear__out_t;

	typedef struct {
		logic value;
	} ct_kv260_ctrl_periph__sinks__sink_ctrl__ddr_circ__out_t;

	typedef struct {
		logic value;
	} ct_kv260_ctrl_periph__sinks__sink_ctrl__uram_oneshot__out_t;

	typedef struct {
		logic value;
	} ct_kv260_ctrl_periph__sinks__sink_ctrl__pib_en__out_t;

	typedef struct {
		logic value;
	} ct_kv260_ctrl_periph__sinks__sink_ctrl__pib_clear__out_t;

	typedef struct {
		logic value;
	} ct_kv260_ctrl_periph__sinks__sink_ctrl__pib_calib__out_t;

	typedef struct {
		logic [2:0] value;
	} ct_kv260_ctrl_periph__sinks__sink_ctrl__pib_div__out_t;

	typedef struct {
		logic [1:0] value;
	} ct_kv260_ctrl_periph__sinks__sink_ctrl__pib_pattern__out_t;

	typedef struct {
		ct_kv260_ctrl_periph__sinks__sink_ctrl__ddr_en__out_t ddr_en;
		ct_kv260_ctrl_periph__sinks__sink_ctrl__ddr_clear__out_t ddr_clear;
		ct_kv260_ctrl_periph__sinks__sink_ctrl__ddr_circ__out_t ddr_circ;
		ct_kv260_ctrl_periph__sinks__sink_ctrl__uram_oneshot__out_t uram_oneshot;
		ct_kv260_ctrl_periph__sinks__sink_ctrl__pib_en__out_t pib_en;
		ct_kv260_ctrl_periph__sinks__sink_ctrl__pib_clear__out_t pib_clear;
		ct_kv260_ctrl_periph__sinks__sink_ctrl__pib_calib__out_t pib_calib;
		ct_kv260_ctrl_periph__sinks__sink_ctrl__pib_div__out_t pib_div;
		ct_kv260_ctrl_periph__sinks__sink_ctrl__pib_pattern__out_t pib_pattern;
	} ct_kv260_ctrl_periph__sinks__sink_ctrl__out_t;

	typedef struct {
		ct_kv260_ctrl_periph__sinks__sink_ctrl__out_t sink_ctrl;
	} ct_kv260_ctrl_periph__sinks__out_t;

	typedef struct {
		ct_kv260_ctrl_periph__common__out_t common;
		ct_kv260_ctrl_periph__sinks__out_t sinks;
	} ct_kv260_ctrl_periph__out_t;

	typedef enum logic [1:0] {
		ct_kv260_sinks_rf__sink_ctrl__pib_pattern__pib_pattern_e__STANDARD = 'h0,
		ct_kv260_sinks_rf__sink_ctrl__pib_pattern__pib_pattern_e__MOVING_ONE = 'h1,
		ct_kv260_sinks_rf__sink_ctrl__pib_pattern__pib_pattern_e__MOVING_ZERO = 'h2
	} ct_kv260_sinks_rf__sink_ctrl__pib_pattern__pib_pattern_e_e;
endpackage
