// SPDX-FileCopyrightText: 2026 Accemic Technologies GmbH
// SPDX-License-Identifier: CERN-OHL-S-2.0 OR LicenseRef-Accemic-Commercial

// vim: set ts=4 noet:
// -*- indent-tabs-mode: t; tab-width: 4 -*-

// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

module ct_kv260_ctrl_regs (
		input wire clk,
		input wire rst,

		output logic s_axil_awready,
		input wire s_axil_awvalid,
		input wire [5:0] s_axil_awaddr,
		input wire [2:0] s_axil_awprot,
		output logic s_axil_wready,
		input wire s_axil_wvalid,
		input wire [31:0] s_axil_wdata,
		input wire [3:0]s_axil_wstrb,
		input wire s_axil_bready,
		output logic s_axil_bvalid,
		output logic [1:0] s_axil_bresp,
		output logic s_axil_arready,
		input wire s_axil_arvalid,
		input wire [5:0] s_axil_araddr,
		input wire [2:0] s_axil_arprot,
		input wire s_axil_rready,
		output logic s_axil_rvalid,
		output logic [31:0] s_axil_rdata,
		output logic [1:0] s_axil_rresp,

		input ct_kv260_ctrl_regs_pkg::ct_kv260_ctrl_periph__in_t hwif_in,
		output ct_kv260_ctrl_regs_pkg::ct_kv260_ctrl_periph__out_t hwif_out
	);

	//--------------------------------------------------------------------------
	// CPU Bus interface logic
	//--------------------------------------------------------------------------
	logic cpuif_req;
	logic cpuif_req_is_wr;
	logic [5:0] cpuif_addr;
	logic [31:0] cpuif_wr_data;
	logic [31:0] cpuif_wr_biten;
	logic cpuif_req_stall_wr;
	logic cpuif_req_stall_rd;

	logic cpuif_rd_ack;
	logic cpuif_rd_err;
	logic [31:0] cpuif_rd_data;

	logic cpuif_wr_ack;
	logic cpuif_wr_err;

	// Max Outstanding Transactions: 2
	logic [1:0] axil_n_in_flight;
	logic axil_prev_was_rd;
	logic axil_arvalid;
	logic [5:0] axil_araddr;
	logic axil_ar_accept;
	logic axil_awvalid;
	logic [5:0] axil_awaddr;
	logic axil_wvalid;
	logic [31:0] axil_wdata;
	logic [3:0] axil_wstrb;
	logic axil_aw_accept;
	logic axil_resp_acked;

	// Transaction request acceptance
	always_ff @(posedge clk) begin
		if(rst) begin
			axil_prev_was_rd <= '0;
			axil_arvalid <= '0;
			axil_araddr <= '0;
			axil_awvalid <= '0;
			axil_awaddr <= '0;
			axil_wvalid <= '0;
			axil_wdata <= '0;
			axil_wstrb <= '0;
			axil_n_in_flight <= '0;
		end else begin
			// AR* acceptance register
			if(axil_ar_accept) begin
				axil_prev_was_rd <= '1;
				axil_arvalid <= '0;
			end
			if(s_axil_arvalid && s_axil_arready) begin
				axil_arvalid <= '1;
				axil_araddr <= s_axil_araddr;
			end

			// AW* & W* acceptance registers
			if(axil_aw_accept) begin
				axil_prev_was_rd <= '0;
				axil_awvalid <= '0;
				axil_wvalid <= '0;
			end
			if(s_axil_awvalid && s_axil_awready) begin
				axil_awvalid <= '1;
				axil_awaddr <= s_axil_awaddr;
			end
			if(s_axil_wvalid && s_axil_wready) begin
				axil_wvalid <= '1;
				axil_wdata <= s_axil_wdata;
				axil_wstrb <= s_axil_wstrb;
			end

			// Keep track of in-flight transactions
			if((axil_ar_accept || axil_aw_accept) && !axil_resp_acked) begin
				axil_n_in_flight <= axil_n_in_flight + 1'b1;
			end else if(!(axil_ar_accept || axil_aw_accept) && axil_resp_acked) begin
				axil_n_in_flight <= axil_n_in_flight - 1'b1;
			end
		end
	end

	always_comb begin
		s_axil_arready = (!axil_arvalid || axil_ar_accept);
		s_axil_awready = (!axil_awvalid || axil_aw_accept);
		s_axil_wready = (!axil_wvalid || axil_aw_accept);
	end

	// Request dispatch
	always_comb begin
		cpuif_wr_data = axil_wdata;
		for(int i=0; i<4; i++) begin
			cpuif_wr_biten[i*8 +: 8] = {8{axil_wstrb[i]}};
		end
		cpuif_req = '0;
		cpuif_req_is_wr = '0;
		cpuif_addr = '0;
		axil_ar_accept = '0;
		axil_aw_accept = '0;

		if(axil_n_in_flight < 2'd2) begin
			// Can safely issue more transactions without overwhelming response buffer
			if(axil_arvalid && !axil_prev_was_rd) begin
				cpuif_req = '1;
				cpuif_req_is_wr = '0;
				cpuif_addr = {axil_araddr[5:2], 2'b0};
				if(!cpuif_req_stall_rd) axil_ar_accept = '1;
			end else if(axil_awvalid && axil_wvalid) begin
				cpuif_req = '1;
				cpuif_req_is_wr = '1;
				cpuif_addr = {axil_awaddr[5:2], 2'b0};
				if(!cpuif_req_stall_wr) axil_aw_accept = '1;
			end else if(axil_arvalid) begin
				cpuif_req = '1;
				cpuif_req_is_wr = '0;
				cpuif_addr = {axil_araddr[5:2], 2'b0};
				if(!cpuif_req_stall_rd) axil_ar_accept = '1;
			end
		end
	end


	// AXI4-Lite Response Logic
	logic axil_resp_buffer_is_wr[2];
	logic axil_resp_buffer_err[2];
	logic [31:0] axil_resp_buffer_rdata[2];

	logic [1:0] axil_resp_wptr;
	logic [1:0] axil_resp_rptr;

	always_ff @(posedge clk) begin
		if(rst) begin
			for(int i=0; i<2; i++) begin
				axil_resp_buffer_is_wr[i] <= '0;
				axil_resp_buffer_err[i] <= '0;
				axil_resp_buffer_rdata[i] <= '0;
			end
			axil_resp_wptr <= '0;
			axil_resp_rptr <= '0;
		end else begin
			// Store responses in buffer until AXI response channel accepts them
			if(cpuif_rd_ack || cpuif_wr_ack) begin
				if(cpuif_rd_ack) begin
					axil_resp_buffer_is_wr[axil_resp_wptr[0:0]] <= '0;
					axil_resp_buffer_err[axil_resp_wptr[0:0]] <= cpuif_rd_err;
					axil_resp_buffer_rdata[axil_resp_wptr[0:0]] <= cpuif_rd_data;

				end else if(cpuif_wr_ack) begin
					axil_resp_buffer_is_wr[axil_resp_wptr[0:0]] <= '1;
					axil_resp_buffer_err[axil_resp_wptr[0:0]] <= cpuif_wr_err;
				end
				axil_resp_wptr <= axil_resp_wptr + 1'b1;
			end

			// Advance read pointer when acknowledged
			if(axil_resp_acked) begin
				axil_resp_rptr <= axil_resp_rptr + 1'b1;
			end
		end
	end

	always_comb begin
		axil_resp_acked = '0;
		s_axil_bvalid = '0;
		s_axil_rvalid = '0;
		if(axil_resp_rptr != axil_resp_wptr) begin
			if(axil_resp_buffer_is_wr[axil_resp_rptr[0:0]]) begin
				s_axil_bvalid = '1;
				if(s_axil_bready) axil_resp_acked = '1;
			end else begin
				s_axil_rvalid = '1;
				if(s_axil_rready) axil_resp_acked = '1;
			end
		end

		s_axil_rdata = axil_resp_buffer_rdata[axil_resp_rptr[0:0]];
		if(axil_resp_buffer_err[axil_resp_rptr[0:0]]) begin
			s_axil_bresp = 2'b10;
			s_axil_rresp = 2'b10;
		end else begin
			s_axil_bresp = 2'b00;
			s_axil_rresp = 2'b00;
		end
	end

	logic cpuif_req_masked;

	// Read & write latencies are balanced. Stalls not required
	assign cpuif_req_stall_rd = '0;
	assign cpuif_req_stall_wr = '0;
	assign cpuif_req_masked = cpuif_req
							& !(!cpuif_req_is_wr & cpuif_req_stall_rd)
							& !(cpuif_req_is_wr & cpuif_req_stall_wr);

	//--------------------------------------------------------------------------
	// Address Decode
	//--------------------------------------------------------------------------
	typedef struct {
		struct {
			logic control;
			logic status;
			logic trace_beats;
			logic trace_bytes;
			logic axis_beats;
			logic trace_bufsz;
		} common;
		struct {
			logic sink_ctrl;
			logic ddr_base;
			logic ddr_size;
			logic ddr_wptr;
			logic sink_stat;
			logic ddr_drops;
			logic pib_drops;
			logic ddr_beats;
		} sinks;
	} decoded_reg_strb_t;
	decoded_reg_strb_t decoded_reg_strb;
	logic decoded_err;
	logic [5:0] decoded_addr;
	logic decoded_req;
	logic decoded_req_is_wr;
	logic [31:0] decoded_wr_data;
	logic [31:0] decoded_wr_biten;

	always_comb begin
		automatic logic is_valid_addr;
		automatic logic is_valid_rw;
		is_valid_addr = '1; // No valid address check
		is_valid_rw = '1; // No valid RW check
		decoded_reg_strb.common.control = cpuif_req_masked & (cpuif_addr == 6'h0);
		decoded_reg_strb.common.status = cpuif_req_masked & (cpuif_addr == 6'h4) & !cpuif_req_is_wr;
		decoded_reg_strb.common.trace_beats = cpuif_req_masked & (cpuif_addr == 6'h8) & !cpuif_req_is_wr;
		decoded_reg_strb.common.trace_bytes = cpuif_req_masked & (cpuif_addr == 6'hc) & !cpuif_req_is_wr;
		decoded_reg_strb.common.axis_beats = cpuif_req_masked & (cpuif_addr == 6'h10) & !cpuif_req_is_wr;
		decoded_reg_strb.common.trace_bufsz = cpuif_req_masked & (cpuif_addr == 6'h14) & !cpuif_req_is_wr;
		decoded_reg_strb.sinks.sink_ctrl = cpuif_req_masked & (cpuif_addr == 6'h18);
		decoded_reg_strb.sinks.ddr_base = cpuif_req_masked & (cpuif_addr == 6'h1c) & !cpuif_req_is_wr;
		decoded_reg_strb.sinks.ddr_size = cpuif_req_masked & (cpuif_addr == 6'h20) & !cpuif_req_is_wr;
		decoded_reg_strb.sinks.ddr_wptr = cpuif_req_masked & (cpuif_addr == 6'h24) & !cpuif_req_is_wr;
		decoded_reg_strb.sinks.sink_stat = cpuif_req_masked & (cpuif_addr == 6'h28) & !cpuif_req_is_wr;
		decoded_reg_strb.sinks.ddr_drops = cpuif_req_masked & (cpuif_addr == 6'h2c) & !cpuif_req_is_wr;
		decoded_reg_strb.sinks.pib_drops = cpuif_req_masked & (cpuif_addr == 6'h30) & !cpuif_req_is_wr;
		decoded_reg_strb.sinks.ddr_beats = cpuif_req_masked & (cpuif_addr == 6'h38) & !cpuif_req_is_wr;
		decoded_err = '0;
	end

	// Pass down signals to next stage
	assign decoded_addr = cpuif_addr;
	assign decoded_req = cpuif_req_masked;
	assign decoded_req_is_wr = cpuif_req_is_wr;
	assign decoded_wr_data = cpuif_wr_data;
	assign decoded_wr_biten = cpuif_wr_biten;

	//--------------------------------------------------------------------------
	// Field logic
	//--------------------------------------------------------------------------
	typedef struct {
		struct {
			struct {
				struct {
					logic next;
					logic load_next;
				} core_run;
				struct {
					logic next;
					logic load_next;
				} trace_clear;
				struct {
					logic [29:0] next;
					logic load_next;
				} top_ctrl;
			} control;
		} common;
		struct {
			struct {
				struct {
					logic next;
					logic load_next;
				} ddr_en;
				struct {
					logic next;
					logic load_next;
				} ddr_clear;
				struct {
					logic next;
					logic load_next;
				} ddr_circ;
				struct {
					logic next;
					logic load_next;
				} uram_oneshot;
				struct {
					logic next;
					logic load_next;
				} pib_en;
				struct {
					logic next;
					logic load_next;
				} pib_clear;
				struct {
					logic next;
					logic load_next;
				} pib_calib;
				struct {
					logic [2:0] next;
					logic load_next;
				} pib_div;
				struct {
					logic [1:0] next;
					logic load_next;
				} pib_pattern;
			} sink_ctrl;
		} sinks;
	} field_combo_t;
	field_combo_t field_combo;

	typedef struct {
		struct {
			struct {
				struct {
					logic value;
				} core_run;
				struct {
					logic value;
				} trace_clear;
				struct {
					logic [29:0] value;
				} top_ctrl;
			} control;
		} common;
		struct {
			struct {
				struct {
					logic value;
				} ddr_en;
				struct {
					logic value;
				} ddr_clear;
				struct {
					logic value;
				} ddr_circ;
				struct {
					logic value;
				} uram_oneshot;
				struct {
					logic value;
				} pib_en;
				struct {
					logic value;
				} pib_clear;
				struct {
					logic value;
				} pib_calib;
				struct {
					logic [2:0] value;
				} pib_div;
				struct {
					logic [1:0] value;
				} pib_pattern;
			} sink_ctrl;
		} sinks;
	} field_storage_t;
	field_storage_t field_storage;

	// Field: ct_kv260_ctrl_periph.common.control.core_run
	always_comb begin
		automatic logic [0:0] next_c;
		automatic logic load_next_c;
		next_c = field_storage.common.control.core_run.value;
		load_next_c = '0;
		if(decoded_reg_strb.common.control && decoded_req_is_wr) begin // SW write
			next_c = (field_storage.common.control.core_run.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
			load_next_c = '1;
		end
		field_combo.common.control.core_run.next = next_c;
		field_combo.common.control.core_run.load_next = load_next_c;
	end
	always_ff @(posedge clk) begin
		if(rst) begin
			field_storage.common.control.core_run.value <= 1'h0;
		end else begin
			if(field_combo.common.control.core_run.load_next) begin
				field_storage.common.control.core_run.value <= field_combo.common.control.core_run.next;
			end
		end
	end
	assign hwif_out.common.control.core_run.value = field_storage.common.control.core_run.value;
	// Field: ct_kv260_ctrl_periph.common.control.trace_clear
	always_comb begin
		automatic logic [0:0] next_c;
		automatic logic load_next_c;
		next_c = field_storage.common.control.trace_clear.value;
		load_next_c = '0;
		if(decoded_reg_strb.common.control && decoded_req_is_wr) begin // SW write
			next_c = (field_storage.common.control.trace_clear.value & ~decoded_wr_biten[1:1]) | (decoded_wr_data[1:1] & decoded_wr_biten[1:1]);
			load_next_c = '1;
		end
		field_combo.common.control.trace_clear.next = next_c;
		field_combo.common.control.trace_clear.load_next = load_next_c;
	end
	always_ff @(posedge clk) begin
		if(rst) begin
			field_storage.common.control.trace_clear.value <= 1'h0;
		end else begin
			if(field_combo.common.control.trace_clear.load_next) begin
				field_storage.common.control.trace_clear.value <= field_combo.common.control.trace_clear.next;
			end
		end
	end
	assign hwif_out.common.control.trace_clear.value = field_storage.common.control.trace_clear.value;
	// Field: ct_kv260_ctrl_periph.common.control.top_ctrl
	always_comb begin
		automatic logic [29:0] next_c;
		automatic logic load_next_c;
		next_c = field_storage.common.control.top_ctrl.value;
		load_next_c = '0;
		if(decoded_reg_strb.common.control && decoded_req_is_wr) begin // SW write
			next_c = (field_storage.common.control.top_ctrl.value & ~decoded_wr_biten[31:2]) | (decoded_wr_data[31:2] & decoded_wr_biten[31:2]);
			load_next_c = '1;
		end
		field_combo.common.control.top_ctrl.next = next_c;
		field_combo.common.control.top_ctrl.load_next = load_next_c;
	end
	always_ff @(posedge clk) begin
		if(rst) begin
			field_storage.common.control.top_ctrl.value <= 30'h0;
		end else begin
			if(field_combo.common.control.top_ctrl.load_next) begin
				field_storage.common.control.top_ctrl.value <= field_combo.common.control.top_ctrl.next;
			end
		end
	end
	assign hwif_out.common.control.top_ctrl.value = field_storage.common.control.top_ctrl.value;
	// Field: ct_kv260_ctrl_periph.sinks.sink_ctrl.ddr_en
	always_comb begin
		automatic logic [0:0] next_c;
		automatic logic load_next_c;
		next_c = field_storage.sinks.sink_ctrl.ddr_en.value;
		load_next_c = '0;
		if(decoded_reg_strb.sinks.sink_ctrl && decoded_req_is_wr) begin // SW write
			next_c = (field_storage.sinks.sink_ctrl.ddr_en.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
			load_next_c = '1;
		end
		field_combo.sinks.sink_ctrl.ddr_en.next = next_c;
		field_combo.sinks.sink_ctrl.ddr_en.load_next = load_next_c;
	end
	always_ff @(posedge clk) begin
		if(rst) begin
			field_storage.sinks.sink_ctrl.ddr_en.value <= 1'h0;
		end else begin
			if(field_combo.sinks.sink_ctrl.ddr_en.load_next) begin
				field_storage.sinks.sink_ctrl.ddr_en.value <= field_combo.sinks.sink_ctrl.ddr_en.next;
			end
		end
	end
	assign hwif_out.sinks.sink_ctrl.ddr_en.value = field_storage.sinks.sink_ctrl.ddr_en.value;
	// Field: ct_kv260_ctrl_periph.sinks.sink_ctrl.ddr_clear
	always_comb begin
		automatic logic [0:0] next_c;
		automatic logic load_next_c;
		next_c = field_storage.sinks.sink_ctrl.ddr_clear.value;
		load_next_c = '0;
		if(decoded_reg_strb.sinks.sink_ctrl && decoded_req_is_wr) begin // SW write
			next_c = (field_storage.sinks.sink_ctrl.ddr_clear.value & ~decoded_wr_biten[1:1]) | (decoded_wr_data[1:1] & decoded_wr_biten[1:1]);
			load_next_c = '1;
		end
		field_combo.sinks.sink_ctrl.ddr_clear.next = next_c;
		field_combo.sinks.sink_ctrl.ddr_clear.load_next = load_next_c;
	end
	always_ff @(posedge clk) begin
		if(rst) begin
			field_storage.sinks.sink_ctrl.ddr_clear.value <= 1'h0;
		end else begin
			if(field_combo.sinks.sink_ctrl.ddr_clear.load_next) begin
				field_storage.sinks.sink_ctrl.ddr_clear.value <= field_combo.sinks.sink_ctrl.ddr_clear.next;
			end
		end
	end
	assign hwif_out.sinks.sink_ctrl.ddr_clear.value = field_storage.sinks.sink_ctrl.ddr_clear.value;
	// Field: ct_kv260_ctrl_periph.sinks.sink_ctrl.ddr_circ
	always_comb begin
		automatic logic [0:0] next_c;
		automatic logic load_next_c;
		next_c = field_storage.sinks.sink_ctrl.ddr_circ.value;
		load_next_c = '0;
		if(decoded_reg_strb.sinks.sink_ctrl && decoded_req_is_wr) begin // SW write
			next_c = (field_storage.sinks.sink_ctrl.ddr_circ.value & ~decoded_wr_biten[2:2]) | (decoded_wr_data[2:2] & decoded_wr_biten[2:2]);
			load_next_c = '1;
		end
		field_combo.sinks.sink_ctrl.ddr_circ.next = next_c;
		field_combo.sinks.sink_ctrl.ddr_circ.load_next = load_next_c;
	end
	always_ff @(posedge clk) begin
		if(rst) begin
			field_storage.sinks.sink_ctrl.ddr_circ.value <= 1'h0;
		end else begin
			if(field_combo.sinks.sink_ctrl.ddr_circ.load_next) begin
				field_storage.sinks.sink_ctrl.ddr_circ.value <= field_combo.sinks.sink_ctrl.ddr_circ.next;
			end
		end
	end
	assign hwif_out.sinks.sink_ctrl.ddr_circ.value = field_storage.sinks.sink_ctrl.ddr_circ.value;
	// Field: ct_kv260_ctrl_periph.sinks.sink_ctrl.uram_oneshot
	always_comb begin
		automatic logic [0:0] next_c;
		automatic logic load_next_c;
		next_c = field_storage.sinks.sink_ctrl.uram_oneshot.value;
		load_next_c = '0;
		if(decoded_reg_strb.sinks.sink_ctrl && decoded_req_is_wr) begin // SW write
			next_c = (field_storage.sinks.sink_ctrl.uram_oneshot.value & ~decoded_wr_biten[3:3]) | (decoded_wr_data[3:3] & decoded_wr_biten[3:3]);
			load_next_c = '1;
		end
		field_combo.sinks.sink_ctrl.uram_oneshot.next = next_c;
		field_combo.sinks.sink_ctrl.uram_oneshot.load_next = load_next_c;
	end
	always_ff @(posedge clk) begin
		if(rst) begin
			field_storage.sinks.sink_ctrl.uram_oneshot.value <= 1'h0;
		end else begin
			if(field_combo.sinks.sink_ctrl.uram_oneshot.load_next) begin
				field_storage.sinks.sink_ctrl.uram_oneshot.value <= field_combo.sinks.sink_ctrl.uram_oneshot.next;
			end
		end
	end
	assign hwif_out.sinks.sink_ctrl.uram_oneshot.value = field_storage.sinks.sink_ctrl.uram_oneshot.value;
	// Field: ct_kv260_ctrl_periph.sinks.sink_ctrl.pib_en
	always_comb begin
		automatic logic [0:0] next_c;
		automatic logic load_next_c;
		next_c = field_storage.sinks.sink_ctrl.pib_en.value;
		load_next_c = '0;
		if(decoded_reg_strb.sinks.sink_ctrl && decoded_req_is_wr) begin // SW write
			next_c = (field_storage.sinks.sink_ctrl.pib_en.value & ~decoded_wr_biten[4:4]) | (decoded_wr_data[4:4] & decoded_wr_biten[4:4]);
			load_next_c = '1;
		end
		field_combo.sinks.sink_ctrl.pib_en.next = next_c;
		field_combo.sinks.sink_ctrl.pib_en.load_next = load_next_c;
	end
	always_ff @(posedge clk) begin
		if(rst) begin
			field_storage.sinks.sink_ctrl.pib_en.value <= 1'h0;
		end else begin
			if(field_combo.sinks.sink_ctrl.pib_en.load_next) begin
				field_storage.sinks.sink_ctrl.pib_en.value <= field_combo.sinks.sink_ctrl.pib_en.next;
			end
		end
	end
	assign hwif_out.sinks.sink_ctrl.pib_en.value = field_storage.sinks.sink_ctrl.pib_en.value;
	// Field: ct_kv260_ctrl_periph.sinks.sink_ctrl.pib_clear
	always_comb begin
		automatic logic [0:0] next_c;
		automatic logic load_next_c;
		next_c = field_storage.sinks.sink_ctrl.pib_clear.value;
		load_next_c = '0;
		if(decoded_reg_strb.sinks.sink_ctrl && decoded_req_is_wr) begin // SW write
			next_c = (field_storage.sinks.sink_ctrl.pib_clear.value & ~decoded_wr_biten[5:5]) | (decoded_wr_data[5:5] & decoded_wr_biten[5:5]);
			load_next_c = '1;
		end
		field_combo.sinks.sink_ctrl.pib_clear.next = next_c;
		field_combo.sinks.sink_ctrl.pib_clear.load_next = load_next_c;
	end
	always_ff @(posedge clk) begin
		if(rst) begin
			field_storage.sinks.sink_ctrl.pib_clear.value <= 1'h0;
		end else begin
			if(field_combo.sinks.sink_ctrl.pib_clear.load_next) begin
				field_storage.sinks.sink_ctrl.pib_clear.value <= field_combo.sinks.sink_ctrl.pib_clear.next;
			end
		end
	end
	assign hwif_out.sinks.sink_ctrl.pib_clear.value = field_storage.sinks.sink_ctrl.pib_clear.value;
	// Field: ct_kv260_ctrl_periph.sinks.sink_ctrl.pib_calib
	always_comb begin
		automatic logic [0:0] next_c;
		automatic logic load_next_c;
		next_c = field_storage.sinks.sink_ctrl.pib_calib.value;
		load_next_c = '0;
		if(decoded_reg_strb.sinks.sink_ctrl && decoded_req_is_wr) begin // SW write
			next_c = (field_storage.sinks.sink_ctrl.pib_calib.value & ~decoded_wr_biten[6:6]) | (decoded_wr_data[6:6] & decoded_wr_biten[6:6]);
			load_next_c = '1;
		end
		field_combo.sinks.sink_ctrl.pib_calib.next = next_c;
		field_combo.sinks.sink_ctrl.pib_calib.load_next = load_next_c;
	end
	always_ff @(posedge clk) begin
		if(rst) begin
			field_storage.sinks.sink_ctrl.pib_calib.value <= 1'h0;
		end else begin
			if(field_combo.sinks.sink_ctrl.pib_calib.load_next) begin
				field_storage.sinks.sink_ctrl.pib_calib.value <= field_combo.sinks.sink_ctrl.pib_calib.next;
			end
		end
	end
	assign hwif_out.sinks.sink_ctrl.pib_calib.value = field_storage.sinks.sink_ctrl.pib_calib.value;
	// Field: ct_kv260_ctrl_periph.sinks.sink_ctrl.pib_div
	always_comb begin
		automatic logic [2:0] next_c;
		automatic logic load_next_c;
		next_c = field_storage.sinks.sink_ctrl.pib_div.value;
		load_next_c = '0;
		if(decoded_reg_strb.sinks.sink_ctrl && decoded_req_is_wr) begin // SW write
			next_c = (field_storage.sinks.sink_ctrl.pib_div.value & ~decoded_wr_biten[10:8]) | (decoded_wr_data[10:8] & decoded_wr_biten[10:8]);
			load_next_c = '1;
		end
		field_combo.sinks.sink_ctrl.pib_div.next = next_c;
		field_combo.sinks.sink_ctrl.pib_div.load_next = load_next_c;
	end
	always_ff @(posedge clk) begin
		if(rst) begin
			field_storage.sinks.sink_ctrl.pib_div.value <= 3'h0;
		end else begin
			if(field_combo.sinks.sink_ctrl.pib_div.load_next) begin
				field_storage.sinks.sink_ctrl.pib_div.value <= field_combo.sinks.sink_ctrl.pib_div.next;
			end
		end
	end
	assign hwif_out.sinks.sink_ctrl.pib_div.value = field_storage.sinks.sink_ctrl.pib_div.value;
	// Field: ct_kv260_ctrl_periph.sinks.sink_ctrl.pib_pattern
	always_comb begin
		automatic logic [1:0] next_c;
		automatic logic load_next_c;
		next_c = field_storage.sinks.sink_ctrl.pib_pattern.value;
		load_next_c = '0;
		if(decoded_reg_strb.sinks.sink_ctrl && decoded_req_is_wr) begin // SW write
			next_c = (field_storage.sinks.sink_ctrl.pib_pattern.value & ~decoded_wr_biten[13:12]) | (decoded_wr_data[13:12] & decoded_wr_biten[13:12]);
			load_next_c = '1;
		end
		field_combo.sinks.sink_ctrl.pib_pattern.next = next_c;
		field_combo.sinks.sink_ctrl.pib_pattern.load_next = load_next_c;
	end
	always_ff @(posedge clk) begin
		if(rst) begin
			field_storage.sinks.sink_ctrl.pib_pattern.value <= 2'h0;
		end else begin
			if(field_combo.sinks.sink_ctrl.pib_pattern.load_next) begin
				field_storage.sinks.sink_ctrl.pib_pattern.value <= field_combo.sinks.sink_ctrl.pib_pattern.next;
			end
		end
	end
	assign hwif_out.sinks.sink_ctrl.pib_pattern.value = field_storage.sinks.sink_ctrl.pib_pattern.value;

	//--------------------------------------------------------------------------
	// Write response
	//--------------------------------------------------------------------------
	assign cpuif_wr_ack = decoded_req & decoded_req_is_wr;
	// Writes are always granted with no error response
	assign cpuif_wr_err = '0;

	//--------------------------------------------------------------------------
	// Readback
	//--------------------------------------------------------------------------

	logic [5:0] rd_mux_addr;
	assign rd_mux_addr = decoded_addr;

	logic readback_err;
	logic readback_done;
	logic [31:0] readback_data;
	always_comb begin
		automatic logic [31:0] readback_data_var;
		readback_data_var = '0;
		if(rd_mux_addr == 6'h0) begin
			readback_data_var[0] = field_storage.common.control.core_run.value;
			readback_data_var[1] = field_storage.common.control.trace_clear.value;
			readback_data_var[31:2] = field_storage.common.control.top_ctrl.value;
		end
		if(rd_mux_addr == 6'h4) begin
			readback_data_var[0] = hwif_in.common.status.trace_wrapped.next;
			readback_data_var[31:1] = hwif_in.common.status.top_status.next;
		end
		if(rd_mux_addr == 6'h8) begin
			readback_data_var[31:0] = hwif_in.common.trace_beats.value.next;
		end
		if(rd_mux_addr == 6'hc) begin
			readback_data_var[31:0] = hwif_in.common.trace_bytes.value.next;
		end
		if(rd_mux_addr == 6'h10) begin
			readback_data_var[31:0] = hwif_in.common.axis_beats.value.next;
		end
		if(rd_mux_addr == 6'h14) begin
			readback_data_var[31:0] = hwif_in.common.trace_bufsz.value.next;
		end
		if(rd_mux_addr == 6'h18) begin
			readback_data_var[0] = field_storage.sinks.sink_ctrl.ddr_en.value;
			readback_data_var[1] = field_storage.sinks.sink_ctrl.ddr_clear.value;
			readback_data_var[2] = field_storage.sinks.sink_ctrl.ddr_circ.value;
			readback_data_var[3] = field_storage.sinks.sink_ctrl.uram_oneshot.value;
			readback_data_var[4] = field_storage.sinks.sink_ctrl.pib_en.value;
			readback_data_var[5] = field_storage.sinks.sink_ctrl.pib_clear.value;
			readback_data_var[6] = field_storage.sinks.sink_ctrl.pib_calib.value;
			readback_data_var[10:8] = field_storage.sinks.sink_ctrl.pib_div.value;
			readback_data_var[13:12] = field_storage.sinks.sink_ctrl.pib_pattern.value;
		end
		if(rd_mux_addr == 6'h1c) begin
			readback_data_var[31:0] = hwif_in.sinks.ddr_base.value.next;
		end
		if(rd_mux_addr == 6'h20) begin
			readback_data_var[31:0] = hwif_in.sinks.ddr_size.value.next;
		end
		if(rd_mux_addr == 6'h24) begin
			readback_data_var[31:0] = hwif_in.sinks.ddr_wptr.value.next;
		end
		if(rd_mux_addr == 6'h28) begin
			readback_data_var[0] = hwif_in.sinks.sink_stat.ddr_full.next;
			readback_data_var[1] = hwif_in.sinks.sink_stat.ddr_axi_err.next;
			readback_data_var[2] = hwif_in.sinks.sink_stat.ddr_wrapped.next;
			readback_data_var[3] = hwif_in.sinks.sink_stat.uram_stopped.next;
			readback_data_var[4] = hwif_in.sinks.sink_stat.ddr_cfg_rej.next;
		end
		if(rd_mux_addr == 6'h2c) begin
			readback_data_var[31:0] = hwif_in.sinks.ddr_drops.value.next;
		end
		if(rd_mux_addr == 6'h30) begin
			readback_data_var[31:0] = hwif_in.sinks.pib_drops.value.next;
		end
		if(rd_mux_addr == 6'h38) begin
			readback_data_var[31:0] = hwif_in.sinks.ddr_beats.value.next;
		end
		readback_data = readback_data_var;
		readback_done = decoded_req & ~decoded_req_is_wr;
		readback_err = '0;
	end

	assign cpuif_rd_ack = readback_done;
	assign cpuif_rd_data = readback_data;
	assign cpuif_rd_err = readback_err;
endmodule
