// SPDX-FileCopyrightText: 2026 Accemic Technologies GmbH
// SPDX-License-Identifier: CERN-OHL-S-2.0 OR LicenseRef-Accemic-Commercial

// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package ct_cs_cpuif_pkg;

    localparam CT_CS_CPUIF_DATA_WIDTH = 32;
    localparam CT_CS_CPUIF_MIN_ADDR_WIDTH = 15;
    localparam CT_CS_CPUIF_SIZE = 'h6078;
    localparam NUM_TRACE_FILTER = 'h10;
    localparam NUM_TRACE_COMPARATORS = 'h8;
    localparam NUM_PERFCNT_IFETCH_TH_RANGES = 'h3;
    localparam NUM_PERFCNT_DATA_RD_TH_RANGES = 'h3;
    localparam NUM_PERFCNT_DATA_RD_RANGES = 'h7;
    localparam NUM_PERFCNT_DATA_WR_RANGES = 'h7;
    localparam NUM_ACT_ST = 'hf;
    localparam NUM_DF_RANGE = 'hf;
    localparam MAX_I_FILTER = 'h8;
    localparam MAX_J_FILTER = 'h8;
    localparam CSC_COUNTER_DATA_RANGE_COUNT = 'h2;

    typedef struct {
        logic hwclr;
        logic hwset;
    } ct_cs_cpuif__te__trTeControl__InstTracing__in_t;

    typedef struct {
        logic next;
    } ct_cs_cpuif__te__trTeControl__Empty__in_t;

    typedef struct {
        logic next;
    } ct_cs_cpuif__te__trTeControl__InstSyncReq__in_t;

    typedef struct {
        ct_cs_cpuif__te__trTeControl__InstTracing__in_t InstTracing;
        ct_cs_cpuif__te__trTeControl__Empty__in_t Empty;
        ct_cs_cpuif__te__trTeControl__InstSyncReq__in_t InstSyncReq;
    } ct_cs_cpuif__te__trTeControl__in_t;

    typedef struct {
        logic hwclr;
        logic hwset;
    } ct_cs_cpuif__te__trTeDataControl__DataTracing__in_t;

    typedef struct {
        logic next;
    } ct_cs_cpuif__te__trTeDataControl__DataSplitLoad__in_t;

    typedef struct {
        ct_cs_cpuif__te__trTeDataControl__DataTracing__in_t DataTracing;
        ct_cs_cpuif__te__trTeDataControl__DataSplitLoad__in_t DataSplitLoad;
    } ct_cs_cpuif__te__trTeDataControl__in_t;

    typedef struct {
        logic [31:0] next;
    } ct_cs_cpuif__te__trTsCounterLow__Value__in_t;

    typedef struct {
        ct_cs_cpuif__te__trTsCounterLow__Value__in_t Value;
    } ct_cs_cpuif__te__trTsCounterLow__in_t;

    typedef struct {
        logic [31:0] next;
    } ct_cs_cpuif__te__trTsCounterHigh__Value__in_t;

    typedef struct {
        ct_cs_cpuif__te__trTsCounterHigh__Value__in_t Value;
    } ct_cs_cpuif__te__trTsCounterHigh__in_t;

    typedef struct {
        logic next;
    } ct_cs_cpuif__te__trTeCsrControl__trTeCsrSendSync__in_t;

    typedef struct {
        logic next;
    } ct_cs_cpuif__te__trTeCsrControl__trTeCsrSendPC__in_t;

    typedef struct {
        logic next;
    } ct_cs_cpuif__te__trTeCsrControl__trTeCsrSendTS__in_t;

    typedef struct {
        logic next;
    } ct_cs_cpuif__te__trTeCsrControl__trTeCsrSendCC__in_t;

    typedef struct {
        ct_cs_cpuif__te__trTeCsrControl__trTeCsrSendSync__in_t trTeCsrSendSync;
        ct_cs_cpuif__te__trTeCsrControl__trTeCsrSendPC__in_t trTeCsrSendPC;
        ct_cs_cpuif__te__trTeCsrControl__trTeCsrSendTS__in_t trTeCsrSendTS;
        ct_cs_cpuif__te__trTeCsrControl__trTeCsrSendCC__in_t trTeCsrSendCC;
    } ct_cs_cpuif__te__trTeCsrControl__in_t;

    typedef struct {
        logic [14:0] next;
    } ct_cs_cpuif__te__trTeTipFifoStatus__trTeTipFifoMaxFill__in_t;

    typedef struct {
        logic [14:0] next;
    } ct_cs_cpuif__te__trTeTipFifoStatus__trTeTipFifoNumOverflows__in_t;

    typedef struct {
        ct_cs_cpuif__te__trTeTipFifoStatus__trTeTipFifoMaxFill__in_t trTeTipFifoMaxFill;
        ct_cs_cpuif__te__trTeTipFifoStatus__trTeTipFifoNumOverflows__in_t trTeTipFifoNumOverflows;
    } ct_cs_cpuif__te__trTeTipFifoStatus__in_t;

    typedef struct {
        ct_cs_cpuif__te__trTeControl__in_t trTeControl;
        ct_cs_cpuif__te__trTeDataControl__in_t trTeDataControl;
        ct_cs_cpuif__te__trTsCounterLow__in_t trTsCounterLow;
        ct_cs_cpuif__te__trTsCounterHigh__in_t trTsCounterHigh;
        ct_cs_cpuif__te__trTeCsrControl__in_t trTeCsrControl;
        ct_cs_cpuif__te__trTeTipFifoStatus__in_t trTeTipFifoStatus;
    } ct_cs_cpuif__te__in_t;

    typedef struct {
        logic next;
    } ct_cs_cpuif__atb__trAtbBridgeControl__Empty__in_t;

    typedef struct {
        ct_cs_cpuif__atb__trAtbBridgeControl__Empty__in_t Empty;
    } ct_cs_cpuif__atb__trAtbBridgeControl__in_t;

    typedef struct {
        ct_cs_cpuif__atb__trAtbBridgeControl__in_t trAtbBridgeControl;
    } ct_cs_cpuif__atb__in_t;

    typedef struct {
        logic rd_ack;
        logic [31:0] rd_data;
        logic wr_ack;
    } ct_cs_cpuif__watchpoints__in_t;

    typedef struct {
        logic rd_ack;
        logic [31:0] rd_data;
        logic wr_ack;
    } ct_cs_cpuif__mem1__in_t;

    typedef struct {
        ct_cs_cpuif__te__in_t te;
        ct_cs_cpuif__atb__in_t atb;
        ct_cs_cpuif__watchpoints__in_t watchpoints;
        ct_cs_cpuif__mem1__in_t mem1;
    } ct_cs_cpuif__in_t;

    typedef struct {
        logic value;
    } ct_cs_cpuif__te__trTeControl__Active__out_t;

    typedef struct {
        logic value;
    } ct_cs_cpuif__te__trTeControl__Enable__out_t;

    typedef struct {
        logic value;
    } ct_cs_cpuif__te__trTeControl__InstTracing__out_t;

    typedef struct {
        logic [2:0] value;
    } ct_cs_cpuif__te__trTeControl__InstMode__out_t;

    typedef struct {
        logic [1:0] value;
    } ct_cs_cpuif__te__trTeControl__SendConfig__out_t;

    typedef struct {
        logic value;
    } ct_cs_cpuif__te__trTeControl__Context__out_t;

    typedef struct {
        logic value;
    } ct_cs_cpuif__te__trTeControl__InhibitSrc__out_t;

    typedef struct {
        logic [3:0] value;
    } ct_cs_cpuif__te__trTeControl__InstSyncMode__out_t;

    typedef struct {
        logic [3:0] value;
    } ct_cs_cpuif__te__trTeControl__InstSyncMax__out_t;

    typedef struct {
        logic [2:0] value;
    } ct_cs_cpuif__te__trTeControl__Format__out_t;

    typedef struct {
        logic value;
    } ct_cs_cpuif__te__trTeControl__InstSyncReq__out_t;

    typedef struct {
        ct_cs_cpuif__te__trTeControl__Active__out_t Active;
        ct_cs_cpuif__te__trTeControl__Enable__out_t Enable;
        ct_cs_cpuif__te__trTeControl__InstTracing__out_t InstTracing;
        ct_cs_cpuif__te__trTeControl__InstMode__out_t InstMode;
        ct_cs_cpuif__te__trTeControl__SendConfig__out_t SendConfig;
        ct_cs_cpuif__te__trTeControl__Context__out_t Context;
        ct_cs_cpuif__te__trTeControl__InhibitSrc__out_t InhibitSrc;
        ct_cs_cpuif__te__trTeControl__InstSyncMode__out_t InstSyncMode;
        ct_cs_cpuif__te__trTeControl__InstSyncMax__out_t InstSyncMax;
        ct_cs_cpuif__te__trTeControl__Format__out_t Format;
        ct_cs_cpuif__te__trTeControl__InstSyncReq__out_t InstSyncReq;
    } ct_cs_cpuif__te__trTeControl__out_t;

    typedef struct {
        logic [3:0] value;
    } ct_cs_cpuif__te__trTeImpl__VerMajor__out_t;

    typedef struct {
        logic [3:0] value;
    } ct_cs_cpuif__te__trTeImpl__VerMinor__out_t;

    typedef struct {
        logic [3:0] value;
    } ct_cs_cpuif__te__trTeImpl__CompType__out_t;

    typedef struct {
        logic [3:0] value;
    } ct_cs_cpuif__te__trTeImpl__ProtocolMajor__out_t;

    typedef struct {
        logic [3:0] value;
    } ct_cs_cpuif__te__trTeImpl__ProtocolMinor__out_t;

    typedef struct {
        ct_cs_cpuif__te__trTeImpl__VerMajor__out_t VerMajor;
        ct_cs_cpuif__te__trTeImpl__VerMinor__out_t VerMinor;
        ct_cs_cpuif__te__trTeImpl__CompType__out_t CompType;
        ct_cs_cpuif__te__trTeImpl__ProtocolMajor__out_t ProtocolMajor;
        ct_cs_cpuif__te__trTeImpl__ProtocolMinor__out_t ProtocolMinor;
    } ct_cs_cpuif__te__trTeImpl__out_t;

    typedef struct {
        logic [11:0] value;
    } ct_cs_cpuif__te__trTeInstFeatures__SrcID__out_t;

    typedef struct {
        logic [3:0] value;
    } ct_cs_cpuif__te__trTeInstFeatures__SrcBits__out_t;

    typedef struct {
        ct_cs_cpuif__te__trTeInstFeatures__SrcID__out_t SrcID;
        ct_cs_cpuif__te__trTeInstFeatures__SrcBits__out_t SrcBits;
    } ct_cs_cpuif__te__trTeInstFeatures__out_t;

    typedef struct {
        logic [15:0] value;
    } ct_cs_cpuif__te__trTeInstFilters__Filters__out_t;

    typedef struct {
        ct_cs_cpuif__te__trTeInstFilters__Filters__out_t Filters;
    } ct_cs_cpuif__te__trTeInstFilters__out_t;

    typedef struct {
        logic value;
    } ct_cs_cpuif__te__trTeDataControl__DataImplemented__out_t;

    typedef struct {
        logic value;
    } ct_cs_cpuif__te__trTeDataControl__DataTracing__out_t;

    typedef struct {
        logic [1:0] value;
    } ct_cs_cpuif__te__trTeDataControl__DataAddrCompress__out_t;

    typedef struct {
        ct_cs_cpuif__te__trTeDataControl__DataImplemented__out_t DataImplemented;
        ct_cs_cpuif__te__trTeDataControl__DataTracing__out_t DataTracing;
        ct_cs_cpuif__te__trTeDataControl__DataAddrCompress__out_t DataAddrCompress;
    } ct_cs_cpuif__te__trTeDataControl__out_t;

    typedef struct {
        logic [15:0] value;
    } ct_cs_cpuif__te__trTeDataFilters__Filters__out_t;

    typedef struct {
        ct_cs_cpuif__te__trTeDataFilters__Filters__out_t Filters;
    } ct_cs_cpuif__te__trTeDataFilters__out_t;

    typedef struct {
        logic value;
    } ct_cs_cpuif__te__trTsControl__Active__out_t;

    typedef struct {
        logic value;
    } ct_cs_cpuif__te__trTsControl__Count__out_t;

    typedef struct {
        logic value;
    } ct_cs_cpuif__te__trTsControl__Reset__out_t;

    typedef struct {
        logic [2:0] value;
    } ct_cs_cpuif__te__trTsControl__Type__out_t;

    typedef struct {
        logic [1:0] value;
    } ct_cs_cpuif__te__trTsControl__Prescale__out_t;

    typedef struct {
        logic value;
    } ct_cs_cpuif__te__trTsControl__Enable__out_t;

    typedef struct {
        logic [5:0] value;
    } ct_cs_cpuif__te__trTsControl__Width__out_t;

    typedef struct {
        ct_cs_cpuif__te__trTsControl__Active__out_t Active;
        ct_cs_cpuif__te__trTsControl__Count__out_t Count;
        ct_cs_cpuif__te__trTsControl__Reset__out_t Reset;
        ct_cs_cpuif__te__trTsControl__Type__out_t Type;
        ct_cs_cpuif__te__trTsControl__Prescale__out_t Prescale;
        ct_cs_cpuif__te__trTsControl__Enable__out_t Enable;
        ct_cs_cpuif__te__trTsControl__Width__out_t Width;
    } ct_cs_cpuif__te__trTsControl__out_t;

    typedef struct {
        logic value;
    } ct_cs_cpuif__te__trTeFilterx__Control__Enable__out_t;

    typedef struct {
        logic value;
    } ct_cs_cpuif__te__trTeFilterx__Control__MatchPrivilege__out_t;

    typedef struct {
        logic value;
    } ct_cs_cpuif__te__trTeFilterx__Control__MatchEcause__out_t;

    typedef struct {
        logic value;
    } ct_cs_cpuif__te__trTeFilterx__Control__MatchInterrupt__out_t;

    typedef struct {
        logic value;
    } ct_cs_cpuif__te__trTeFilterx__Control__MatchComp1__out_t;

    typedef struct {
        logic [2:0] value;
    } ct_cs_cpuif__te__trTeFilterx__Control__Comp1__out_t;

    typedef struct {
        logic value;
    } ct_cs_cpuif__te__trTeFilterx__Control__MatchComp2__out_t;

    typedef struct {
        logic [2:0] value;
    } ct_cs_cpuif__te__trTeFilterx__Control__Comp2__out_t;

    typedef struct {
        logic value;
    } ct_cs_cpuif__te__trTeFilterx__Control__MatchComp3__out_t;

    typedef struct {
        logic [2:0] value;
    } ct_cs_cpuif__te__trTeFilterx__Control__Comp3__out_t;

    typedef struct {
        logic value;
    } ct_cs_cpuif__te__trTeFilterx__Control__Impdef__out_t;

    typedef struct {
        logic value;
    } ct_cs_cpuif__te__trTeFilterx__Control__Dtype__out_t;

    typedef struct {
        logic value;
    } ct_cs_cpuif__te__trTeFilterx__Control__Dsize__out_t;

    typedef struct {
        ct_cs_cpuif__te__trTeFilterx__Control__Enable__out_t Enable;
        ct_cs_cpuif__te__trTeFilterx__Control__MatchPrivilege__out_t MatchPrivilege;
        ct_cs_cpuif__te__trTeFilterx__Control__MatchEcause__out_t MatchEcause;
        ct_cs_cpuif__te__trTeFilterx__Control__MatchInterrupt__out_t MatchInterrupt;
        ct_cs_cpuif__te__trTeFilterx__Control__MatchComp1__out_t MatchComp1;
        ct_cs_cpuif__te__trTeFilterx__Control__Comp1__out_t Comp1;
        ct_cs_cpuif__te__trTeFilterx__Control__MatchComp2__out_t MatchComp2;
        ct_cs_cpuif__te__trTeFilterx__Control__Comp2__out_t Comp2;
        ct_cs_cpuif__te__trTeFilterx__Control__MatchComp3__out_t MatchComp3;
        ct_cs_cpuif__te__trTeFilterx__Control__Comp3__out_t Comp3;
        ct_cs_cpuif__te__trTeFilterx__Control__Impdef__out_t Impdef;
        ct_cs_cpuif__te__trTeFilterx__Control__Dtype__out_t Dtype;
        ct_cs_cpuif__te__trTeFilterx__Control__Dsize__out_t Dsize;
    } ct_cs_cpuif__te__trTeFilterx__Control__out_t;

    typedef struct {
        logic [7:0] value;
    } ct_cs_cpuif__te__trTeFilterx__Match__ChoicePrivilege__out_t;

    typedef struct {
        logic value;
    } ct_cs_cpuif__te__trTeFilterx__Match__ValueInterrupt__out_t;

    typedef struct {
        ct_cs_cpuif__te__trTeFilterx__Match__ChoicePrivilege__out_t ChoicePrivilege;
        ct_cs_cpuif__te__trTeFilterx__Match__ValueInterrupt__out_t ValueInterrupt;
    } ct_cs_cpuif__te__trTeFilterx__Match__out_t;

    typedef struct {
        logic [31:0] value;
    } ct_cs_cpuif__te__trTeFilterx__MatchChoiceEcauseLow__Value__out_t;

    typedef struct {
        ct_cs_cpuif__te__trTeFilterx__MatchChoiceEcauseLow__Value__out_t Value;
    } ct_cs_cpuif__te__trTeFilterx__MatchChoiceEcauseLow__out_t;

    typedef struct {
        logic [31:0] value;
    } ct_cs_cpuif__te__trTeFilterx__MatchChoiceEcauseHigh__Value__out_t;

    typedef struct {
        ct_cs_cpuif__te__trTeFilterx__MatchChoiceEcauseHigh__Value__out_t Value;
    } ct_cs_cpuif__te__trTeFilterx__MatchChoiceEcauseHigh__out_t;

    typedef struct {
        logic [31:0] value;
    } ct_cs_cpuif__te__trTeFilterx__MatchValueImpdef__Value__out_t;

    typedef struct {
        ct_cs_cpuif__te__trTeFilterx__MatchValueImpdef__Value__out_t Value;
    } ct_cs_cpuif__te__trTeFilterx__MatchValueImpdef__out_t;

    typedef struct {
        logic [31:0] value;
    } ct_cs_cpuif__te__trTeFilterx__MatchMaskImpdef__Value__out_t;

    typedef struct {
        ct_cs_cpuif__te__trTeFilterx__MatchMaskImpdef__Value__out_t Value;
    } ct_cs_cpuif__te__trTeFilterx__MatchMaskImpdef__out_t;

    typedef struct {
        logic [15:0] value;
    } ct_cs_cpuif__te__trTeFilterx__MatchChoiceData__Dtype__out_t;

    typedef struct {
        logic [7:0] value;
    } ct_cs_cpuif__te__trTeFilterx__MatchChoiceData__Dsize__out_t;

    typedef struct {
        ct_cs_cpuif__te__trTeFilterx__MatchChoiceData__Dtype__out_t Dtype;
        ct_cs_cpuif__te__trTeFilterx__MatchChoiceData__Dsize__out_t Dsize;
    } ct_cs_cpuif__te__trTeFilterx__MatchChoiceData__out_t;

    typedef struct {
        ct_cs_cpuif__te__trTeFilterx__Control__out_t Control;
        ct_cs_cpuif__te__trTeFilterx__Match__out_t Match;
        ct_cs_cpuif__te__trTeFilterx__MatchChoiceEcauseLow__out_t MatchChoiceEcauseLow;
        ct_cs_cpuif__te__trTeFilterx__MatchChoiceEcauseHigh__out_t MatchChoiceEcauseHigh;
        ct_cs_cpuif__te__trTeFilterx__MatchValueImpdef__out_t MatchValueImpdef;
        ct_cs_cpuif__te__trTeFilterx__MatchMaskImpdef__out_t MatchMaskImpdef;
        ct_cs_cpuif__te__trTeFilterx__MatchChoiceData__out_t MatchChoiceData;
    } ct_cs_cpuif__te__trTeFilterx__out_t;

    typedef struct {
        logic [1:0] value;
    } ct_cs_cpuif__te__trTeCompx__Control__PInput__out_t;

    typedef struct {
        logic [1:0] value;
    } ct_cs_cpuif__te__trTeCompx__Control__SInput__out_t;

    typedef struct {
        logic [2:0] value;
    } ct_cs_cpuif__te__trTeCompx__Control__PFunction__out_t;

    typedef struct {
        logic [2:0] value;
    } ct_cs_cpuif__te__trTeCompx__Control__SFunction__out_t;

    typedef struct {
        logic [1:0] value;
    } ct_cs_cpuif__te__trTeCompx__Control__MatchMode__out_t;

    typedef struct {
        logic value;
    } ct_cs_cpuif__te__trTeCompx__Control__PNotify__out_t;

    typedef struct {
        logic value;
    } ct_cs_cpuif__te__trTeCompx__Control__SNotify__out_t;

    typedef struct {
        ct_cs_cpuif__te__trTeCompx__Control__PInput__out_t PInput;
        ct_cs_cpuif__te__trTeCompx__Control__SInput__out_t SInput;
        ct_cs_cpuif__te__trTeCompx__Control__PFunction__out_t PFunction;
        ct_cs_cpuif__te__trTeCompx__Control__SFunction__out_t SFunction;
        ct_cs_cpuif__te__trTeCompx__Control__MatchMode__out_t MatchMode;
        ct_cs_cpuif__te__trTeCompx__Control__PNotify__out_t PNotify;
        ct_cs_cpuif__te__trTeCompx__Control__SNotify__out_t SNotify;
    } ct_cs_cpuif__te__trTeCompx__Control__out_t;

    typedef struct {
        logic [31:0] value;
    } ct_cs_cpuif__te__trTeCompx__PMatchLow__Value__out_t;

    typedef struct {
        ct_cs_cpuif__te__trTeCompx__PMatchLow__Value__out_t Value;
    } ct_cs_cpuif__te__trTeCompx__PMatchLow__out_t;

    typedef struct {
        logic [31:0] value;
    } ct_cs_cpuif__te__trTeCompx__PMatchHigh__Value__out_t;

    typedef struct {
        ct_cs_cpuif__te__trTeCompx__PMatchHigh__Value__out_t Value;
    } ct_cs_cpuif__te__trTeCompx__PMatchHigh__out_t;

    typedef struct {
        logic [31:0] value;
    } ct_cs_cpuif__te__trTeCompx__SMatchLow__Value__out_t;

    typedef struct {
        ct_cs_cpuif__te__trTeCompx__SMatchLow__Value__out_t Value;
    } ct_cs_cpuif__te__trTeCompx__SMatchLow__out_t;

    typedef struct {
        logic [31:0] value;
    } ct_cs_cpuif__te__trTeCompx__SMatchHigh__Value__out_t;

    typedef struct {
        ct_cs_cpuif__te__trTeCompx__SMatchHigh__Value__out_t Value;
    } ct_cs_cpuif__te__trTeCompx__SMatchHigh__out_t;

    typedef struct {
        ct_cs_cpuif__te__trTeCompx__Control__out_t Control;
        ct_cs_cpuif__te__trTeCompx__PMatchLow__out_t PMatchLow;
        ct_cs_cpuif__te__trTeCompx__PMatchHigh__out_t PMatchHigh;
        ct_cs_cpuif__te__trTeCompx__SMatchLow__out_t SMatchLow;
        ct_cs_cpuif__te__trTeCompx__SMatchHigh__out_t SMatchHigh;
    } ct_cs_cpuif__te__trTeCompx__out_t;

    typedef struct {
        logic value;
    } ct_cs_cpuif__te__trTeCsrControl__trTeCsrSendSync__out_t;

    typedef struct {
        logic value;
    } ct_cs_cpuif__te__trTeCsrControl__trTeCsrSendPC__out_t;

    typedef struct {
        logic value;
    } ct_cs_cpuif__te__trTeCsrControl__trTeCsrSendTS__out_t;

    typedef struct {
        logic value;
    } ct_cs_cpuif__te__trTeCsrControl__trTeCsrSendCC__out_t;

    typedef struct {
        ct_cs_cpuif__te__trTeCsrControl__trTeCsrSendSync__out_t trTeCsrSendSync;
        ct_cs_cpuif__te__trTeCsrControl__trTeCsrSendPC__out_t trTeCsrSendPC;
        ct_cs_cpuif__te__trTeCsrControl__trTeCsrSendTS__out_t trTeCsrSendTS;
        ct_cs_cpuif__te__trTeCsrControl__trTeCsrSendCC__out_t trTeCsrSendCC;
    } ct_cs_cpuif__te__trTeCsrControl__out_t;

    typedef struct {
        logic value;
    } ct_cs_cpuif__te__trTeTipFifoStatus__trTeTipFifoMaxFillClear__out_t;

    typedef struct {
        logic value;
    } ct_cs_cpuif__te__trTeTipFifoStatus__trTeTipFifoNumOverflowsClear__out_t;

    typedef struct {
        ct_cs_cpuif__te__trTeTipFifoStatus__trTeTipFifoMaxFillClear__out_t trTeTipFifoMaxFillClear;
        ct_cs_cpuif__te__trTeTipFifoStatus__trTeTipFifoNumOverflowsClear__out_t trTeTipFifoNumOverflowsClear;
    } ct_cs_cpuif__te__trTeTipFifoStatus__out_t;

    typedef struct {
        ct_cs_cpuif__te__trTeControl__out_t trTeControl;
        ct_cs_cpuif__te__trTeImpl__out_t trTeImpl;
        ct_cs_cpuif__te__trTeInstFeatures__out_t trTeInstFeatures;
        ct_cs_cpuif__te__trTeInstFilters__out_t trTeInstFilters;
        ct_cs_cpuif__te__trTeDataControl__out_t trTeDataControl;
        ct_cs_cpuif__te__trTeDataFilters__out_t trTeDataFilters;
        ct_cs_cpuif__te__trTsControl__out_t trTsControl;
        ct_cs_cpuif__te__trTeFilterx__out_t trTeFilter[16];
        ct_cs_cpuif__te__trTeCompx__out_t trTeComp[8];
        ct_cs_cpuif__te__trTeCsrControl__out_t trTeCsrControl;
        ct_cs_cpuif__te__trTeTipFifoStatus__out_t trTeTipFifoStatus;
    } ct_cs_cpuif__te__out_t;

    typedef struct {
        logic value;
    } ct_cs_cpuif__atb__trAtbBridgeControl__Active__out_t;

    typedef struct {
        logic value;
    } ct_cs_cpuif__atb__trAtbBridgeControl__Enable__out_t;

    typedef struct {
        logic [6:0] value;
    } ct_cs_cpuif__atb__trAtbBridgeControl__ID__out_t;

    typedef struct {
        ct_cs_cpuif__atb__trAtbBridgeControl__Active__out_t Active;
        ct_cs_cpuif__atb__trAtbBridgeControl__Enable__out_t Enable;
        ct_cs_cpuif__atb__trAtbBridgeControl__ID__out_t ID;
    } ct_cs_cpuif__atb__trAtbBridgeControl__out_t;

    typedef struct {
        logic [3:0] value;
    } ct_cs_cpuif__atb__trAtbBridgeImpl__VerMajor__out_t;

    typedef struct {
        logic [3:0] value;
    } ct_cs_cpuif__atb__trAtbBridgeImpl__VerMinor__out_t;

    typedef struct {
        logic [3:0] value;
    } ct_cs_cpuif__atb__trAtbBridgeImpl__CompType__out_t;

    typedef struct {
        logic [2:0] value;
    } ct_cs_cpuif__atb__trAtbBridgeImpl__AsyncFreq__out_t;

    typedef struct {
        ct_cs_cpuif__atb__trAtbBridgeImpl__VerMajor__out_t VerMajor;
        ct_cs_cpuif__atb__trAtbBridgeImpl__VerMinor__out_t VerMinor;
        ct_cs_cpuif__atb__trAtbBridgeImpl__CompType__out_t CompType;
        ct_cs_cpuif__atb__trAtbBridgeImpl__AsyncFreq__out_t AsyncFreq;
    } ct_cs_cpuif__atb__trAtbBridgeImpl__out_t;

    typedef struct {
        ct_cs_cpuif__atb__trAtbBridgeControl__out_t trAtbBridgeControl;
        ct_cs_cpuif__atb__trAtbBridgeImpl__out_t trAtbBridgeImpl;
    } ct_cs_cpuif__atb__out_t;

    typedef struct {
        logic value;
    } ct_cs_cpuif__pc__trPcControl__Active__out_t;

    typedef struct {
        ct_cs_cpuif__pc__trPcControl__Active__out_t Active;
    } ct_cs_cpuif__pc__trPcControl__out_t;

    typedef struct {
        logic [3:0] value;
    } ct_cs_cpuif__pc__trPcImpl__VerMajor__out_t;

    typedef struct {
        logic [3:0] value;
    } ct_cs_cpuif__pc__trPcImpl__VerMinor__out_t;

    typedef struct {
        logic [3:0] value;
    } ct_cs_cpuif__pc__trPcImpl__CompType__out_t;

    typedef struct {
        ct_cs_cpuif__pc__trPcImpl__VerMajor__out_t VerMajor;
        ct_cs_cpuif__pc__trPcImpl__VerMinor__out_t VerMinor;
        ct_cs_cpuif__pc__trPcImpl__CompType__out_t CompType;
    } ct_cs_cpuif__pc__trPcImpl__out_t;

    typedef struct {
        logic [4:0] value;
    } ct_cs_cpuif__pc__trTeConstants__num_trace_filter__out_t;

    typedef struct {
        logic [3:0] value;
    } ct_cs_cpuif__pc__trTeConstants__num_trace_comparators__out_t;

    typedef struct {
        logic [3:0] value;
    } ct_cs_cpuif__pc__trTeConstants__num_perfcnt_ifetch_th_ranges__out_t;

    typedef struct {
        logic [3:0] value;
    } ct_cs_cpuif__pc__trTeConstants__num_perfcnt_data_rd_th_ranges__out_t;

    typedef struct {
        logic [3:0] value;
    } ct_cs_cpuif__pc__trTeConstants__num_perfcnt_data_rd_ranges__out_t;

    typedef struct {
        logic [3:0] value;
    } ct_cs_cpuif__pc__trTeConstants__num_perfcnt_data_wr_ranges__out_t;

    typedef struct {
        ct_cs_cpuif__pc__trTeConstants__num_trace_filter__out_t num_trace_filter;
        ct_cs_cpuif__pc__trTeConstants__num_trace_comparators__out_t num_trace_comparators;
        ct_cs_cpuif__pc__trTeConstants__num_perfcnt_ifetch_th_ranges__out_t num_perfcnt_ifetch_th_ranges;
        ct_cs_cpuif__pc__trTeConstants__num_perfcnt_data_rd_th_ranges__out_t num_perfcnt_data_rd_th_ranges;
        ct_cs_cpuif__pc__trTeConstants__num_perfcnt_data_rd_ranges__out_t num_perfcnt_data_rd_ranges;
        ct_cs_cpuif__pc__trTeConstants__num_perfcnt_data_wr_ranges__out_t num_perfcnt_data_wr_ranges;
    } ct_cs_cpuif__pc__trTeConstants__out_t;

    typedef struct {
        logic [7:0] value;
    } ct_cs_cpuif__pc__trPerfCntControl__IFetchThreshold__out_t;

    typedef struct {
        logic [7:0] value;
    } ct_cs_cpuif__pc__trPerfCntControl__DataWrThreshold__out_t;

    typedef struct {
        ct_cs_cpuif__pc__trPerfCntControl__IFetchThreshold__out_t IFetchThreshold;
        ct_cs_cpuif__pc__trPerfCntControl__DataWrThreshold__out_t DataWrThreshold;
    } ct_cs_cpuif__pc__trPerfCntControl__out_t;

    typedef struct {
        logic [31:0] value;
    } ct_cs_cpuif__pc__trTePerfCntIFetchRangex__Low__Value__out_t;

    typedef struct {
        ct_cs_cpuif__pc__trTePerfCntIFetchRangex__Low__Value__out_t Value;
    } ct_cs_cpuif__pc__trTePerfCntIFetchRangex__Low__out_t;

    typedef struct {
        logic [31:0] value;
    } ct_cs_cpuif__pc__trTePerfCntIFetchRangex__High__Value__out_t;

    typedef struct {
        ct_cs_cpuif__pc__trTePerfCntIFetchRangex__High__Value__out_t Value;
    } ct_cs_cpuif__pc__trTePerfCntIFetchRangex__High__out_t;

    typedef struct {
        ct_cs_cpuif__pc__trTePerfCntIFetchRangex__Low__out_t Low;
        ct_cs_cpuif__pc__trTePerfCntIFetchRangex__High__out_t High;
    } ct_cs_cpuif__pc__trTePerfCntIFetchRangex__out_t;

    typedef struct {
        logic [31:0] value;
    } ct_cs_cpuif__pc__trTePerfCntDataRdThRangex__Low__Value__out_t;

    typedef struct {
        ct_cs_cpuif__pc__trTePerfCntDataRdThRangex__Low__Value__out_t Value;
    } ct_cs_cpuif__pc__trTePerfCntDataRdThRangex__Low__out_t;

    typedef struct {
        logic [31:0] value;
    } ct_cs_cpuif__pc__trTePerfCntDataRdThRangex__High__Value__out_t;

    typedef struct {
        ct_cs_cpuif__pc__trTePerfCntDataRdThRangex__High__Value__out_t Value;
    } ct_cs_cpuif__pc__trTePerfCntDataRdThRangex__High__out_t;

    typedef struct {
        ct_cs_cpuif__pc__trTePerfCntDataRdThRangex__Low__out_t Low;
        ct_cs_cpuif__pc__trTePerfCntDataRdThRangex__High__out_t High;
    } ct_cs_cpuif__pc__trTePerfCntDataRdThRangex__out_t;

    typedef struct {
        logic [31:0] value;
    } ct_cs_cpuif__pc__trTePerfCntDataRdRangex__Low__Value__out_t;

    typedef struct {
        ct_cs_cpuif__pc__trTePerfCntDataRdRangex__Low__Value__out_t Value;
    } ct_cs_cpuif__pc__trTePerfCntDataRdRangex__Low__out_t;

    typedef struct {
        logic [31:0] value;
    } ct_cs_cpuif__pc__trTePerfCntDataRdRangex__High__Value__out_t;

    typedef struct {
        ct_cs_cpuif__pc__trTePerfCntDataRdRangex__High__Value__out_t Value;
    } ct_cs_cpuif__pc__trTePerfCntDataRdRangex__High__out_t;

    typedef struct {
        ct_cs_cpuif__pc__trTePerfCntDataRdRangex__Low__out_t Low;
        ct_cs_cpuif__pc__trTePerfCntDataRdRangex__High__out_t High;
    } ct_cs_cpuif__pc__trTePerfCntDataRdRangex__out_t;

    typedef struct {
        logic [31:0] value;
    } ct_cs_cpuif__pc__trTePerfCntDataWrRangex__Low__Value__out_t;

    typedef struct {
        ct_cs_cpuif__pc__trTePerfCntDataWrRangex__Low__Value__out_t Value;
    } ct_cs_cpuif__pc__trTePerfCntDataWrRangex__Low__out_t;

    typedef struct {
        logic [31:0] value;
    } ct_cs_cpuif__pc__trTePerfCntDataWrRangex__High__Value__out_t;

    typedef struct {
        ct_cs_cpuif__pc__trTePerfCntDataWrRangex__High__Value__out_t Value;
    } ct_cs_cpuif__pc__trTePerfCntDataWrRangex__High__out_t;

    typedef struct {
        ct_cs_cpuif__pc__trTePerfCntDataWrRangex__Low__out_t Low;
        ct_cs_cpuif__pc__trTePerfCntDataWrRangex__High__out_t High;
    } ct_cs_cpuif__pc__trTePerfCntDataWrRangex__out_t;

    typedef struct {
        ct_cs_cpuif__pc__trPcControl__out_t trPcControl;
        ct_cs_cpuif__pc__trPcImpl__out_t trPcImpl;
        ct_cs_cpuif__pc__trTeConstants__out_t trTeConstants;
        ct_cs_cpuif__pc__trPerfCntControl__out_t trPerfCntControl;
        ct_cs_cpuif__pc__trTePerfCntIFetchRangex__out_t trTePerfCntIFetchRange[3];
        ct_cs_cpuif__pc__trTePerfCntDataRdThRangex__out_t trTePerfCntDataRdThRange[3];
        ct_cs_cpuif__pc__trTePerfCntDataRdRangex__out_t trTePerfCntDataRdRange[7];
        ct_cs_cpuif__pc__trTePerfCntDataWrRangex__out_t trTePerfCntDataWrRange[7];
    } ct_cs_cpuif__pc__out_t;

    typedef struct {
        logic value;
    } ct_cs_cpuif__trWpControl__Active__out_t;

    typedef struct {
        ct_cs_cpuif__trWpControl__Active__out_t Active;
    } ct_cs_cpuif__trWpControl__out_t;

    typedef struct {
        logic [3:0] value;
    } ct_cs_cpuif__trWpImpl__VerMajor__out_t;

    typedef struct {
        logic [3:0] value;
    } ct_cs_cpuif__trWpImpl__VerMinor__out_t;

    typedef struct {
        logic [3:0] value;
    } ct_cs_cpuif__trWpImpl__CompType__out_t;

    typedef struct {
        ct_cs_cpuif__trWpImpl__VerMajor__out_t VerMajor;
        ct_cs_cpuif__trWpImpl__VerMinor__out_t VerMinor;
        ct_cs_cpuif__trWpImpl__CompType__out_t CompType;
    } ct_cs_cpuif__trWpImpl__out_t;

    typedef struct {
        logic req;
        logic [6:0] addr;
        logic req_is_wr;
        logic [31:0] wr_data;
        logic [31:0] wr_biten;
    } ct_cs_cpuif__watchpoints__out_t;

    typedef struct {
        logic value;
    } ct_cs_cpuif__trDfControl__Active__out_t;

    typedef struct {
        ct_cs_cpuif__trDfControl__Active__out_t Active;
    } ct_cs_cpuif__trDfControl__out_t;

    typedef struct {
        logic [3:0] value;
    } ct_cs_cpuif__trDfImpl__VerMajor__out_t;

    typedef struct {
        logic [3:0] value;
    } ct_cs_cpuif__trDfImpl__VerMinor__out_t;

    typedef struct {
        logic [3:0] value;
    } ct_cs_cpuif__trDfImpl__CompType__out_t;

    typedef struct {
        ct_cs_cpuif__trDfImpl__VerMajor__out_t VerMajor;
        ct_cs_cpuif__trDfImpl__VerMinor__out_t VerMinor;
        ct_cs_cpuif__trDfImpl__CompType__out_t CompType;
    } ct_cs_cpuif__trDfImpl__out_t;

    typedef struct {
        logic req;
        logic [6:0] addr;
        logic req_is_wr;
        logic [31:0] wr_data;
        logic [31:0] wr_biten;
    } ct_cs_cpuif__mem1__out_t;

    typedef struct {
        ct_cs_cpuif__te__out_t te;
        ct_cs_cpuif__atb__out_t atb;
        ct_cs_cpuif__pc__out_t pc;
        ct_cs_cpuif__trWpControl__out_t trWpControl;
        ct_cs_cpuif__trWpImpl__out_t trWpImpl;
        ct_cs_cpuif__watchpoints__out_t watchpoints;
        ct_cs_cpuif__trDfControl__out_t trDfControl;
        ct_cs_cpuif__trDfImpl__out_t trDfImpl;
        ct_cs_cpuif__mem1__out_t mem1;
    } ct_cs_cpuif__out_t;

    typedef enum logic [2:0] {
        ct_cs_cpuif__te__trTeControl__trTeInstMode_e__ITR_BRANCH = 'h3,
        ct_cs_cpuif__te__trTeControl__trTeInstMode_e__ITR_BRANCH_HIST = 'h6
    } ct_cs_cpuif__te__trTeControl__trTeInstMode_e_e;

    typedef enum logic [1:0] {
        ct_cs_cpuif__te__trTeControl__trTeSendConfigMode_e__CFG_NONE = 'h0,
        ct_cs_cpuif__te__trTeControl__trTeSendConfigMode_e__CFG_ONCE = 'h1,
        ct_cs_cpuif__te__trTeControl__trTeSendConfigMode_e__CFG_ON_SYNC = 'h2
    } ct_cs_cpuif__te__trTeControl__trTeSendConfigMode_e_e;

    typedef enum logic [2:0] {
        ct_cs_cpuif__te__trTeControl__trTeInstSyncMode_e__ITR_SYNC_OFF = 'h0,
        ct_cs_cpuif__te__trTeControl__trTeInstSyncMode_e__ITR_SYNC_TRACE_MSG = 'h1,
        ct_cs_cpuif__te__trTeControl__trTeInstSyncMode_e__ITR_SYNC_CLK_CYCLES = 'h2,
        ct_cs_cpuif__te__trTeControl__trTeInstSyncMode_e__ITR_SYNC_HALFWORDS = 'h3,
        ct_cs_cpuif__te__trTeControl__trTeInstSyncMode_e__ITR_SYNC_TRACE_BYTES = 'h4,
        ct_cs_cpuif__te__trTeControl__trTeInstSyncMode_e__ITR_SYNC_WALL_CLK = 'h5,
        ct_cs_cpuif__te__trTeControl__trTeInstSyncMode_e__ITR_SYNC_INSTRUCTIONS = 'h6,
        ct_cs_cpuif__te__trTeControl__trTeInstSyncMode_e__ITR_SYNC_ATB = 'h7
    } ct_cs_cpuif__te__trTeControl__trTeInstSyncMode_e_e;

    typedef enum logic {
        ct_cs_cpuif__te__trTeControl__trTeFormat_e__TR_FORMAT_N = 'h1
    } ct_cs_cpuif__te__trTeControl__trTeFormat_e_e;

    typedef enum logic {
        ct_cs_cpuif__te__trTeDataControl__trTeDataAddrCompress_e__DTR_ADDR_FULL = 'h0
    } ct_cs_cpuif__te__trTeDataControl__trTeDataAddrCompress_e_e;

    typedef enum logic [1:0] {
        ct_cs_cpuif__te__trTsControl__trTsType_e__TR_TS_NONE = 'h0,
        ct_cs_cpuif__te__trTsControl__trTsType_e__TR_TS_SYSTEM = 'h2,
        ct_cs_cpuif__te__trTsControl__trTsType_e__TR_TS_CORE = 'h3
    } ct_cs_cpuif__te__trTsControl__trTsType_e_e;

    typedef enum logic {
        ct_cs_cpuif__te__trTeFilter__Match__trTeFilterMatchInstExInt_e__TR_FILTER_MATCHVALUE_EXCEPTION_TRAP = 'h0,
        ct_cs_cpuif__te__trTeFilter__Match__trTeFilterMatchInstExInt_e__TR_FILTER_MATCHVALUE_INTERRUPT = 'h1
    } ct_cs_cpuif__te__trTeFilter__Match__trTeFilterMatchInstExInt_e_e;

    typedef enum logic [1:0] {
        ct_cs_cpuif__te__trTeComp__Control__trTeCompInput_e__TR_COMP_INPUT_IADDR = 'h0,
        ct_cs_cpuif__te__trTeComp__Control__trTeCompInput_e__TR_COMP_INPUT_CONTEXT = 'h1,
        ct_cs_cpuif__te__trTeComp__Control__trTeCompInput_e__TR_COMP_INPUT_TVAL = 'h2,
        ct_cs_cpuif__te__trTeComp__Control__trTeCompInput_e__TR_COMP_INPUT_DADDR = 'h3
    } ct_cs_cpuif__te__trTeComp__Control__trTeCompInput_e_e;

    typedef enum logic [2:0] {
        ct_cs_cpuif__te__trTeComp__Control__trTeCompPFunction_e__TR_COMP_PFUNC_EQUAL = 'h0,
        ct_cs_cpuif__te__trTeComp__Control__trTeCompPFunction_e__TR_COMP_PFUNC_NOT_EQUAL = 'h1,
        ct_cs_cpuif__te__trTeComp__Control__trTeCompPFunction_e__TR_COMP_PFUNC_LESS = 'h2,
        ct_cs_cpuif__te__trTeComp__Control__trTeCompPFunction_e__TR_COMP_PFUNC_LESS_EQUAL = 'h3,
        ct_cs_cpuif__te__trTeComp__Control__trTeCompPFunction_e__TR_COMP_PFUNC_GREATER = 'h4,
        ct_cs_cpuif__te__trTeComp__Control__trTeCompPFunction_e__TR_COMP_PFUNC_GREATER_EQUAL = 'h5,
        ct_cs_cpuif__te__trTeComp__Control__trTeCompPFunction_e__TR_COMP_PFUNC_RESERVED_MATCH = 'h6,
        ct_cs_cpuif__te__trTeComp__Control__trTeCompPFunction_e__TR_COMP_PFUNC_ALWAYS_MATCH = 'h7
    } ct_cs_cpuif__te__trTeComp__Control__trTeCompPFunction_e_e;

    typedef enum logic [2:0] {
        ct_cs_cpuif__te__trTeComp__Control__trTeCompSFunction_e__TR_COMP_SFUNC_EQUAL = 'h0,
        ct_cs_cpuif__te__trTeComp__Control__trTeCompSFunction_e__TR_COMP_SFUNC_NOT_EQUAL = 'h1,
        ct_cs_cpuif__te__trTeComp__Control__trTeCompSFunction_e__TR_COMP_SFUNC_LESS = 'h2,
        ct_cs_cpuif__te__trTeComp__Control__trTeCompSFunction_e__TR_COMP_SFUNC_LESS_EQUAL = 'h3,
        ct_cs_cpuif__te__trTeComp__Control__trTeCompSFunction_e__TR_COMP_SFUNC_GREATER = 'h4,
        ct_cs_cpuif__te__trTeComp__Control__trTeCompSFunction_e__TR_COMP_SFUNC_GREATER_EQUAL = 'h5,
        ct_cs_cpuif__te__trTeComp__Control__trTeCompSFunction_e__TR_COMP_SFUNC_PMASK = 'h6,
        ct_cs_cpuif__te__trTeComp__Control__trTeCompSFunction_e__TR_COMP_SFUNC_ALWAYS_MATCH = 'h7
    } ct_cs_cpuif__te__trTeComp__Control__trTeCompSFunction_e_e;

    typedef enum logic [1:0] {
        ct_cs_cpuif__te__trTeComp__Control__trTeCompMatchMode_e__TR_COMP_MATCH_MODE0 = 'h0,
        ct_cs_cpuif__te__trTeComp__Control__trTeCompMatchMode_e__TR_COMP_INPUT_MODE1 = 'h1,
        ct_cs_cpuif__te__trTeComp__Control__trTeCompMatchMode_e__TR_COMP_INPUT_MODE2 = 'h2,
        ct_cs_cpuif__te__trTeComp__Control__trTeCompMatchMode_e__TR_COMP_INPUT_MODE3 = 'h3
    } ct_cs_cpuif__te__trTeComp__Control__trTeCompMatchMode_e_e;
endpackage
