#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 Accemic Technologies GmbH
# SPDX-License-Identifier: ISC
#
# Build the axis_wp_demo program (after the common/tgc5b prog/ pattern).
#
# Inputs (src/): crt0.S prog.ld main.c walk.h funcs.c — walk.h/funcs.c are
# GENERATED by gen_program.py and committed; re-run `py gen_program.py`
# before building if you changed the generator.
#
# Outputs (this directory, committed except the ELF):
#   axis_wp_demo.elf   linked ELF (provenance, gitignored)
#   axis_wp_demo.dis   objdump -d disassembly (input for gen_wp_set.py /
#                      check_consistency.py)
#   axis_wp_demo.hex   $readmemh image, one 32-bit word per line, padded
#                      to a whole word (little-endian words)
#
#   axis_wp_demo.pcinfo  NexRv decoder map (feeds the dashboard decode/
#                      live-PC view, package H3) — generated from the .dis
#                      via `NexRv -conv`; committed like the other program
#                      artifacts. Override the binary with NEXRV=…; if no
#                      runnable NexRv is found the step is SKIPPED with a
#                      warning and the committed .pcinfo stays authoritative
#                      (the vendored Windows binary does not run on the
#                      aarch64 board).
#
# Toolchain: override via CROSS=…  (e.g. CROSS=riscv32-unknown-elf-).
# Auto-detection order: riscv32-unknown-elf- on PATH, riscv64-unknown-elf-
# on PATH, then the SysGCC install C:/SysGCC/risc-v/bin (GCC 10.1.0).
# -march: rv32i_zicsr is probed first; GCC 10.1.0 rejects the _zicsr
# suffix ("unsupported ISA subset 'z'") but its default ISA spec 2.2
# includes the CSR instructions in plain rv32i, so rv32i is the fallback.
#
# Endless-walk board build: ENDLESS=1 ./build.sh   (adds -DWALK_ENDLESS=1;
# alternatively poke the WALK_CTRL cell at 0xE800, see src/main.c).

set -euo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
src="$here/src"

# --- toolchain -----------------------------------------------------------
if [ -z "${CROSS:-}" ]; then
	if command -v riscv32-unknown-elf-gcc >/dev/null 2>&1; then
		CROSS=riscv32-unknown-elf-
	elif command -v riscv64-unknown-elf-gcc >/dev/null 2>&1; then
		CROSS=riscv64-unknown-elf-
	elif [ -x /c/SysGCC/risc-v/bin/riscv64-unknown-elf-gcc.exe ]; then
		CROSS=/c/SysGCC/risc-v/bin/riscv64-unknown-elf-
	else
		echo "[build] ERROR: no RISC-V toolchain found (set CROSS=)" >&2
		exit 1
	fi
fi
GCC="${CROSS}gcc"
OBJCOPY="${CROSS}objcopy"
OBJDUMP="${CROSS}objdump"

# --- -march probe (GCC 10 has no _zicsr suffix) --------------------------
march_ok() {
	echo 'int x;' | "$GCC" -march="$1" -mabi=ilp32 -x c -c -o /dev/null - \
		>/dev/null 2>&1
}
if [ -z "${MARCH:-}" ]; then
	if march_ok rv32i_zicsr; then
		MARCH=rv32i_zicsr
	elif march_ok rv32i; then
		MARCH=rv32i
	else
		echo "[build] ERROR: neither rv32i_zicsr nor rv32i accepted by $GCC" >&2
		exit 1
	fi
fi

# --- python (host quirk: 'py' launcher on Windows) ------------------------
if [ -z "${PY:-}" ]; then
	for cand in py python3 python; do
		if command -v "$cand" >/dev/null 2>&1 && "$cand" -c pass >/dev/null 2>&1; then
			PY="$cand"
			break
		fi
	done
fi
[ -n "${PY:-}" ] || { echo "[build] ERROR: no working python (set PY=)" >&2; exit 1; }

elf="$here/axis_wp_demo.elf"
dis="$here/axis_wp_demo.dis"
hex="$here/axis_wp_demo.hex"

# --no-warn-rwx-segments exists only since binutils 2.39 (as does the
# warning it silences) — probe, the GCC 10.1.0 binutils lack both.
ldflags=()
if "${CROSS}ld" --help 2>/dev/null | grep -q 'no-warn-rwx-segments'; then
	ldflags+=(-Wl,--no-warn-rwx-segments)
fi

extra_defs=()
if [ "${ENDLESS:-0}" != "0" ]; then
	extra_defs+=(-DWALK_ENDLESS=1)
	echo "[build] endless-walk board build (-DWALK_ENDLESS=1)"
fi

echo "[build] CROSS=$CROSS MARCH=$MARCH PY=$PY"
echo "[build] compiling + linking ($MARCH / ilp32)"
"$GCC" -march="$MARCH" -mabi=ilp32 -nostdlib -nostartfiles -ffreestanding \
	-O1 -Wall ${ldflags[@]+"${ldflags[@]}"} ${extra_defs[@]+"${extra_defs[@]}"} \
	-T "$src/prog.ld" -o "$elf" \
	"$src/crt0.S" "$src/main.c" "$src/funcs.c"

echo "[build] disassembly -> $dis"
"$OBJDUMP" -d "$elf" > "$dis"

echo "[build] flat binary -> word-per-line hex -> $hex"
bin="$(mktemp)"; trap 'rm -f "$bin"' EXIT
"$OBJCOPY" -O binary "$elf" "$bin"
"$PY" - "$bin" "$hex" <<'PYEOF'
import sys
data = open(sys.argv[1], "rb").read()
data += b"\x00" * ((-len(data)) % 4)               # pad to a whole word
with open(sys.argv[2], "w") as f:
    for i in range(0, len(data), 4):
        f.write("%08x\n" % int.from_bytes(data[i:i+4], "little"))
PYEOF

# --- CTTD pcinfo (dashboard decode/live-PC feed, H3) ----------------------
# The decoder is the fetched CTTD in the repository's bin/ (scripts/fetch_cttd.py);
# NEXRV keeps its historical name as the override, like everywhere else here.
pcinfo="$here/axis_wp_demo.pcinfo"
if [ -z "${NEXRV:-}" ]; then
	for cand in "$here/../../../../bin/cttd-linux-x86_64" \
	            "$here/../../../../bin/cttd-windows-x64.exe" \
	            "$here/../../../../bin/cttd-linux-arm64"; do
		[ -x "$cand" ] && NEXRV="$cand" && break
	done
fi
NEXRV="${NEXRV:-cttd.exe}"
if [ -x "$NEXRV" ] || command -v "$NEXRV" >/dev/null 2>&1; then
	echo "[build] pcinfo -> $pcinfo (CTTD -conv)"
	conv_out="$("$NEXRV" -conv -objd "$dis" -pcinfo "$pcinfo" 2>&1)" \
		&& echo "$conv_out" | grep -q "Converted OK" \
		|| { echo "[build] ERROR: CTTD -conv failed: $conv_out" >&2; exit 1; }
	echo "[build] $conv_out"
else
	echo "[build] WARN: no runnable CTTD ($NEXRV; run scripts/fetch_cttd.py) — pcinfo step skipped," \
	     "committed axis_wp_demo.pcinfo stays as-is" >&2
fi

echo "[build] done:"
ls -l "$elf" "$dis" "$hex"
echo "BUILD_OK"
