#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Accemic Technologies GmbH
# SPDX-License-Identifier: ISC
"""gen_program.py — generate the deterministic axis_wp_demo walk program.

Emits (relative to this script's directory):
  src/funcs.c         ~NUM_FUNCS small noinline leaf functions of varying
                      length (straight-line, no branches, no multiplies so
                      rv32i needs no libgcc), one noinline phase runner per
                      phase with direct calls, and the phase dispatch table.
  src/walk.h          shared constants + externs for main.c.
  expected_walk.txt   the oracle: per phase the exact function-name sequence
                      (runner first, then the leaf functions in call order).

Everything is derived from the fixed SEED below via an in-file xorshift32
PRNG — NO runtime randomness, NO dependency on Python's random module
internals. Re-running the script is byte-stable.

Determinism contract (why the walk is a CFI pre-stage):
  * the timer IRQ only increments a tick counter (pacer);
  * main waits for the next tick and then runs the phase sequence EXACTLY
    once, so the order of function entries is independent of IRQ timing;
  * leaf bodies are straight-line (every body address executes exactly once
    per call), phase runners call leaves directly (each callsite executes
    exactly once per phase run).

Usage:  py gen_program.py
"""

import os
import sys

# ----------------------------------------------------------------------------
# Fixed generator parameters (part of the oracle — bump SEED only together
# with a regeneration of funcs.c/expected_walk.txt and a rebuild).
# ----------------------------------------------------------------------------
SEED = 0xC0FFEE01
NUM_FUNCS = 300          # leaf functions f000..f299
NUM_PHASES = 64          # phase runners run_phase_00..run_phase_63
PHASE_LEN_MIN = 10       # leaf calls per phase (before the mandatory ones
PHASE_LEN_MAX = 14       #  distributed round-robin are counted in)

HERE = os.path.dirname(os.path.abspath(__file__))


class XorShift32:
    """Tiny deterministic PRNG (Marsaglia xorshift32)."""

    def __init__(self, seed):
        self.s = (seed & 0xFFFFFFFF) or 1

    def next(self):
        s = self.s
        s ^= (s << 13) & 0xFFFFFFFF
        s ^= s >> 17
        s ^= (s << 5) & 0xFFFFFFFF
        self.s = s
        return s

    def below(self, n):
        return self.next() % n

    def range(self, lo, hi):
        """Inclusive [lo, hi]."""
        return lo + self.below(hi - lo + 1)

    def shuffle(self, lst):
        """In-place Fisher-Yates."""
        for i in range(len(lst) - 1, 0, -1):
            j = self.below(i + 1)
            lst[i], lst[j] = lst[j], lst[i]


def gen_leaf(idx, rng):
    """One straight-line leaf function of varying length (~6-12 rv32i
    instructions): only ^ + - << >> | on uint32_t and volatile g_acc
    accesses — no branches, no loops, no '*' (would pull in __mulsi3)."""
    name = "f%03d" % idx
    lines = []
    lines.append("uint32_t __attribute__((noinline)) %s(uint32_t x)" % name)
    lines.append("{")
    # First constant: small (1 instr) or large (lui+addi) — spreads lengths.
    if rng.below(2):
        lines.append("\tuint32_t v = x ^ 0x%xu;" % rng.range(1, 0x7FF))
    else:
        lines.append("\tuint32_t v = x ^ 0x%08xu;" % rng.next())
    for _ in range(rng.range(1, 4)):
        op = rng.below(5)
        if op == 0:
            lines.append("\tv += 0x%xu;" % rng.range(1, 0x7FF))
        elif op == 1:
            lines.append("\tv ^= 0x%08xu;" % rng.next())
        elif op == 2:
            sh = rng.range(1, 31)
            lines.append("\tv = (v << %d) | (v >> %d);" % (sh, 32 - sh))
        elif op == 3:
            lines.append("\tg_acc += v;")
        else:
            lines.append("\tv -= 0x%xu;" % rng.range(1, 0x7FF))
    lines.append("\tg_acc ^= v;")
    lines.append("\treturn v;")
    lines.append("}")
    return name, "\n".join(lines)


def build_phases(rng):
    """Return list of NUM_PHASES lists of leaf indices. Every leaf appears
    at least once overall (round-robin of a shuffled full list), phases are
    padded with PRNG picks to PHASE_LEN_MIN..PHASE_LEN_MAX and shuffled."""
    order = list(range(NUM_FUNCS))
    rng.shuffle(order)
    phases = [[] for _ in range(NUM_PHASES)]
    for i, f in enumerate(order):
        phases[i % NUM_PHASES].append(f)
    for seq in phases:
        target = rng.range(PHASE_LEN_MIN, PHASE_LEN_MAX)
        while len(seq) < target:
            seq.append(rng.below(NUM_FUNCS))
        rng.shuffle(seq)
    return phases


def main():
    rng = XorShift32(SEED)

    leaves = [gen_leaf(i, rng) for i in range(NUM_FUNCS)]
    phases = build_phases(rng)

    gen_note = ("GENERATED by gen_program.py (seed=0x%08X, funcs=%d, "
                "phases=%d) -- DO NOT EDIT, regenerate instead."
                % (SEED, NUM_FUNCS, NUM_PHASES))

    # ---- src/walk.h ---------------------------------------------------------
    walk_h = []
    walk_h.append("/* SPDX-FileCopyrightText: 2026 Accemic Technologies GmbH")
    # (split across a concatenation so this emitter line is not itself
    # mistaken for the .py file's own SPDX header by REUSE tooling)
    walk_h.append(" * SPDX-" + "License-Identifier: CERN-OHL-S-2.0 OR LicenseRef-Accemic-Commercial")
    walk_h.append(" * %s */" % gen_note)
    walk_h.append("#ifndef AXIS_WP_DEMO_WALK_H")
    walk_h.append("#define AXIS_WP_DEMO_WALK_H")
    walk_h.append("")
    walk_h.append("#include <stdint.h>")
    walk_h.append("")
    walk_h.append("#define WALK_NUM_PHASES %du" % NUM_PHASES)
    walk_h.append("")
    walk_h.append("typedef void (*walk_phase_fn)(void);")
    walk_h.append("extern const walk_phase_fn walk_phases[%d];" % NUM_PHASES)
    walk_h.append("extern volatile uint32_t g_acc;")
    walk_h.append("")
    walk_h.append("#endif /* AXIS_WP_DEMO_WALK_H */")
    walk_h.append("")

    # ---- src/funcs.c --------------------------------------------------------
    funcs_c = []
    funcs_c.append("/* SPDX-FileCopyrightText: 2026 Accemic Technologies GmbH")
    funcs_c.append(" * SPDX-" + "License-Identifier: CERN-OHL-S-2.0 OR LicenseRef-Accemic-Commercial")
    funcs_c.append(" * %s" % gen_note)
    funcs_c.append(" *")
    funcs_c.append(" * Leaf functions are straight-line on purpose: every instruction of a")
    funcs_c.append(" * called leaf executes exactly once per call, so ANY leaf address is a")
    funcs_c.append(" * deterministic watchpoint. Phase runners use direct calls so every")
    funcs_c.append(" * callsite is a unique, deterministic instruction address too. */")
    funcs_c.append("")
    funcs_c.append('#include "walk.h"')
    funcs_c.append("")
    funcs_c.append("volatile uint32_t g_acc;")
    funcs_c.append("")
    for _, body in leaves:
        funcs_c.append(body)
        funcs_c.append("")
    for p, seq in enumerate(phases):
        funcs_c.append("static void __attribute__((noinline)) run_phase_%02d(void)" % p)
        funcs_c.append("{")
        for f in seq:
            funcs_c.append("\t(void)f%03d(0x%xu);" % (f, rng.range(0, 0x7FF)))
        funcs_c.append("}")
        funcs_c.append("")
    funcs_c.append("const walk_phase_fn walk_phases[%d] = {" % NUM_PHASES)
    for p in range(NUM_PHASES):
        funcs_c.append("\trun_phase_%02d," % p)
    funcs_c.append("};")
    funcs_c.append("")

    # ---- expected_walk.txt --------------------------------------------------
    walk_txt = []
    walk_txt.append("# SPDX-FileCopyrightText: 2026 Accemic Technologies GmbH")
    walk_txt.append("# SPDX-" + "License-Identifier: CERN-OHL-S-2.0 OR LicenseRef-Accemic-Commercial")
    walk_txt.append("# expected_walk -- %s" % gen_note)
    walk_txt.append("# format: P<phase> <runner> <leaf...>   (execution order within the phase;")
    walk_txt.append("#         the runner entry executes first, then the leaves in call order)")
    walk_txt.append("# seed=0x%08X funcs=%d phases=%d" % (SEED, NUM_FUNCS, NUM_PHASES))
    for p, seq in enumerate(phases):
        walk_txt.append("P%d run_phase_%02d %s"
                        % (p, p, " ".join("f%03d" % f for f in seq)))
    walk_txt.append("")

    os.makedirs(os.path.join(HERE, "src"), exist_ok=True)
    outs = [
        (os.path.join(HERE, "src", "walk.h"), "\n".join(walk_h)),
        (os.path.join(HERE, "src", "funcs.c"), "\n".join(funcs_c)),
        (os.path.join(HERE, "expected_walk.txt"), "\n".join(walk_txt)),
    ]
    for path, text in outs:
        with open(path, "w", newline="\n", encoding="utf-8") as f:
            f.write(text)
        print("[gen_program] wrote %s (%d lines)" % (path, text.count("\n")))

    ncalls = sum(len(s) for s in phases)
    print("[gen_program] leaves=%d phases=%d total_calls=%d seed=0x%08X"
          % (NUM_FUNCS, NUM_PHASES, ncalls, SEED))
    return 0


if __name__ == "__main__":
    sys.exit(main())
