// SPDX-FileCopyrightText: 2026 Accemic Technologies GmbH
// SPDX-License-Identifier: CERN-OHL-S-2.0 OR LicenseRef-Accemic-Commercial

// vim: set ts=4 noet:
// -*- indent-tabs-mode: t; tab-width: 4 -*-
`default_nettype none

/**
 * @brief    Oracle replay WITH overflow: the mixed-workload recovery class in
 *           the simulated encoder.
 *
 * @details
 *   Drives the EXACT instruction sequence of a hardware run -- a 30 000
 *   instruction oracle prefix, auto-generated by scripts/gen_replay.py into
 *   replay_seq.svh -- through the simulated encoder with the EXACT hardware
 *   configuration (full suite, timestamps active, periodic sync off), and
 *   forces natural overflows into it by throttling the ATB
 *   (ATB_CLK_HALF_NS=40).
 *
 *   What this adds over gate 09 is the REAL branch-outcome history (one
 *   branch taken 14 376 times, an alternating branch, leaf loops) together
 *   with real predictor training -- exactly the ingredient that makes the
 *   hardware class show VendorBP BCNT misattribution after FIFO_OVERRUN
 *   anchors: BCNT=1 for a branch the decoder sees as freshly not-taken.
 *
 *   Gates: scripts/cli_replayovf_test.sh
 *     T0  >=1 Nexus error message -> a natural overflow was reached
 *     T1  >=1 VendorBP            -> the BP path was active
 *     T2  "Decoded OK" AND every transition legal (scripts/check_transitions.py
 *         against expected.pcs) -- this class otherwise produces silently
 *         wrong PCs
 */
module replay_ovf_tb;

	import cpu_model_pkg::*;

	ct_env #(
		.SPLIT_DATA_ACCESS   (0),
		.CYCLES_PER_INSTR    (1),
		.ATB_CLK_HALF_NS     (40),     // throttle: drain << source rate -> overflow
		.PROC_CLK_HALF_NS    (5),
		.ATB_DUMP_PATH       ("replay_ovf_tb.atb.bin"),
		.TIP_DUMP_TXT_PATH   ("replay_ovf_tb.tip.txt"),
		.NEXRV_INFO_PATH     ("replay_ovf_tb.nexrv.info"),
		.EXPECTED_PCS_PATH   ("replay_ovf_tb.expected.pcs")
	) env ();

	`include "replay_seq.svh"

	initial begin
		$display("[replay_ovf_tb] %0t: waiting for reset release", $time);
		env.wait_for_reset_release();

		env.csr.clear();
		// As in 07: the hardware runs never write trTsControl, so timestamps are ACTIVE.
		env.csr.Set_te_trTsControl_Active       (1'b1);
		// Captured configuration: periodic sync off, full compression suite.
		env.csr.Set_te_trTeInstFeatures_InstEnImplicitReturn   (1'b1);
		env.csr.Set_te_trTeInstFeatures_InstEnBranchPrediction (1'b1);
		env.csr.Set_te_trTeInstFeatures_InstEnJumpTargetCache  (1'b1);
		env.csr.Set_te_trTeInstFeatures_InstEnRepeatedHistory  (1'b1);
		env.csr.Set_te_trTeInstFeatures_InstEnWideIcnt         (1'b1);
		env.csr.Set_te_trTeInstFeatures_InstEnRepeatBranch     (1'b1);
		env.csr.Set_te_trTeInstFeatures_InstEnIbhs             (1'b1);
		env.csr.Set_te_trTeInstFeatures_InstEnRepeatInstr      (1'b1);
		$display("[replay_ovf_tb] replaying captured config: full suite + timestamps + sync off, ATB throttled to 40 ns");
		env.csr.Set_te_trTeControl_Enable       (1'b1);
		env.csr.Set_te_trTeControl_InstTracing  (1'b1);
		env.csr.Set_te_trTeControl_Active       (1'b1);
		env.cpu.idle(20);

		replay_board_seq();

		env.cpu.exit_trace();
		env.cpu.idle(50);
		env.csr.Set_te_trTeControl_InstTracing (1'b0);
		env.cpu.idle(200);
		env.csr.Set_te_trTeControl_Enable      (1'b0);
		env.atb_force_flush = 1'b1;
		env.cpu.idle(8000);
		env.atb_force_flush = 1'b0;
		env.cpu.idle(500);
		env.csr.Set_te_trTeControl_Active(1'b0);
		env.cpu.idle(1000);

		if (env.cpu.event_count() == 0) $error("[replay_ovf_tb] cpu_model event log empty");
		if (env.atb_bytes_seen == 0)    $error("[replay_ovf_tb] no ATB bytes observed");
		$display("[replay_ovf_tb] PASS (sim); decode gates in scripts/cli_replayovf_test.sh");
		$finish;
	end

endmodule
`default_nettype wire
