/* SPDX-FileCopyrightText: 2026 Accemic Technologies GmbH
 * SPDX-License-Identifier: CERN-OHL-S-2.0 OR LicenseRef-Accemic-Commercial
 * GENERATED by gen_program.py (seed=0xC0FFEE01, funcs=300, phases=64) -- DO NOT EDIT, regenerate instead.
 *
 * Leaf functions are straight-line on purpose: every instruction of a
 * called leaf executes exactly once per call, so ANY leaf address is a
 * deterministic watchpoint. Phase runners use direct calls so every
 * callsite is a unique, deterministic instruction address too. */

#include "walk.h"

volatile uint32_t g_acc;

uint32_t __attribute__((noinline)) f000(uint32_t x)
{
	uint32_t v = x ^ 0x776c5329u;
	v = (v << 13) | (v >> 19);
	v -= 0xbbu;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f001(uint32_t x)
{
	uint32_t v = x ^ 0x1bu;
	v = (v << 4) | (v >> 28);
	g_acc += v;
	v ^= 0xa9791059u;
	v -= 0x393u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f002(uint32_t x)
{
	uint32_t v = x ^ 0x2ffu;
	v = (v << 24) | (v >> 8);
	v = (v << 29) | (v >> 3);
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f003(uint32_t x)
{
	uint32_t v = x ^ 0x167u;
	v ^= 0xe92e1ab3u;
	v = (v << 13) | (v >> 19);
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f004(uint32_t x)
{
	uint32_t v = x ^ 0x75au;
	v ^= 0xf3c9d867u;
	g_acc += v;
	v = (v << 4) | (v >> 28);
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f005(uint32_t x)
{
	uint32_t v = x ^ 0x598u;
	v = (v << 2) | (v >> 30);
	v = (v << 29) | (v >> 3);
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f006(uint32_t x)
{
	uint32_t v = x ^ 0x1b2u;
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f007(uint32_t x)
{
	uint32_t v = x ^ 0xd2c819efu;
	v = (v << 11) | (v >> 21);
	v = (v << 23) | (v >> 9);
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f008(uint32_t x)
{
	uint32_t v = x ^ 0xb8dbaaaau;
	v ^= 0x2521c560u;
	v = (v << 13) | (v >> 19);
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f009(uint32_t x)
{
	uint32_t v = x ^ 0x9ef3afeau;
	v = (v << 3) | (v >> 29);
	v ^= 0x841a10ecu;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f010(uint32_t x)
{
	uint32_t v = x ^ 0x20eu;
	v += 0x159u;
	v ^= 0x2b21278du;
	v -= 0x7f7u;
	v ^= 0xce11bb5eu;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f011(uint32_t x)
{
	uint32_t v = x ^ 0x8fu;
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f012(uint32_t x)
{
	uint32_t v = x ^ 0x260u;
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f013(uint32_t x)
{
	uint32_t v = x ^ 0x3f6u;
	v = (v << 13) | (v >> 19);
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f014(uint32_t x)
{
	uint32_t v = x ^ 0x603f2bf8u;
	v -= 0x748u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f015(uint32_t x)
{
	uint32_t v = x ^ 0x3bau;
	v = (v << 18) | (v >> 14);
	v -= 0x52eu;
	v = (v << 21) | (v >> 11);
	v -= 0x2ebu;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f016(uint32_t x)
{
	uint32_t v = x ^ 0xba93977au;
	v ^= 0x50f429e7u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f017(uint32_t x)
{
	uint32_t v = x ^ 0x566u;
	v ^= 0x6806c1f8u;
	g_acc += v;
	v += 0x548u;
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f018(uint32_t x)
{
	uint32_t v = x ^ 0x980aaf1bu;
	v -= 0x238u;
	g_acc += v;
	v = (v << 4) | (v >> 28);
	v = (v << 31) | (v >> 1);
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f019(uint32_t x)
{
	uint32_t v = x ^ 0x7ce28f76u;
	v -= 0x12u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f020(uint32_t x)
{
	uint32_t v = x ^ 0xd34dba44u;
	v += 0x3eu;
	g_acc += v;
	v += 0x7d0u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f021(uint32_t x)
{
	uint32_t v = x ^ 0x0a83d184u;
	v += 0x705u;
	v ^= 0xd6695437u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f022(uint32_t x)
{
	uint32_t v = x ^ 0x9a85870fu;
	v -= 0x8eu;
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f023(uint32_t x)
{
	uint32_t v = x ^ 0x7e1u;
	v += 0x416u;
	v += 0x2f6u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f024(uint32_t x)
{
	uint32_t v = x ^ 0xa3ef7270u;
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f025(uint32_t x)
{
	uint32_t v = x ^ 0xc36fadcdu;
	v -= 0x22au;
	v = (v << 8) | (v >> 24);
	v += 0x42cu;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f026(uint32_t x)
{
	uint32_t v = x ^ 0x5bau;
	g_acc += v;
	g_acc += v;
	v += 0x601u;
	v -= 0x7a4u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f027(uint32_t x)
{
	uint32_t v = x ^ 0x483u;
	v = (v << 27) | (v >> 5);
	v -= 0x2c2u;
	v = (v << 8) | (v >> 24);
	v += 0x42bu;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f028(uint32_t x)
{
	uint32_t v = x ^ 0x3a545bffu;
	v = (v << 21) | (v >> 11);
	v = (v << 29) | (v >> 3);
	v += 0x1d5u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f029(uint32_t x)
{
	uint32_t v = x ^ 0x267u;
	v ^= 0x48f5171bu;
	v = (v << 14) | (v >> 18);
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f030(uint32_t x)
{
	uint32_t v = x ^ 0x330ee073u;
	g_acc += v;
	g_acc += v;
	g_acc += v;
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f031(uint32_t x)
{
	uint32_t v = x ^ 0x1f4u;
	v += 0x1b2u;
	v = (v << 21) | (v >> 11);
	v = (v << 7) | (v >> 25);
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f032(uint32_t x)
{
	uint32_t v = x ^ 0x44871f30u;
	v ^= 0x5b9ee939u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f033(uint32_t x)
{
	uint32_t v = x ^ 0x45du;
	v ^= 0x41ad0e64u;
	v -= 0x353u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f034(uint32_t x)
{
	uint32_t v = x ^ 0x746u;
	v -= 0x278u;
	v -= 0x35eu;
	g_acc += v;
	v ^= 0x1e0c005au;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f035(uint32_t x)
{
	uint32_t v = x ^ 0x351u;
	g_acc += v;
	v -= 0x625u;
	v -= 0x5ebu;
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f036(uint32_t x)
{
	uint32_t v = x ^ 0x6eau;
	g_acc += v;
	v += 0x4a7u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f037(uint32_t x)
{
	uint32_t v = x ^ 0x152u;
	g_acc += v;
	v += 0x5f5u;
	v ^= 0x4a44d1a5u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f038(uint32_t x)
{
	uint32_t v = x ^ 0x483u;
	v += 0x7fbu;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f039(uint32_t x)
{
	uint32_t v = x ^ 0x2a0d5a31u;
	v ^= 0x001f9695u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f040(uint32_t x)
{
	uint32_t v = x ^ 0x47cu;
	v += 0x3a6u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f041(uint32_t x)
{
	uint32_t v = x ^ 0xa6d741adu;
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f042(uint32_t x)
{
	uint32_t v = x ^ 0xae848d67u;
	v += 0x4d2u;
	v = (v << 29) | (v >> 3);
	v ^= 0x83c33297u;
	v -= 0x5a5u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f043(uint32_t x)
{
	uint32_t v = x ^ 0x13u;
	v = (v << 27) | (v >> 5);
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f044(uint32_t x)
{
	uint32_t v = x ^ 0x7e2u;
	v += 0x305u;
	v = (v << 10) | (v >> 22);
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f045(uint32_t x)
{
	uint32_t v = x ^ 0x1c6u;
	v += 0x23fu;
	v += 0x7eau;
	v = (v << 16) | (v >> 16);
	v ^= 0x8044061eu;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f046(uint32_t x)
{
	uint32_t v = x ^ 0x534u;
	g_acc += v;
	v += 0x51bu;
	g_acc += v;
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f047(uint32_t x)
{
	uint32_t v = x ^ 0x425u;
	g_acc += v;
	v -= 0x649u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f048(uint32_t x)
{
	uint32_t v = x ^ 0xb6c0fb9du;
	v -= 0x2ceu;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f049(uint32_t x)
{
	uint32_t v = x ^ 0x9a3af967u;
	v ^= 0x7235c4f4u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f050(uint32_t x)
{
	uint32_t v = x ^ 0x417u;
	v = (v << 19) | (v >> 13);
	v -= 0x7c4u;
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f051(uint32_t x)
{
	uint32_t v = x ^ 0x3b8u;
	g_acc += v;
	g_acc += v;
	v = (v << 11) | (v >> 21);
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f052(uint32_t x)
{
	uint32_t v = x ^ 0xe9b311fbu;
	v ^= 0xb15a3911u;
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f053(uint32_t x)
{
	uint32_t v = x ^ 0x1e0u;
	v = (v << 16) | (v >> 16);
	g_acc += v;
	v += 0x4cu;
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f054(uint32_t x)
{
	uint32_t v = x ^ 0x7e5u;
	v -= 0x7cu;
	v -= 0x79bu;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f055(uint32_t x)
{
	uint32_t v = x ^ 0x3c7u;
	v -= 0x6eau;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f056(uint32_t x)
{
	uint32_t v = x ^ 0x20du;
	g_acc += v;
	v ^= 0xc7ec7f28u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f057(uint32_t x)
{
	uint32_t v = x ^ 0xd0008337u;
	v -= 0x56eu;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f058(uint32_t x)
{
	uint32_t v = x ^ 0x4a59daa5u;
	v += 0x356u;
	g_acc += v;
	v += 0x155u;
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f059(uint32_t x)
{
	uint32_t v = x ^ 0x2b9f1227u;
	g_acc += v;
	v ^= 0x59ea9847u;
	v -= 0x39u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f060(uint32_t x)
{
	uint32_t v = x ^ 0x6dcu;
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f061(uint32_t x)
{
	uint32_t v = x ^ 0x50u;
	v += 0x6f0u;
	v = (v << 30) | (v >> 2);
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f062(uint32_t x)
{
	uint32_t v = x ^ 0x2c6u;
	v ^= 0x69e0edd5u;
	v -= 0x2a4u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f063(uint32_t x)
{
	uint32_t v = x ^ 0xf5cb5110u;
	v -= 0x360u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f064(uint32_t x)
{
	uint32_t v = x ^ 0x28cu;
	v -= 0x77cu;
	v += 0x475u;
	v -= 0x2e9u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f065(uint32_t x)
{
	uint32_t v = x ^ 0x200u;
	v ^= 0x8bc4ef78u;
	g_acc += v;
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f066(uint32_t x)
{
	uint32_t v = x ^ 0x731u;
	v ^= 0xedaad2ffu;
	v -= 0x3ebu;
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f067(uint32_t x)
{
	uint32_t v = x ^ 0xfed1c9bbu;
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f068(uint32_t x)
{
	uint32_t v = x ^ 0x3c4dcfc3u;
	v -= 0x73eu;
	v = (v << 22) | (v >> 10);
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f069(uint32_t x)
{
	uint32_t v = x ^ 0xd3333907u;
	v = (v << 5) | (v >> 27);
	v = (v << 6) | (v >> 26);
	v += 0x718u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f070(uint32_t x)
{
	uint32_t v = x ^ 0x69014b57u;
	g_acc += v;
	v ^= 0x5ab8a76cu;
	v -= 0x32du;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f071(uint32_t x)
{
	uint32_t v = x ^ 0xc729828eu;
	v += 0x696u;
	v ^= 0x5f658f8fu;
	v -= 0x127u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f072(uint32_t x)
{
	uint32_t v = x ^ 0x1afu;
	v += 0x2fbu;
	v -= 0x6b2u;
	v += 0x100u;
	v += 0x79eu;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f073(uint32_t x)
{
	uint32_t v = x ^ 0x7c8u;
	v -= 0x6c2u;
	v += 0x737u;
	v = (v << 24) | (v >> 8);
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f074(uint32_t x)
{
	uint32_t v = x ^ 0xdfu;
	v = (v << 3) | (v >> 29);
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f075(uint32_t x)
{
	uint32_t v = x ^ 0x20u;
	v -= 0x689u;
	v ^= 0x8ac3a0ceu;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f076(uint32_t x)
{
	uint32_t v = x ^ 0x415u;
	v ^= 0xa01836b3u;
	v ^= 0xb4690fe6u;
	v += 0xe3u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f077(uint32_t x)
{
	uint32_t v = x ^ 0x4ccu;
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f078(uint32_t x)
{
	uint32_t v = x ^ 0x737u;
	g_acc += v;
	v -= 0x7c7u;
	g_acc += v;
	v ^= 0x7fce103cu;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f079(uint32_t x)
{
	uint32_t v = x ^ 0xcf29c95du;
	v = (v << 28) | (v >> 4);
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f080(uint32_t x)
{
	uint32_t v = x ^ 0x6d9u;
	v = (v << 31) | (v >> 1);
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f081(uint32_t x)
{
	uint32_t v = x ^ 0x246fde27u;
	g_acc += v;
	v += 0x4a5u;
	v = (v << 28) | (v >> 4);
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f082(uint32_t x)
{
	uint32_t v = x ^ 0xe1cfa0d8u;
	v ^= 0xdb737cb7u;
	v -= 0x7c6u;
	v += 0x749u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f083(uint32_t x)
{
	uint32_t v = x ^ 0xda210d67u;
	v -= 0x25cu;
	v -= 0x21fu;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f084(uint32_t x)
{
	uint32_t v = x ^ 0x793u;
	v ^= 0xe9c9ad54u;
	v += 0x511u;
	v ^= 0x0148d8f9u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f085(uint32_t x)
{
	uint32_t v = x ^ 0x523d54dfu;
	v ^= 0xf5c74445u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f086(uint32_t x)
{
	uint32_t v = x ^ 0xaeb675b1u;
	v = (v << 4) | (v >> 28);
	v += 0x45au;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f087(uint32_t x)
{
	uint32_t v = x ^ 0x356u;
	v -= 0x27au;
	v -= 0x8bu;
	v += 0x2f2u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f088(uint32_t x)
{
	uint32_t v = x ^ 0xf5ca3165u;
	g_acc += v;
	v += 0x19cu;
	v ^= 0x9c5a7447u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f089(uint32_t x)
{
	uint32_t v = x ^ 0x5181ade6u;
	v ^= 0xb8031728u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f090(uint32_t x)
{
	uint32_t v = x ^ 0x309u;
	v += 0x4cbu;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f091(uint32_t x)
{
	uint32_t v = x ^ 0x3d5dfaf0u;
	v ^= 0xe3f5215au;
	v ^= 0xac05e0bfu;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f092(uint32_t x)
{
	uint32_t v = x ^ 0x422131b8u;
	g_acc += v;
	v -= 0x5e7u;
	v = (v << 15) | (v >> 17);
	v ^= 0xb1710ff2u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f093(uint32_t x)
{
	uint32_t v = x ^ 0x746u;
	v += 0x452u;
	v -= 0x65u;
	v = (v << 18) | (v >> 14);
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f094(uint32_t x)
{
	uint32_t v = x ^ 0xf625dbbfu;
	v -= 0x16fu;
	v = (v << 27) | (v >> 5);
	v -= 0x740u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f095(uint32_t x)
{
	uint32_t v = x ^ 0x68cu;
	v += 0x30eu;
	v += 0x41bu;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f096(uint32_t x)
{
	uint32_t v = x ^ 0x453u;
	v -= 0x739u;
	v = (v << 4) | (v >> 28);
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f097(uint32_t x)
{
	uint32_t v = x ^ 0x238u;
	v = (v << 25) | (v >> 7);
	v ^= 0x52e833c1u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f098(uint32_t x)
{
	uint32_t v = x ^ 0x273u;
	v = (v << 6) | (v >> 26);
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f099(uint32_t x)
{
	uint32_t v = x ^ 0x1c3u;
	v += 0x42au;
	v += 0x25bu;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f100(uint32_t x)
{
	uint32_t v = x ^ 0x55du;
	v += 0x514u;
	v -= 0x3bau;
	v += 0x7cu;
	v -= 0x31cu;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f101(uint32_t x)
{
	uint32_t v = x ^ 0x9941c458u;
	g_acc += v;
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f102(uint32_t x)
{
	uint32_t v = x ^ 0x467u;
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f103(uint32_t x)
{
	uint32_t v = x ^ 0x665u;
	v ^= 0x26fc77e7u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f104(uint32_t x)
{
	uint32_t v = x ^ 0x7a3u;
	v -= 0x70u;
	v -= 0x6c0u;
	v -= 0x532u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f105(uint32_t x)
{
	uint32_t v = x ^ 0x120u;
	v ^= 0xbe8e5f63u;
	g_acc += v;
	v ^= 0xa62643e2u;
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f106(uint32_t x)
{
	uint32_t v = x ^ 0x412u;
	v = (v << 6) | (v >> 26);
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f107(uint32_t x)
{
	uint32_t v = x ^ 0x5b3u;
	g_acc += v;
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f108(uint32_t x)
{
	uint32_t v = x ^ 0x466u;
	v ^= 0xc3e84d20u;
	v += 0x53cu;
	v -= 0x108u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f109(uint32_t x)
{
	uint32_t v = x ^ 0x2a3u;
	v += 0x597u;
	g_acc += v;
	v += 0x1a2u;
	v = (v << 2) | (v >> 30);
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f110(uint32_t x)
{
	uint32_t v = x ^ 0xb346467eu;
	v ^= 0xdd18e3e6u;
	v ^= 0x72052a5fu;
	v = (v << 3) | (v >> 29);
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f111(uint32_t x)
{
	uint32_t v = x ^ 0x63bu;
	v ^= 0x436d5099u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f112(uint32_t x)
{
	uint32_t v = x ^ 0xc2eb3d57u;
	v ^= 0x44000aa9u;
	v += 0x63fu;
	v = (v << 13) | (v >> 19);
	v ^= 0x91f25c23u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f113(uint32_t x)
{
	uint32_t v = x ^ 0x45109387u;
	v += 0x78fu;
	v -= 0x53eu;
	g_acc += v;
	v ^= 0xfa190e61u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f114(uint32_t x)
{
	uint32_t v = x ^ 0x6f8u;
	v = (v << 24) | (v >> 8);
	v = (v << 27) | (v >> 5);
	v ^= 0x4a9b7d08u;
	v -= 0x5e5u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f115(uint32_t x)
{
	uint32_t v = x ^ 0x71b850bdu;
	v ^= 0x66f91e68u;
	v ^= 0x6b508140u;
	v += 0x434u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f116(uint32_t x)
{
	uint32_t v = x ^ 0xc6ad2cfcu;
	v ^= 0x41d2a489u;
	v -= 0x181u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f117(uint32_t x)
{
	uint32_t v = x ^ 0x289u;
	g_acc += v;
	v += 0x7f0u;
	v ^= 0x25f693a5u;
	v ^= 0x85a99aafu;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f118(uint32_t x)
{
	uint32_t v = x ^ 0x258u;
	v -= 0x767u;
	g_acc += v;
	v += 0x6a9u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f119(uint32_t x)
{
	uint32_t v = x ^ 0x6abu;
	v -= 0x63u;
	v ^= 0x548c625cu;
	v = (v << 31) | (v >> 1);
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f120(uint32_t x)
{
	uint32_t v = x ^ 0x33f6e3aau;
	v -= 0x1a7u;
	v = (v << 22) | (v >> 10);
	v -= 0x730u;
	v ^= 0xa6f603c2u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f121(uint32_t x)
{
	uint32_t v = x ^ 0x39du;
	v += 0x2d0u;
	v -= 0x714u;
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f122(uint32_t x)
{
	uint32_t v = x ^ 0xc68259c9u;
	v ^= 0x49794580u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f123(uint32_t x)
{
	uint32_t v = x ^ 0xd8ba0929u;
	v += 0x7dbu;
	v -= 0x567u;
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f124(uint32_t x)
{
	uint32_t v = x ^ 0x6b271545u;
	v ^= 0x6c79afccu;
	v ^= 0xdfebdce4u;
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f125(uint32_t x)
{
	uint32_t v = x ^ 0x6f3u;
	g_acc += v;
	v = (v << 13) | (v >> 19);
	v ^= 0x5ef4d747u;
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f126(uint32_t x)
{
	uint32_t v = x ^ 0xb65c5b5eu;
	g_acc += v;
	v -= 0x3d4u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f127(uint32_t x)
{
	uint32_t v = x ^ 0xb6f13276u;
	v = (v << 12) | (v >> 20);
	v += 0x3c1u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f128(uint32_t x)
{
	uint32_t v = x ^ 0x353u;
	v = (v << 21) | (v >> 11);
	v = (v << 1) | (v >> 31);
	v ^= 0xee5f4568u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f129(uint32_t x)
{
	uint32_t v = x ^ 0x42bu;
	v = (v << 3) | (v >> 29);
	v -= 0x642u;
	v ^= 0xff27f744u;
	v += 0x6c0u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f130(uint32_t x)
{
	uint32_t v = x ^ 0x639u;
	v ^= 0x5d57dfeeu;
	v += 0x7cfu;
	v = (v << 4) | (v >> 28);
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f131(uint32_t x)
{
	uint32_t v = x ^ 0x1b7accb8u;
	v += 0x6bdu;
	g_acc += v;
	v = (v << 3) | (v >> 29);
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f132(uint32_t x)
{
	uint32_t v = x ^ 0x19612300u;
	v += 0x69au;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f133(uint32_t x)
{
	uint32_t v = x ^ 0x1aeu;
	v ^= 0xb0a16facu;
	v -= 0x721u;
	g_acc += v;
	v = (v << 11) | (v >> 21);
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f134(uint32_t x)
{
	uint32_t v = x ^ 0x229u;
	v -= 0xa5u;
	v += 0x9du;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f135(uint32_t x)
{
	uint32_t v = x ^ 0x6b2u;
	v ^= 0xd6c02bb7u;
	g_acc += v;
	g_acc += v;
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f136(uint32_t x)
{
	uint32_t v = x ^ 0x5b3u;
	v += 0x5fcu;
	g_acc += v;
	v += 0x3e6u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f137(uint32_t x)
{
	uint32_t v = x ^ 0x3b6726c7u;
	v += 0x719u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f138(uint32_t x)
{
	uint32_t v = x ^ 0x2c1ffdd1u;
	g_acc += v;
	g_acc += v;
	v ^= 0x3b152912u;
	v ^= 0xa2ec7372u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f139(uint32_t x)
{
	uint32_t v = x ^ 0x5au;
	v ^= 0xd1694585u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f140(uint32_t x)
{
	uint32_t v = x ^ 0x4dbu;
	v += 0x634u;
	v -= 0x586u;
	v = (v << 28) | (v >> 4);
	v += 0x10u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f141(uint32_t x)
{
	uint32_t v = x ^ 0x36u;
	v ^= 0x59097470u;
	v ^= 0x5acaced9u;
	v -= 0x15u;
	v += 0x421u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f142(uint32_t x)
{
	uint32_t v = x ^ 0x5bbu;
	v += 0x40fu;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f143(uint32_t x)
{
	uint32_t v = x ^ 0x30bu;
	g_acc += v;
	v -= 0x52cu;
	v -= 0x160u;
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f144(uint32_t x)
{
	uint32_t v = x ^ 0x2d11aa75u;
	g_acc += v;
	v += 0x5d6u;
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f145(uint32_t x)
{
	uint32_t v = x ^ 0xb0900c55u;
	v = (v << 15) | (v >> 17);
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f146(uint32_t x)
{
	uint32_t v = x ^ 0x592u;
	v = (v << 4) | (v >> 28);
	v -= 0x2c6u;
	v ^= 0x1523f010u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f147(uint32_t x)
{
	uint32_t v = x ^ 0x1485cfd4u;
	v = (v << 2) | (v >> 30);
	v -= 0x3cdu;
	v += 0x75fu;
	v = (v << 27) | (v >> 5);
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f148(uint32_t x)
{
	uint32_t v = x ^ 0x455u;
	g_acc += v;
	v = (v << 24) | (v >> 8);
	v = (v << 26) | (v >> 6);
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f149(uint32_t x)
{
	uint32_t v = x ^ 0xb4aeef01u;
	v ^= 0xc65bf4fcu;
	g_acc += v;
	v += 0x7acu;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f150(uint32_t x)
{
	uint32_t v = x ^ 0x147u;
	v = (v << 17) | (v >> 15);
	v = (v << 16) | (v >> 16);
	v ^= 0xd6d67162u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f151(uint32_t x)
{
	uint32_t v = x ^ 0x2c7u;
	v = (v << 15) | (v >> 17);
	v = (v << 21) | (v >> 11);
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f152(uint32_t x)
{
	uint32_t v = x ^ 0x432u;
	v = (v << 6) | (v >> 26);
	v += 0x4a7u;
	v += 0x43u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f153(uint32_t x)
{
	uint32_t v = x ^ 0x498u;
	v -= 0x4cu;
	v = (v << 1) | (v >> 31);
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f154(uint32_t x)
{
	uint32_t v = x ^ 0x628dcc77u;
	v -= 0x100u;
	v -= 0x65fu;
	v -= 0x78u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f155(uint32_t x)
{
	uint32_t v = x ^ 0x5a3u;
	v = (v << 21) | (v >> 11);
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f156(uint32_t x)
{
	uint32_t v = x ^ 0x1c1u;
	v -= 0x30bu;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f157(uint32_t x)
{
	uint32_t v = x ^ 0xb48ad0bbu;
	v ^= 0x76d3e729u;
	v += 0x7du;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f158(uint32_t x)
{
	uint32_t v = x ^ 0xd1aed6ceu;
	v -= 0xd3u;
	v += 0x30au;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f159(uint32_t x)
{
	uint32_t v = x ^ 0x5e7u;
	g_acc += v;
	v += 0xc9u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f160(uint32_t x)
{
	uint32_t v = x ^ 0x660151cdu;
	g_acc += v;
	v += 0x309u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f161(uint32_t x)
{
	uint32_t v = x ^ 0x9d980250u;
	v ^= 0x138a4830u;
	v ^= 0x5cb6532du;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f162(uint32_t x)
{
	uint32_t v = x ^ 0x8d37eedau;
	v += 0x36u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f163(uint32_t x)
{
	uint32_t v = x ^ 0x87abc674u;
	v = (v << 7) | (v >> 25);
	g_acc += v;
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f164(uint32_t x)
{
	uint32_t v = x ^ 0x1a7u;
	v += 0x1f0u;
	v += 0x346u;
	v = (v << 14) | (v >> 18);
	v ^= 0xd665695fu;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f165(uint32_t x)
{
	uint32_t v = x ^ 0xeb03216bu;
	v += 0x5a9u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f166(uint32_t x)
{
	uint32_t v = x ^ 0x022be55bu;
	v += 0xdfu;
	v = (v << 16) | (v >> 16);
	g_acc += v;
	v = (v << 6) | (v >> 26);
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f167(uint32_t x)
{
	uint32_t v = x ^ 0xaf1c75e8u;
	v = (v << 21) | (v >> 11);
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f168(uint32_t x)
{
	uint32_t v = x ^ 0x3cbu;
	g_acc += v;
	v ^= 0x36626946u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f169(uint32_t x)
{
	uint32_t v = x ^ 0x438u;
	v += 0x25bu;
	v ^= 0x72bd9618u;
	v ^= 0xf6ee715bu;
	v = (v << 12) | (v >> 20);
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f170(uint32_t x)
{
	uint32_t v = x ^ 0x3c12ab24u;
	v = (v << 31) | (v >> 1);
	v -= 0x602u;
	v -= 0x56au;
	v -= 0x654u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f171(uint32_t x)
{
	uint32_t v = x ^ 0x3a6u;
	v = (v << 23) | (v >> 9);
	v ^= 0x9c8c8698u;
	v = (v << 3) | (v >> 29);
	v -= 0x786u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f172(uint32_t x)
{
	uint32_t v = x ^ 0x23cu;
	g_acc += v;
	v -= 0x426u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f173(uint32_t x)
{
	uint32_t v = x ^ 0x361u;
	v -= 0x435u;
	v += 0x6f9u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f174(uint32_t x)
{
	uint32_t v = x ^ 0x536u;
	v ^= 0xb280a122u;
	g_acc += v;
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f175(uint32_t x)
{
	uint32_t v = x ^ 0xdc5867a4u;
	v = (v << 1) | (v >> 31);
	v ^= 0xdb5b1ffcu;
	v -= 0x6ebu;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f176(uint32_t x)
{
	uint32_t v = x ^ 0x44u;
	v ^= 0x7cfe1ac6u;
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f177(uint32_t x)
{
	uint32_t v = x ^ 0x769u;
	v -= 0x4dau;
	v += 0x6adu;
	g_acc += v;
	v ^= 0x369dc00eu;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f178(uint32_t x)
{
	uint32_t v = x ^ 0xd765acfeu;
	v = (v << 22) | (v >> 10);
	v -= 0x6cbu;
	v = (v << 18) | (v >> 14);
	v = (v << 19) | (v >> 13);
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f179(uint32_t x)
{
	uint32_t v = x ^ 0x2d1u;
	v -= 0x149u;
	v = (v << 22) | (v >> 10);
	v ^= 0x26fba848u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f180(uint32_t x)
{
	uint32_t v = x ^ 0x61cu;
	v += 0x31eu;
	v = (v << 23) | (v >> 9);
	v -= 0xbbu;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f181(uint32_t x)
{
	uint32_t v = x ^ 0x2b0u;
	v = (v << 30) | (v >> 2);
	v += 0xebu;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f182(uint32_t x)
{
	uint32_t v = x ^ 0x531fd2fcu;
	v = (v << 28) | (v >> 4);
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f183(uint32_t x)
{
	uint32_t v = x ^ 0xa5edf321u;
	v += 0x453u;
	v -= 0x432u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f184(uint32_t x)
{
	uint32_t v = x ^ 0x225u;
	v += 0x4fau;
	v ^= 0x1c5967afu;
	g_acc += v;
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f185(uint32_t x)
{
	uint32_t v = x ^ 0x3ddu;
	v += 0x1beu;
	v += 0x4ddu;
	g_acc += v;
	v = (v << 19) | (v >> 13);
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f186(uint32_t x)
{
	uint32_t v = x ^ 0x806a1f7au;
	v -= 0x22u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f187(uint32_t x)
{
	uint32_t v = x ^ 0x74eu;
	v += 0x39du;
	v += 0x151u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f188(uint32_t x)
{
	uint32_t v = x ^ 0x28717109u;
	v = (v << 11) | (v >> 21);
	v += 0x480u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f189(uint32_t x)
{
	uint32_t v = x ^ 0x74bu;
	g_acc += v;
	v += 0xb5u;
	v = (v << 15) | (v >> 17);
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f190(uint32_t x)
{
	uint32_t v = x ^ 0x4e5u;
	g_acc += v;
	v = (v << 12) | (v >> 20);
	v = (v << 2) | (v >> 30);
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f191(uint32_t x)
{
	uint32_t v = x ^ 0x99e0c45au;
	v += 0x661u;
	v ^= 0x4c05584eu;
	v = (v << 8) | (v >> 24);
	v += 0x7c4u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f192(uint32_t x)
{
	uint32_t v = x ^ 0x11au;
	v = (v << 3) | (v >> 29);
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f193(uint32_t x)
{
	uint32_t v = x ^ 0x633f0ef5u;
	v ^= 0x71c3ed45u;
	v += 0x1beu;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f194(uint32_t x)
{
	uint32_t v = x ^ 0xe743bbe6u;
	v ^= 0x0cfd5595u;
	v = (v << 1) | (v >> 31);
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f195(uint32_t x)
{
	uint32_t v = x ^ 0x17du;
	v = (v << 14) | (v >> 18);
	v = (v << 5) | (v >> 27);
	v = (v << 27) | (v >> 5);
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f196(uint32_t x)
{
	uint32_t v = x ^ 0xce2a8b3cu;
	v ^= 0x83664462u;
	v ^= 0x6cd1abf7u;
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f197(uint32_t x)
{
	uint32_t v = x ^ 0x5f1u;
	v -= 0x381u;
	v += 0x737u;
	v = (v << 17) | (v >> 15);
	v = (v << 19) | (v >> 13);
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f198(uint32_t x)
{
	uint32_t v = x ^ 0x735u;
	v ^= 0xc483ce0fu;
	v -= 0x4d1u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f199(uint32_t x)
{
	uint32_t v = x ^ 0x148u;
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f200(uint32_t x)
{
	uint32_t v = x ^ 0x626u;
	v += 0x37cu;
	v -= 0x6a4u;
	v = (v << 8) | (v >> 24);
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f201(uint32_t x)
{
	uint32_t v = x ^ 0xa66a2c39u;
	v += 0x7d4u;
	v ^= 0x9f0fdb0au;
	v -= 0x666u;
	v += 0x1a4u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f202(uint32_t x)
{
	uint32_t v = x ^ 0xfffe24aau;
	g_acc += v;
	g_acc += v;
	v = (v << 3) | (v >> 29);
	v ^= 0x0bb05e2bu;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f203(uint32_t x)
{
	uint32_t v = x ^ 0x338u;
	v += 0x540u;
	v ^= 0x92665b63u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f204(uint32_t x)
{
	uint32_t v = x ^ 0xc0af2fb0u;
	v += 0x4e7u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f205(uint32_t x)
{
	uint32_t v = x ^ 0xdd84304cu;
	v = (v << 9) | (v >> 23);
	v = (v << 6) | (v >> 26);
	v ^= 0x62125831u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f206(uint32_t x)
{
	uint32_t v = x ^ 0x5e4u;
	v ^= 0x6e972daeu;
	v ^= 0x4b0411b9u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f207(uint32_t x)
{
	uint32_t v = x ^ 0xfeceaa5eu;
	v += 0x14fu;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f208(uint32_t x)
{
	uint32_t v = x ^ 0x86e9a1fbu;
	v ^= 0xee89dd7fu;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f209(uint32_t x)
{
	uint32_t v = x ^ 0x708a5fbcu;
	v -= 0x66du;
	v ^= 0x914d899eu;
	v ^= 0xc2a49ce3u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f210(uint32_t x)
{
	uint32_t v = x ^ 0x2d6u;
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f211(uint32_t x)
{
	uint32_t v = x ^ 0xd3566cb2u;
	v += 0x139u;
	v = (v << 12) | (v >> 20);
	v += 0x587u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f212(uint32_t x)
{
	uint32_t v = x ^ 0x269u;
	g_acc += v;
	v = (v << 28) | (v >> 4);
	v -= 0x3b9u;
	v ^= 0xfe771dc5u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f213(uint32_t x)
{
	uint32_t v = x ^ 0x446ed908u;
	v ^= 0x06ea7b4bu;
	v = (v << 20) | (v >> 12);
	g_acc += v;
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f214(uint32_t x)
{
	uint32_t v = x ^ 0x9882417bu;
	v -= 0x467u;
	v -= 0x69bu;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f215(uint32_t x)
{
	uint32_t v = x ^ 0xd468f0b8u;
	v = (v << 27) | (v >> 5);
	v -= 0x139u;
	g_acc += v;
	v += 0x338u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f216(uint32_t x)
{
	uint32_t v = x ^ 0x8afa75c4u;
	v ^= 0x43258e66u;
	v = (v << 19) | (v >> 13);
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f217(uint32_t x)
{
	uint32_t v = x ^ 0x5d3u;
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f218(uint32_t x)
{
	uint32_t v = x ^ 0x6abf735fu;
	v += 0x603u;
	v += 0x5b3u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f219(uint32_t x)
{
	uint32_t v = x ^ 0xba109b71u;
	v ^= 0x25ff2ad9u;
	v = (v << 28) | (v >> 4);
	v = (v << 20) | (v >> 12);
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f220(uint32_t x)
{
	uint32_t v = x ^ 0x2e4f0549u;
	v = (v << 15) | (v >> 17);
	v ^= 0xfa504a29u;
	v ^= 0xd4a815e4u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f221(uint32_t x)
{
	uint32_t v = x ^ 0x6d35b079u;
	v ^= 0xaa041e4cu;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f222(uint32_t x)
{
	uint32_t v = x ^ 0xfbba9f6au;
	v = (v << 9) | (v >> 23);
	v = (v << 25) | (v >> 7);
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f223(uint32_t x)
{
	uint32_t v = x ^ 0xfc49fdc8u;
	v = (v << 5) | (v >> 27);
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f224(uint32_t x)
{
	uint32_t v = x ^ 0x28bu;
	v ^= 0x5aa995c9u;
	v ^= 0xdaa8489fu;
	v -= 0x29au;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f225(uint32_t x)
{
	uint32_t v = x ^ 0x3a9u;
	v ^= 0xca33fe01u;
	v = (v << 2) | (v >> 30);
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f226(uint32_t x)
{
	uint32_t v = x ^ 0xa8551539u;
	v += 0x5ebu;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f227(uint32_t x)
{
	uint32_t v = x ^ 0x48au;
	v = (v << 24) | (v >> 8);
	v = (v << 8) | (v >> 24);
	v -= 0x39du;
	v ^= 0xfb5ebd17u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f228(uint32_t x)
{
	uint32_t v = x ^ 0x2b1u;
	v += 0x4f0u;
	g_acc += v;
	v -= 0x6a6u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f229(uint32_t x)
{
	uint32_t v = x ^ 0x84b08bbcu;
	v ^= 0x7f05391fu;
	v += 0x58u;
	v ^= 0x63d61c37u;
	v ^= 0xf8e3cc62u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f230(uint32_t x)
{
	uint32_t v = x ^ 0x13du;
	v ^= 0x6c7986edu;
	g_acc += v;
	v = (v << 1) | (v >> 31);
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f231(uint32_t x)
{
	uint32_t v = x ^ 0xeb9f4b64u;
	g_acc += v;
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f232(uint32_t x)
{
	uint32_t v = x ^ 0x673u;
	v -= 0x7b9u;
	v -= 0x392u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f233(uint32_t x)
{
	uint32_t v = x ^ 0x47eu;
	v ^= 0xafd5dca1u;
	v = (v << 31) | (v >> 1);
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f234(uint32_t x)
{
	uint32_t v = x ^ 0x67b7d1ccu;
	g_acc += v;
	v -= 0x59au;
	v -= 0x4e1u;
	v ^= 0x7f39d065u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f235(uint32_t x)
{
	uint32_t v = x ^ 0x166u;
	g_acc += v;
	v = (v << 3) | (v >> 29);
	g_acc += v;
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f236(uint32_t x)
{
	uint32_t v = x ^ 0x15au;
	v ^= 0xdbd77341u;
	v = (v << 11) | (v >> 21);
	v -= 0x138u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f237(uint32_t x)
{
	uint32_t v = x ^ 0xfea1c570u;
	v -= 0x2c8u;
	v = (v << 22) | (v >> 10);
	v += 0x109u;
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f238(uint32_t x)
{
	uint32_t v = x ^ 0x49u;
	v = (v << 6) | (v >> 26);
	v ^= 0x4c93779du;
	v = (v << 20) | (v >> 12);
	v += 0x20u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f239(uint32_t x)
{
	uint32_t v = x ^ 0x5cu;
	v = (v << 6) | (v >> 26);
	v -= 0x469u;
	v ^= 0x2f2f19d7u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f240(uint32_t x)
{
	uint32_t v = x ^ 0x68bu;
	v += 0x5a7u;
	v += 0x669u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f241(uint32_t x)
{
	uint32_t v = x ^ 0x53au;
	v = (v << 11) | (v >> 21);
	v += 0x325u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f242(uint32_t x)
{
	uint32_t v = x ^ 0x1au;
	g_acc += v;
	v += 0x573u;
	v ^= 0x9c14a50cu;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f243(uint32_t x)
{
	uint32_t v = x ^ 0xd31950c7u;
	g_acc += v;
	v ^= 0x6ee08b1fu;
	g_acc += v;
	v ^= 0xd85fb42cu;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f244(uint32_t x)
{
	uint32_t v = x ^ 0x3fu;
	v -= 0x77cu;
	v = (v << 11) | (v >> 21);
	v -= 0x47au;
	v += 0x740u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f245(uint32_t x)
{
	uint32_t v = x ^ 0x58u;
	v += 0x3cbu;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f246(uint32_t x)
{
	uint32_t v = x ^ 0x28eu;
	v += 0x38au;
	v += 0x691u;
	v -= 0x1afu;
	v ^= 0x821f5d04u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f247(uint32_t x)
{
	uint32_t v = x ^ 0x521u;
	v ^= 0xe0c93c74u;
	v = (v << 25) | (v >> 7);
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f248(uint32_t x)
{
	uint32_t v = x ^ 0x36cu;
	v ^= 0x48ede145u;
	v += 0x284u;
	v ^= 0x9a8efca0u;
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f249(uint32_t x)
{
	uint32_t v = x ^ 0x59u;
	g_acc += v;
	v -= 0x2ccu;
	v ^= 0x7874a2dcu;
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f250(uint32_t x)
{
	uint32_t v = x ^ 0x6f3u;
	v ^= 0x1f5d9d31u;
	v -= 0x7c7u;
	v += 0x271u;
	v ^= 0xb7822dfdu;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f251(uint32_t x)
{
	uint32_t v = x ^ 0xb7u;
	v -= 0x1a7u;
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f252(uint32_t x)
{
	uint32_t v = x ^ 0x448u;
	v += 0x310u;
	v = (v << 8) | (v >> 24);
	g_acc += v;
	v ^= 0xb906206bu;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f253(uint32_t x)
{
	uint32_t v = x ^ 0x4829a2eeu;
	v = (v << 9) | (v >> 23);
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f254(uint32_t x)
{
	uint32_t v = x ^ 0x600u;
	v ^= 0x3af3bf63u;
	v ^= 0x3bcad41au;
	v -= 0x38au;
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f255(uint32_t x)
{
	uint32_t v = x ^ 0x4afu;
	v = (v << 4) | (v >> 28);
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f256(uint32_t x)
{
	uint32_t v = x ^ 0x9a10fe39u;
	g_acc += v;
	v = (v << 16) | (v >> 16);
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f257(uint32_t x)
{
	uint32_t v = x ^ 0x484u;
	v ^= 0x57496ed4u;
	v -= 0x708u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f258(uint32_t x)
{
	uint32_t v = x ^ 0x375u;
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f259(uint32_t x)
{
	uint32_t v = x ^ 0x541u;
	v += 0xb3u;
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f260(uint32_t x)
{
	uint32_t v = x ^ 0x93006a94u;
	v -= 0x10bu;
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f261(uint32_t x)
{
	uint32_t v = x ^ 0x54a7e813u;
	v = (v << 9) | (v >> 23);
	v = (v << 30) | (v >> 2);
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f262(uint32_t x)
{
	uint32_t v = x ^ 0x5bcu;
	v += 0x4fbu;
	v -= 0x345u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f263(uint32_t x)
{
	uint32_t v = x ^ 0x622u;
	v -= 0x559u;
	v += 0x778u;
	v ^= 0x353bb2b7u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f264(uint32_t x)
{
	uint32_t v = x ^ 0x74bu;
	v -= 0x3b7u;
	v += 0x33u;
	v = (v << 8) | (v >> 24);
	v = (v << 31) | (v >> 1);
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f265(uint32_t x)
{
	uint32_t v = x ^ 0x67dd487du;
	v ^= 0x02566021u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f266(uint32_t x)
{
	uint32_t v = x ^ 0x4622a403u;
	g_acc += v;
	v = (v << 22) | (v >> 10);
	v -= 0x6bcu;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f267(uint32_t x)
{
	uint32_t v = x ^ 0x3d8u;
	v -= 0x2a0u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f268(uint32_t x)
{
	uint32_t v = x ^ 0x15cf9768u;
	v -= 0x40cu;
	v += 0x51fu;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f269(uint32_t x)
{
	uint32_t v = x ^ 0x25cu;
	v = (v << 28) | (v >> 4);
	v ^= 0xe6cdbef2u;
	v = (v << 19) | (v >> 13);
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f270(uint32_t x)
{
	uint32_t v = x ^ 0x28b84e94u;
	v -= 0x7e2u;
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f271(uint32_t x)
{
	uint32_t v = x ^ 0xf2u;
	v ^= 0x38629332u;
	v -= 0x7b0u;
	v ^= 0x7f145c24u;
	v = (v << 22) | (v >> 10);
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f272(uint32_t x)
{
	uint32_t v = x ^ 0x23fff240u;
	v += 0x492u;
	g_acc += v;
	v += 0x6du;
	v ^= 0x75a997c7u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f273(uint32_t x)
{
	uint32_t v = x ^ 0x68u;
	v = (v << 26) | (v >> 6);
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f274(uint32_t x)
{
	uint32_t v = x ^ 0x3653803bu;
	v += 0x513u;
	v -= 0xb5u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f275(uint32_t x)
{
	uint32_t v = x ^ 0xdee9bcffu;
	v = (v << 11) | (v >> 21);
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f276(uint32_t x)
{
	uint32_t v = x ^ 0x265u;
	v ^= 0x2985cb62u;
	v += 0x4e9u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f277(uint32_t x)
{
	uint32_t v = x ^ 0xbu;
	v += 0x7f3u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f278(uint32_t x)
{
	uint32_t v = x ^ 0x695u;
	v ^= 0x20613d46u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f279(uint32_t x)
{
	uint32_t v = x ^ 0x4ee491d7u;
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f280(uint32_t x)
{
	uint32_t v = x ^ 0x63daac79u;
	v -= 0xafu;
	v -= 0x604u;
	v ^= 0x9f662bf7u;
	v ^= 0x58d5c680u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f281(uint32_t x)
{
	uint32_t v = x ^ 0x01077e17u;
	v ^= 0x2355b133u;
	v += 0x6adu;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f282(uint32_t x)
{
	uint32_t v = x ^ 0x6e0u;
	v += 0x2e0u;
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f283(uint32_t x)
{
	uint32_t v = x ^ 0x6fd2992du;
	v -= 0x71fu;
	v -= 0x795u;
	v ^= 0xdb2ed714u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f284(uint32_t x)
{
	uint32_t v = x ^ 0x43637e4au;
	v ^= 0xd834b5a4u;
	v ^= 0x3e9a1da3u;
	g_acc += v;
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f285(uint32_t x)
{
	uint32_t v = x ^ 0x3b7u;
	v += 0x5d1u;
	v = (v << 9) | (v >> 23);
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f286(uint32_t x)
{
	uint32_t v = x ^ 0xdc23ae14u;
	v = (v << 13) | (v >> 19);
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f287(uint32_t x)
{
	uint32_t v = x ^ 0xe90f161au;
	v ^= 0x62ee26eau;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f288(uint32_t x)
{
	uint32_t v = x ^ 0x1d5u;
	v += 0x567u;
	v ^= 0x497c1e69u;
	g_acc += v;
	v -= 0x50au;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f289(uint32_t x)
{
	uint32_t v = x ^ 0x28531d62u;
	g_acc += v;
	v += 0x7afu;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f290(uint32_t x)
{
	uint32_t v = x ^ 0x293u;
	v ^= 0x351656feu;
	v = (v << 21) | (v >> 11);
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f291(uint32_t x)
{
	uint32_t v = x ^ 0x50776e71u;
	v ^= 0xda7b3d25u;
	v -= 0x469u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f292(uint32_t x)
{
	uint32_t v = x ^ 0x327u;
	v ^= 0x42a66ea2u;
	v = (v << 7) | (v >> 25);
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f293(uint32_t x)
{
	uint32_t v = x ^ 0x23cu;
	g_acc += v;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f294(uint32_t x)
{
	uint32_t v = x ^ 0x561u;
	v ^= 0x74b07bb9u;
	v += 0x281u;
	g_acc += v;
	v -= 0xd2u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f295(uint32_t x)
{
	uint32_t v = x ^ 0x7b7u;
	v ^= 0xc7a7d147u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f296(uint32_t x)
{
	uint32_t v = x ^ 0x24cc3dedu;
	v ^= 0x500a9422u;
	v += 0x225u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f297(uint32_t x)
{
	uint32_t v = x ^ 0x26eu;
	v -= 0x7b8u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f298(uint32_t x)
{
	uint32_t v = x ^ 0x095d6f50u;
	g_acc += v;
	v = (v << 13) | (v >> 19);
	v += 0x325u;
	v ^= 0x6eabdcc8u;
	g_acc ^= v;
	return v;
}

uint32_t __attribute__((noinline)) f299(uint32_t x)
{
	uint32_t v = x ^ 0x450u;
	g_acc += v;
	g_acc += v;
	v = (v << 21) | (v >> 11);
	g_acc += v;
	g_acc ^= v;
	return v;
}

static void __attribute__((noinline)) run_phase_00(void)
{
	(void)f228(0x1eu);
	(void)f062(0x1ecu);
	(void)f114(0x744u);
	(void)f224(0x37bu);
	(void)f293(0x383u);
	(void)f278(0x420u);
	(void)f283(0x5b8u);
	(void)f047(0x183u);
	(void)f198(0x799u);
	(void)f199(0x7deu);
	(void)f296(0x444u);
	(void)f153(0x6c8u);
}

static void __attribute__((noinline)) run_phase_01(void)
{
	(void)f224(0x67au);
	(void)f015(0x701u);
	(void)f251(0x227u);
	(void)f023(0x218u);
	(void)f058(0x345u);
	(void)f253(0x5b8u);
	(void)f085(0x76au);
	(void)f105(0xbbu);
	(void)f238(0x20u);
	(void)f276(0xfdu);
	(void)f139(0x211u);
	(void)f167(0x2ecu);
}

static void __attribute__((noinline)) run_phase_02(void)
{
	(void)f006(0x667u);
	(void)f162(0x7e7u);
	(void)f105(0x3f0u);
	(void)f041(0xf6u);
	(void)f136(0x12au);
	(void)f255(0x224u);
	(void)f095(0x3d0u);
	(void)f292(0x5f3u);
	(void)f231(0xf3u);
	(void)f043(0x6bu);
	(void)f265(0x73u);
	(void)f073(0x64au);
}

static void __attribute__((noinline)) run_phase_03(void)
{
	(void)f268(0x697u);
	(void)f021(0x2d9u);
	(void)f003(0x16du);
	(void)f133(0x487u);
	(void)f095(0x714u);
	(void)f166(0x5ffu);
	(void)f277(0x3e1u);
	(void)f288(0x299u);
	(void)f243(0x674u);
	(void)f228(0x2bfu);
	(void)f293(0xb7u);
}

static void __attribute__((noinline)) run_phase_04(void)
{
	(void)f272(0x540u);
	(void)f137(0x28cu);
	(void)f216(0x2beu);
	(void)f030(0x68du);
	(void)f196(0xdeu);
	(void)f135(0x215u);
	(void)f032(0x7e6u);
	(void)f245(0x592u);
	(void)f048(0x668u);
	(void)f000(0x7au);
	(void)f149(0x4f0u);
	(void)f028(0x407u);
}

static void __attribute__((noinline)) run_phase_05(void)
{
	(void)f025(0x3a4u);
	(void)f101(0x582u);
	(void)f076(0x2a6u);
	(void)f233(0x62au);
	(void)f028(0x642u);
	(void)f186(0x88u);
	(void)f119(0x6f3u);
	(void)f115(0x31bu);
	(void)f250(0x781u);
	(void)f220(0x10cu);
	(void)f081(0x14bu);
	(void)f157(0x2ebu);
	(void)f150(0x6bu);
}

static void __attribute__((noinline)) run_phase_06(void)
{
	(void)f110(0x290u);
	(void)f129(0x68du);
	(void)f299(0x1d1u);
	(void)f277(0x501u);
	(void)f196(0x409u);
	(void)f180(0x4ddu);
	(void)f201(0x74du);
	(void)f017(0x5bdu);
	(void)f230(0x1a8u);
	(void)f097(0x2du);
	(void)f275(0x66eu);
	(void)f213(0x413u);
	(void)f030(0x7f8u);
}

static void __attribute__((noinline)) run_phase_07(void)
{
	(void)f077(0x3a9u);
	(void)f116(0x6b3u);
	(void)f236(0x322u);
	(void)f299(0xaau);
	(void)f107(0x1bu);
	(void)f159(0x36u);
	(void)f171(0x8bu);
	(void)f298(0x4aau);
	(void)f283(0x3dfu);
	(void)f103(0x1dcu);
	(void)f065(0x209u);
	(void)f141(0x1fu);
	(void)f068(0x3c3u);
	(void)f174(0xdcu);
}

static void __attribute__((noinline)) run_phase_08(void)
{
	(void)f168(0x22cu);
	(void)f125(0xf4u);
	(void)f119(0x5fau);
	(void)f016(0x420u);
	(void)f291(0x4a2u);
	(void)f097(0x7b2u);
	(void)f186(0xc2u);
	(void)f059(0xf0u);
	(void)f080(0x646u);
	(void)f241(0x2a5u);
	(void)f210(0x289u);
	(void)f008(0x7c7u);
	(void)f080(0x565u);
}

static void __attribute__((noinline)) run_phase_09(void)
{
	(void)f172(0xe8u);
	(void)f190(0x2f1u);
	(void)f131(0x233u);
	(void)f180(0x183u);
	(void)f021(0x4e9u);
	(void)f080(0x724u);
	(void)f297(0x7au);
	(void)f009(0x25bu);
	(void)f249(0x46fu);
	(void)f165(0x83u);
}

static void __attribute__((noinline)) run_phase_10(void)
{
	(void)f221(0x1bdu);
	(void)f080(0x1e8u);
	(void)f210(0x508u);
	(void)f227(0x3b8u);
	(void)f251(0x16au);
	(void)f214(0x4fu);
	(void)f148(0x4d3u);
	(void)f076(0x21bu);
	(void)f214(0x35eu);
	(void)f242(0x50au);
}

static void __attribute__((noinline)) run_phase_11(void)
{
	(void)f159(0xd4u);
	(void)f063(0x661u);
	(void)f116(0x6cfu);
	(void)f031(0x2cu);
	(void)f117(0x6c3u);
	(void)f204(0x62fu);
	(void)f015(0x30au);
	(void)f045(0x226u);
	(void)f295(0x3b2u);
	(void)f198(0x323u);
	(void)f092(0x716u);
	(void)f055(0x4b4u);
	(void)f285(0x3ceu);
	(void)f275(0x3a5u);
}

static void __attribute__((noinline)) run_phase_12(void)
{
	(void)f117(0x420u);
	(void)f228(0x3d8u);
	(void)f268(0xd6u);
	(void)f058(0x77du);
	(void)f090(0x264u);
	(void)f091(0x7ecu);
	(void)f156(0x66fu);
	(void)f130(0x3d6u);
	(void)f038(0x19du);
	(void)f118(0x6ffu);
	(void)f270(0x1f1u);
	(void)f253(0x600u);
	(void)f024(0x224u);
}

static void __attribute__((noinline)) run_phase_13(void)
{
	(void)f159(0x39du);
	(void)f108(0x467u);
	(void)f007(0x470u);
	(void)f077(0x62bu);
	(void)f221(0x35eu);
	(void)f269(0x49u);
	(void)f206(0x1f3u);
	(void)f068(0x355u);
	(void)f220(0x6f2u);
	(void)f121(0x4bdu);
	(void)f023(0x58fu);
	(void)f249(0x612u);
	(void)f215(0x131u);
}

static void __attribute__((noinline)) run_phase_14(void)
{
	(void)f024(0x23u);
	(void)f010(0x214u);
	(void)f069(0x122u);
	(void)f154(0x4a9u);
	(void)f051(0x37au);
	(void)f132(0x5b4u);
	(void)f087(0x3e4u);
	(void)f230(0x304u);
	(void)f218(0x758u);
	(void)f036(0x236u);
	(void)f221(0x151u);
	(void)f229(0x11fu);
	(void)f215(0x507u);
	(void)f195(0x19u);
}

static void __attribute__((noinline)) run_phase_15(void)
{
	(void)f158(0x11bu);
	(void)f273(0x59du);
	(void)f045(0x5bu);
	(void)f219(0x7b8u);
	(void)f239(0x42fu);
	(void)f262(0x493u);
	(void)f042(0x70cu);
	(void)f249(0x79cu);
	(void)f169(0x34du);
	(void)f207(0x85u);
	(void)f280(0x3c9u);
}

static void __attribute__((noinline)) run_phase_16(void)
{
	(void)f104(0x1f7u);
	(void)f058(0x236u);
	(void)f016(0x538u);
	(void)f226(0x319u);
	(void)f269(0x190u);
	(void)f266(0x1b0u);
	(void)f189(0x28cu);
	(void)f189(0x2e3u);
	(void)f114(0x6e6u);
	(void)f054(0x74du);
	(void)f288(0x9eu);
	(void)f083(0x4e4u);
	(void)f274(0x5efu);
}

static void __attribute__((noinline)) run_phase_17(void)
{
	(void)f114(0x65bu);
	(void)f146(0x1beu);
	(void)f255(0x643u);
	(void)f036(0x4ffu);
	(void)f262(0x32au);
	(void)f188(0x13cu);
	(void)f259(0x713u);
	(void)f279(0x192u);
	(void)f234(0x541u);
	(void)f121(0x6dau);
	(void)f183(0x1e3u);
}

static void __attribute__((noinline)) run_phase_18(void)
{
	(void)f072(0x5e7u);
	(void)f281(0xabu);
	(void)f205(0x77bu);
	(void)f149(0x3cfu);
	(void)f111(0x11du);
	(void)f175(0x2c7u);
	(void)f261(0x7fbu);
	(void)f070(0x312u);
	(void)f042(0x21du);
	(void)f225(0x6d1u);
	(void)f052(0x416u);
	(void)f162(0x5a0u);
	(void)f003(0x64eu);
	(void)f062(0x765u);
}

static void __attribute__((noinline)) run_phase_19(void)
{
	(void)f147(0x5e8u);
	(void)f173(0x339u);
	(void)f182(0x48eu);
	(void)f057(0x4a3u);
	(void)f206(0x2c2u);
	(void)f064(0x4a2u);
	(void)f111(0x7c4u);
	(void)f118(0x173u);
	(void)f212(0x47du);
	(void)f257(0xedu);
	(void)f132(0x2bu);
}

static void __attribute__((noinline)) run_phase_20(void)
{
	(void)f165(0x1c8u);
	(void)f192(0x182u);
	(void)f053(0x716u);
	(void)f077(0x401u);
	(void)f177(0x6a5u);
	(void)f002(0x8au);
	(void)f271(0x23du);
	(void)f013(0x668u);
	(void)f209(0x4b2u);
	(void)f203(0x66eu);
	(void)f039(0x73du);
	(void)f035(0xeu);
	(void)f076(0x518u);
	(void)f065(0x3a1u);
}

static void __attribute__((noinline)) run_phase_21(void)
{
	(void)f295(0x681u);
	(void)f071(0x23eu);
	(void)f018(0x356u);
	(void)f218(0x2dcu);
	(void)f267(0xf6u);
	(void)f259(0x5a3u);
	(void)f053(0x2aeu);
	(void)f012(0x1d1u);
	(void)f050(0x7c9u);
	(void)f217(0x37bu);
}

static void __attribute__((noinline)) run_phase_22(void)
{
	(void)f205(0x67du);
	(void)f247(0x2eu);
	(void)f031(0x1bfu);
	(void)f279(0xe0u);
	(void)f011(0x748u);
	(void)f294(0x294u);
	(void)f144(0x78u);
	(void)f057(0x742u);
	(void)f110(0x5d2u);
	(void)f132(0x5cu);
	(void)f133(0x4eu);
	(void)f096(0x4edu);
	(void)f052(0x45cu);
	(void)f111(0x256u);
}

static void __attribute__((noinline)) run_phase_23(void)
{
	(void)f031(0x213u);
	(void)f258(0xc3u);
	(void)f182(0xf0u);
	(void)f191(0x55bu);
	(void)f022(0x59du);
	(void)f175(0x6d9u);
	(void)f084(0x540u);
	(void)f275(0x499u);
	(void)f044(0x4e7u);
	(void)f205(0x20fu);
}

static void __attribute__((noinline)) run_phase_24(void)
{
	(void)f101(0x17eu);
	(void)f217(0x232u);
	(void)f069(0x3d2u);
	(void)f160(0x6fdu);
	(void)f036(0xbu);
	(void)f044(0x31eu);
	(void)f115(0x7e5u);
	(void)f080(0x7d7u);
	(void)f036(0x34fu);
	(void)f201(0x16bu);
	(void)f264(0x4c3u);
	(void)f153(0x269u);
	(void)f277(0x729u);
}

static void __attribute__((noinline)) run_phase_25(void)
{
	(void)f147(0x185u);
	(void)f222(0x152u);
	(void)f151(0x3f2u);
	(void)f144(0x7au);
	(void)f105(0x7acu);
	(void)f037(0xf1u);
	(void)f180(0x57eu);
	(void)f164(0x17fu);
	(void)f160(0x4bu);
	(void)f027(0x510u);
	(void)f120(0x278u);
}

static void __attribute__((noinline)) run_phase_26(void)
{
	(void)f014(0x77au);
	(void)f242(0x14au);
	(void)f121(0x65fu);
	(void)f102(0x53eu);
	(void)f291(0x7d5u);
	(void)f165(0x546u);
	(void)f164(0x43cu);
	(void)f132(0x1afu);
	(void)f161(0x647u);
	(void)f222(0x305u);
}

static void __attribute__((noinline)) run_phase_27(void)
{
	(void)f271(0x600u);
	(void)f290(0x6c4u);
	(void)f061(0x1d1u);
	(void)f030(0x323u);
	(void)f170(0x523u);
	(void)f201(0x1f7u);
	(void)f244(0x261u);
	(void)f032(0x2a4u);
	(void)f073(0x5c9u);
	(void)f254(0x2e8u);
	(void)f186(0x165u);
	(void)f011(0x5d1u);
	(void)f085(0x4efu);
}

static void __attribute__((noinline)) run_phase_28(void)
{
	(void)f080(0x1eeu);
	(void)f136(0x80u);
	(void)f069(0x376u);
	(void)f012(0x715u);
	(void)f128(0x2a3u);
	(void)f233(0x590u);
	(void)f134(0x784u);
	(void)f007(0x78bu);
	(void)f035(0x1f8u);
	(void)f269(0x5a6u);
	(void)f039(0x209u);
	(void)f079(0x544u);
}

static void __attribute__((noinline)) run_phase_29(void)
{
	(void)f255(0x1b2u);
	(void)f008(0x6f1u);
	(void)f208(0x4ceu);
	(void)f270(0x700u);
	(void)f062(0x203u);
	(void)f253(0x15u);
	(void)f047(0x67cu);
	(void)f075(0x3bbu);
	(void)f149(0xa7u);
	(void)f269(0x227u);
	(void)f071(0x68fu);
}

static void __attribute__((noinline)) run_phase_30(void)
{
	(void)f051(0x51du);
	(void)f043(0x101u);
	(void)f010(0x74bu);
	(void)f239(0x1c8u);
	(void)f195(0x6cbu);
	(void)f013(0x46au);
	(void)f070(0x2a6u);
	(void)f116(0x76bu);
	(void)f127(0x5ceu);
	(void)f109(0x750u);
	(void)f089(0x1c9u);
}

static void __attribute__((noinline)) run_phase_31(void)
{
	(void)f158(0x775u);
	(void)f066(0x57bu);
	(void)f291(0x463u);
	(void)f271(0x316u);
	(void)f250(0x7e2u);
	(void)f227(0x2f2u);
	(void)f207(0x35u);
	(void)f202(0x662u);
	(void)f093(0x759u);
	(void)f078(0x4cu);
}

static void __attribute__((noinline)) run_phase_32(void)
{
	(void)f232(0x470u);
	(void)f069(0x22du);
	(void)f064(0x6e1u);
	(void)f171(0x11fu);
	(void)f006(0x5d0u);
	(void)f049(0x4c7u);
	(void)f104(0x31u);
	(void)f034(0x476u);
	(void)f234(0x196u);
	(void)f098(0x681u);
	(void)f082(0x3eeu);
	(void)f061(0x12du);
	(void)f040(0x599u);
	(void)f185(0x9eu);
}

static void __attribute__((noinline)) run_phase_33(void)
{
	(void)f284(0x45bu);
	(void)f149(0x629u);
	(void)f052(0x3d8u);
	(void)f015(0x2dbu);
	(void)f234(0x3e8u);
	(void)f001(0x6e7u);
	(void)f277(0x6b9u);
	(void)f120(0x13u);
	(void)f134(0x7b9u);
	(void)f169(0x3d2u);
	(void)f293(0x415u);
	(void)f059(0x3c4u);
	(void)f121(0x3c2u);
}

static void __attribute__((noinline)) run_phase_34(void)
{
	(void)f049(0x4cdu);
	(void)f039(0x33fu);
	(void)f248(0x361u);
	(void)f045(0x1ddu);
	(void)f240(0x36du);
	(void)f088(0x1ccu);
	(void)f176(0x458u);
	(void)f105(0x37fu);
	(void)f174(0x5e0u);
	(void)f246(0x6u);
	(void)f252(0x197u);
	(void)f248(0x627u);
	(void)f103(0x37bu);
}

static void __attribute__((noinline)) run_phase_35(void)
{
	(void)f225(0x7e8u);
	(void)f019(0x20bu);
	(void)f023(0x723u);
	(void)f263(0x66bu);
	(void)f028(0x528u);
	(void)f184(0x269u);
	(void)f018(0x108u);
	(void)f008(0x39eu);
	(void)f252(0x643u);
	(void)f281(0x143u);
	(void)f201(0x789u);
	(void)f100(0x21eu);
	(void)f004(0x1adu);
}

static void __attribute__((noinline)) run_phase_36(void)
{
	(void)f021(0x779u);
	(void)f068(0x1aau);
	(void)f247(0x74cu);
	(void)f180(0xceu);
	(void)f165(0x44u);
	(void)f123(0x1b1u);
	(void)f006(0x62fu);
	(void)f104(0x760u);
	(void)f079(0x1fau);
	(void)f208(0x4e8u);
	(void)f005(0x549u);
	(void)f009(0x576u);
	(void)f229(0x734u);
}

static void __attribute__((noinline)) run_phase_37(void)
{
	(void)f047(0x7d0u);
	(void)f217(0x4f5u);
	(void)f232(0x1ceu);
	(void)f033(0x29au);
	(void)f033(0x61du);
	(void)f243(0x1f6u);
	(void)f073(0x5u);
	(void)f195(0x472u);
	(void)f233(0x2e0u);
	(void)f122(0x53du);
	(void)f087(0x5fu);
	(void)f119(0x4a1u);
	(void)f130(0x55du);
}

static void __attribute__((noinline)) run_phase_38(void)
{
	(void)f220(0x192u);
	(void)f204(0x149u);
	(void)f048(0x1edu);
	(void)f091(0x360u);
	(void)f216(0x164u);
	(void)f067(0x3c5u);
	(void)f153(0x1f9u);
	(void)f235(0x28bu);
	(void)f027(0x4b2u);
	(void)f011(0x3a8u);
	(void)f151(0x550u);
	(void)f217(0x149u);
	(void)f134(0x73fu);
}

static void __attribute__((noinline)) run_phase_39(void)
{
	(void)f066(0x53du);
	(void)f042(0x17bu);
	(void)f177(0x31cu);
	(void)f173(0x74fu);
	(void)f283(0x203u);
	(void)f176(0x64au);
	(void)f261(0x72du);
	(void)f101(0x5f8u);
	(void)f230(0x4b3u);
	(void)f009(0x1d3u);
}

static void __attribute__((noinline)) run_phase_40(void)
{
	(void)f214(0x1d0u);
	(void)f254(0x2dfu);
	(void)f151(0x5ecu);
	(void)f285(0xb6u);
	(void)f036(0x31fu);
	(void)f176(0x11au);
	(void)f046(0x5d1u);
	(void)f027(0x27bu);
	(void)f261(0x7bfu);
	(void)f021(0x38bu);
}

static void __attribute__((noinline)) run_phase_41(void)
{
	(void)f077(0x33eu);
	(void)f223(0x73fu);
	(void)f088(0x29u);
	(void)f229(0x3edu);
	(void)f224(0x6a4u);
	(void)f166(0x1dbu);
	(void)f051(0x19u);
	(void)f171(0x547u);
	(void)f017(0xe8u);
	(void)f200(0x11u);
}

static void __attribute__((noinline)) run_phase_42(void)
{
	(void)f138(0x16cu);
	(void)f246(0x6cfu);
	(void)f147(0x388u);
	(void)f158(0x184u);
	(void)f082(0x694u);
	(void)f002(0x7d5u);
	(void)f121(0x4d5u);
	(void)f045(0x39du);
	(void)f006(0x616u);
	(void)f049(0x540u);
	(void)f038(0x26fu);
	(void)f189(0x6f4u);
	(void)f204(0x2e8u);
}

static void __attribute__((noinline)) run_phase_43(void)
{
	(void)f086(0x68au);
	(void)f108(0x58cu);
	(void)f128(0x580u);
	(void)f125(0x6b7u);
	(void)f163(0x664u);
	(void)f096(0x40du);
	(void)f226(0x4d7u);
	(void)f130(0x59bu);
	(void)f212(0x3d9u);
	(void)f022(0x627u);
	(void)f289(0x531u);
}

static void __attribute__((noinline)) run_phase_44(void)
{
	(void)f132(0x4ffu);
	(void)f035(0x8au);
	(void)f091(0x780u);
	(void)f278(0x476u);
	(void)f184(0x68au);
	(void)f217(0xd8u);
	(void)f248(0x40au);
	(void)f042(0x746u);
	(void)f046(0x9u);
	(void)f076(0x4b5u);
	(void)f022(0x23au);
	(void)f066(0x5eeu);
}

static void __attribute__((noinline)) run_phase_45(void)
{
	(void)f007(0x611u);
	(void)f182(0x502u);
	(void)f252(0x74du);
	(void)f245(0x757u);
	(void)f133(0x3c6u);
	(void)f271(0x4adu);
	(void)f292(0x512u);
	(void)f196(0x716u);
	(void)f065(0x1e2u);
	(void)f197(0x34cu);
	(void)f184(0x75au);
	(void)f132(0x30du);
}

static void __attribute__((noinline)) run_phase_46(void)
{
	(void)f106(0x324u);
	(void)f188(0x10u);
	(void)f044(0x6dfu);
	(void)f209(0x497u);
	(void)f026(0x764u);
	(void)f040(0x239u);
	(void)f010(0x6c0u);
	(void)f290(0x322u);
	(void)f171(0x5du);
	(void)f215(0x697u);
	(void)f013(0x4e3u);
	(void)f142(0x2b0u);
	(void)f178(0x799u);
}

static void __attribute__((noinline)) run_phase_47(void)
{
	(void)f214(0x533u);
	(void)f266(0x593u);
	(void)f109(0x38cu);
	(void)f145(0xbbu);
	(void)f049(0x70cu);
	(void)f036(0x1f6u);
	(void)f180(0x68cu);
	(void)f260(0x316u);
	(void)f123(0x176u);
	(void)f233(0x344u);
	(void)f074(0x4c6u);
}

static void __attribute__((noinline)) run_phase_48(void)
{
	(void)f249(0x300u);
	(void)f263(0x36au);
	(void)f028(0x26eu);
	(void)f223(0x618u);
	(void)f287(0x7ccu);
	(void)f108(0x46cu);
	(void)f134(0x2f7u);
	(void)f287(0x212u);
	(void)f179(0x77au);
	(void)f256(0x2b8u);
	(void)f193(0xebu);
	(void)f233(0x581u);
	(void)f115(0x750u);
}

static void __attribute__((noinline)) run_phase_49(void)
{
	(void)f159(0x506u);
	(void)f299(0x6fu);
	(void)f090(0x748u);
	(void)f032(0x1fcu);
	(void)f067(0x60au);
	(void)f144(0x7e3u);
	(void)f256(0x391u);
	(void)f130(0x224u);
	(void)f225(0x4e3u);
	(void)f089(0x359u);
	(void)f047(0x99u);
	(void)f003(0x5f4u);
	(void)f033(0x39fu);
	(void)f187(0x1dcu);
}

static void __attribute__((noinline)) run_phase_50(void)
{
	(void)f228(0x4f4u);
	(void)f202(0x5a9u);
	(void)f248(0x7au);
	(void)f267(0x0u);
	(void)f001(0x319u);
	(void)f200(0xd7u);
	(void)f237(0x6cbu);
	(void)f113(0x1f5u);
	(void)f220(0x2eau);
	(void)f212(0x71bu);
	(void)f061(0x440u);
	(void)f282(0x7f2u);
	(void)f194(0x7b8u);
	(void)f280(0x1bbu);
}

static void __attribute__((noinline)) run_phase_51(void)
{
	(void)f098(0x785u);
	(void)f267(0x6d3u);
	(void)f226(0x5f1u);
	(void)f002(0x407u);
	(void)f223(0x63u);
	(void)f260(0x11bu);
	(void)f170(0x43du);
	(void)f084(0x4acu);
	(void)f130(0x337u);
	(void)f183(0x104u);
	(void)f103(0x33u);
}

static void __attribute__((noinline)) run_phase_52(void)
{
	(void)f243(0x2a9u);
	(void)f096(0x541u);
	(void)f226(0x416u);
	(void)f049(0x29du);
	(void)f253(0x3b6u);
	(void)f165(0x12du);
	(void)f245(0x16cu);
	(void)f099(0x19cu);
	(void)f289(0x1e0u);
	(void)f272(0x72du);
	(void)f285(0x656u);
	(void)f213(0x39fu);
	(void)f291(0x6eu);
}

static void __attribute__((noinline)) run_phase_53(void)
{
	(void)f185(0x5f8u);
	(void)f014(0x374u);
	(void)f034(0x18eu);
	(void)f024(0x1cdu);
	(void)f060(0x74cu);
	(void)f149(0xd6u);
	(void)f244(0x1abu);
	(void)f298(0x20cu);
	(void)f201(0x3fcu);
	(void)f270(0x24fu);
	(void)f112(0x744u);
	(void)f271(0x7c0u);
	(void)f087(0x711u);
}

static void __attribute__((noinline)) run_phase_54(void)
{
	(void)f025(0x311u);
	(void)f124(0x510u);
	(void)f286(0x5ddu);
	(void)f032(0x79au);
	(void)f127(0xcau);
	(void)f211(0x382u);
	(void)f138(0x1d3u);
	(void)f146(0xau);
	(void)f190(0x5b8u);
	(void)f281(0x17fu);
	(void)f166(0x743u);
}

static void __attribute__((noinline)) run_phase_55(void)
{
	(void)f026(0x4aau);
	(void)f266(0xe8u);
	(void)f018(0x717u);
	(void)f292(0x384u);
	(void)f289(0x27du);
	(void)f223(0x2feu);
	(void)f268(0x203u);
	(void)f029(0x4eu);
	(void)f276(0x1f8u);
	(void)f197(0x2e7u);
	(void)f282(0xbfu);
	(void)f286(0xffu);
	(void)f083(0x68eu);
	(void)f050(0x6b6u);
}

static void __attribute__((noinline)) run_phase_56(void)
{
	(void)f260(0x147u);
	(void)f142(0xecu);
	(void)f262(0x4e2u);
	(void)f065(0x1eau);
	(void)f207(0x405u);
	(void)f068(0x3c9u);
	(void)f287(0x614u);
	(void)f128(0x3a9u);
	(void)f249(0x1cbu);
	(void)f259(0x1e3u);
	(void)f202(0x6dfu);
}

static void __attribute__((noinline)) run_phase_57(void)
{
	(void)f264(0x17u);
	(void)f236(0x6dfu);
	(void)f006(0x46fu);
	(void)f199(0x7b6u);
	(void)f140(0x2e8u);
	(void)f168(0x15cu);
	(void)f284(0x764u);
	(void)f001(0x67eu);
	(void)f289(0x7adu);
	(void)f123(0x544u);
	(void)f139(0x148u);
	(void)f275(0x6f1u);
	(void)f262(0x6a4u);
	(void)f104(0x447u);
}

static void __attribute__((noinline)) run_phase_58(void)
{
	(void)f208(0x3b6u);
	(void)f019(0x684u);
	(void)f112(0x780u);
	(void)f244(0x655u);
	(void)f095(0x4d1u);
	(void)f048(0x691u);
	(void)f108(0x5c2u);
	(void)f206(0x155u);
	(void)f235(0x500u);
	(void)f150(0xf2u);
	(void)f099(0x7d2u);
	(void)f152(0x18au);
	(void)f216(0x7a1u);
}

static void __attribute__((noinline)) run_phase_59(void)
{
	(void)f226(0x67eu);
	(void)f297(0x183u);
	(void)f176(0x17au);
	(void)f004(0x287u);
	(void)f293(0x188u);
	(void)f020(0x787u);
	(void)f201(0x33au);
	(void)f279(0x312u);
	(void)f015(0x65u);
	(void)f100(0x758u);
	(void)f143(0x343u);
	(void)f140(0x4a6u);
}

static void __attribute__((noinline)) run_phase_60(void)
{
	(void)f286(0x7e8u);
	(void)f203(0x710u);
	(void)f050(0x390u);
	(void)f036(0x389u);
	(void)f194(0x73cu);
	(void)f130(0x437u);
	(void)f001(0x48bu);
	(void)f251(0x3du);
	(void)f287(0x36cu);
	(void)f095(0x453u);
	(void)f261(0x4c3u);
	(void)f129(0x6f0u);
	(void)f019(0x6f5u);
	(void)f041(0x4e3u);
}

static void __attribute__((noinline)) run_phase_61(void)
{
	(void)f037(0x6d6u);
	(void)f026(0x6cdu);
	(void)f051(0x5e8u);
	(void)f292(0x2b8u);
	(void)f130(0x7dcu);
	(void)f126(0x12u);
	(void)f165(0x5bbu);
	(void)f181(0x22du);
	(void)f153(0x383u);
	(void)f279(0x172u);
	(void)f094(0x51bu);
	(void)f260(0x513u);
	(void)f102(0x499u);
}

static void __attribute__((noinline)) run_phase_62(void)
{
	(void)f274(0x44bu);
	(void)f145(0x659u);
	(void)f052(0xc8u);
	(void)f026(0x7u);
	(void)f117(0x4edu);
	(void)f171(0x5cbu);
	(void)f000(0x310u);
	(void)f119(0x429u);
	(void)f287(0x437u);
	(void)f155(0x6u);
	(void)f256(0x7d8u);
	(void)f273(0x28du);
	(void)f209(0x61bu);
	(void)f013(0x6a3u);
}

static void __attribute__((noinline)) run_phase_63(void)
{
	(void)f044(0x76fu);
	(void)f124(0x701u);
	(void)f056(0x7c9u);
	(void)f203(0x12fu);
	(void)f158(0x378u);
	(void)f061(0x6a6u);
	(void)f008(0x7f7u);
	(void)f181(0x342u);
	(void)f188(0x338u);
	(void)f206(0x728u);
	(void)f060(0x18au);
	(void)f184(0x376u);
	(void)f277(0xbu);
	(void)f218(0x1f6u);
}

const walk_phase_fn walk_phases[64] = {
	run_phase_00,
	run_phase_01,
	run_phase_02,
	run_phase_03,
	run_phase_04,
	run_phase_05,
	run_phase_06,
	run_phase_07,
	run_phase_08,
	run_phase_09,
	run_phase_10,
	run_phase_11,
	run_phase_12,
	run_phase_13,
	run_phase_14,
	run_phase_15,
	run_phase_16,
	run_phase_17,
	run_phase_18,
	run_phase_19,
	run_phase_20,
	run_phase_21,
	run_phase_22,
	run_phase_23,
	run_phase_24,
	run_phase_25,
	run_phase_26,
	run_phase_27,
	run_phase_28,
	run_phase_29,
	run_phase_30,
	run_phase_31,
	run_phase_32,
	run_phase_33,
	run_phase_34,
	run_phase_35,
	run_phase_36,
	run_phase_37,
	run_phase_38,
	run_phase_39,
	run_phase_40,
	run_phase_41,
	run_phase_42,
	run_phase_43,
	run_phase_44,
	run_phase_45,
	run_phase_46,
	run_phase_47,
	run_phase_48,
	run_phase_49,
	run_phase_50,
	run_phase_51,
	run_phase_52,
	run_phase_53,
	run_phase_54,
	run_phase_55,
	run_phase_56,
	run_phase_57,
	run_phase_58,
	run_phase_59,
	run_phase_60,
	run_phase_61,
	run_phase_62,
	run_phase_63,
};
