/* SPDX-FileCopyrightText: 2026 Accemic Technologies GmbH
 * SPDX-License-Identifier: CERN-OHL-S-2.0 OR LicenseRef-Accemic-Commercial
 * GENERATED by gen_program.py (seed=0xC0FFEE01, funcs=300, phases=64) -- DO NOT EDIT, regenerate instead. */
#ifndef AXIS_WP_DEMO_WALK_H
#define AXIS_WP_DEMO_WALK_H

#include <stdint.h>

#define WALK_NUM_PHASES 64u

typedef void (*walk_phase_fn)(void);
extern const walk_phase_fn walk_phases[64];
extern volatile uint32_t g_acc;

#endif /* AXIS_WP_DEMO_WALK_H */
