// SPDX-FileCopyrightText: 2026 Accemic Technologies GmbH
// SPDX-License-Identifier: CERN-OHL-S-2.0 OR LicenseRef-Accemic-Commercial
//
// tb_mbv_ps_devmem -- G6 stage 1: the devmem flow against mbv_soc_top.
//
// Migrated 2026-08-18 from the evidence archive
// (package D3b). The test
// sequence is carried over verbatim, including its German $display texts --
// they are the verdict strings of the archived G6 evidence. Three things had
// to change, all of them consequences of the D2 rebuild (840c3cb010), and all
// of them listed here rather than buried in the diff:
//
//   (a) PORT LIST. mbv_soc_top instantiates the shared three-sink subsystem
//       ct_trace_sinks since D2 and therefore has two new outward edges: the
//       DDR4 sink's AXI4 write master m_axi_* (to PS S_AXI_HP0_FPD) and the
//       PIB pins pib_clk/pib_data[3:0]. Both are wired here -- m_axi_* to the
//       same minimal always-ready AXI write-slave model tb_duo_ps_devmem
//       uses, mirroring from the RESET window (DDR_BASE 0x5000_0000, read-only
//       in hardware since U9-1), the PIB pins to an observer. Leaving the
//       m_axi_* INPUTS unconnected would not be neutral: they would float, and
//       X would reach the sink's handshake the moment anyone enables it.
//   (b) REGISTER MAP. SINK_CTRL (0x18) resets to 0, so DDR and PIB stay off
//       and this bench sees exactly the pre-sink behaviour -- it deliberately
//       does not write 0x18, and it now CHECKS that both stayed silent.
//       Note for anyone extending it: ATB_BP moved from 0x38 to 0x40 in D2;
//       0x38 is now the read-only counter DDR_BEATS, and a write there is
//       swallowed without any error.
//   (c) PROGRAM PATH. The archive runner copied the chosen image to `prog.bin`
//       in the xsim run directory. The default now names this example's own
//       artifact relative to the simulator work directory (bld/<task>.vsim),
//       exactly as examples/kv260/common/tgc5b/test/ct_soc_tb.sv spells its programs;
//       +PROG_BIN still overrides it.
//
// NOT RUNNABLE ON THE DEFAULT BACKEND, and that is a property of the design,
// not of this migration: mbv_soc_top -> mbv_soc_synth_wrap instantiates
// `mbv_ctrace_soc_wrapper` (generated by Vivado's make_wrapper from the
// `mbv_ctrace_soc` block design, around the ENCRYPTED MicroBlaze-V core) and
// the Xilinx XPM macro `xpm_memory_tdpram`. Neither has an in-repo .sv source.
// See this directory's README.md for the Vivado recipe and for what was verified without it.
//
// ---- original header of the archived bench, carried over unchanged --------
// tb_mbv_ps_devmem -- G6 stage 1: devmem-flow smoke test against mbv_soc_top.
//
// Adaptation of the tgc5b `ct_soc_ps_tb` of the predecessor repository: drives
// the AXI4-Lite slave exactly like Linux `devmem` does on the KV260, and proves the whole
// on-hardware flow in sim:
//   1. Hold the core, write the program image (.bin, little-endian) into the RAM window,
//   2. configure CTTE + arm it (trTeControl @ ENC+0x0),
//   3. clear the trace buffer + start the core (CTRL),
//   4. run, InstTracing off (trace-off correlation) + encoder flush,
//   5. read TRACE_BYTES + write the ATB capture to tb_mbv_ps_devmem.atb.bin
//      (offline: NexRv -conv/-deco against the object dump, same as run_g5_e2e).
//
// Program via +PROG_BIN=<path> (default: trace_test.bin, path relative to the XSIM run dir;
// override with +PROG_BIN -- the runner passes absolute paths).
//
// trTeControl value as in the tgc5b README: full-word writes MUST keep the reset default fields
// (InstMode=6, InhibitSrc=1, Format=1) -- 0x0106_8067 = on, 0x0106_8063 = InstTracing off.

`default_nettype none

module tb_mbv_ps_devmem;

    localparam logic [21:0] CTRL_BASE  = 22'h00_0000;
    localparam logic [21:0] ENC_BASE   = 22'h01_0000;
    localparam logic [21:0] RAM_BASE   = 22'h10_0000;
    localparam logic [21:0] TRACE_BASE = 22'h20_0000;
    localparam logic [21:0] AXIS_BASE  = 22'h30_0000;

    localparam int unsigned MEM_WORDS  = 32768;
    localparam int unsigned RUN_CYCLES = 60000;   // trace_test: ~4k retires; generous margin

    logic clk = 0;
    logic resetn = 0;
    always #6667ps clk = ~clk;                    // ~75 MHz, as pl_clk0

    logic [21:0] awaddr;  logic awvalid;  uwire awready;
    logic [31:0] wdata;   logic [3:0] wstrb; logic wvalid; uwire wready;
    uwire [1:0]  bresp;   uwire bvalid;    logic bready;
    logic [21:0] araddr;  logic arvalid;   uwire arready;
    uwire [31:0] rdata;   uwire [1:0] rresp; uwire rvalid; logic rready;

    // DDR4 sink (AXI4 write master) + PIB pins -- new since the D2 rebuild (ct_trace_sinks).
    uwire logic [31:0] mx_awaddr;  uwire logic [7:0] mx_awlen; uwire logic [2:0] mx_awsize;
    uwire logic [1:0]  mx_awburst; uwire logic mx_awvalid; logic mx_awready;
    uwire logic [31:0] mx_wdata;   uwire logic [3:0] mx_wstrb; uwire logic mx_wlast, mx_wvalid;
    logic mx_wready, mx_bvalid;    uwire logic mx_bready;
    uwire logic pib_clk_w; uwire logic [3:0] pib_data_w;

    mbv_soc_top #(.MEM_WORDS(MEM_WORDS)) dut (
        .clk (clk), .resetn (resetn),
        .s_axi_awaddr (awaddr), .s_axi_awprot (3'b0), .s_axi_awvalid (awvalid), .s_axi_awready (awready),
        .s_axi_wdata (wdata), .s_axi_wstrb (wstrb), .s_axi_wvalid (wvalid), .s_axi_wready (wready),
        .s_axi_bresp (bresp), .s_axi_bvalid (bvalid), .s_axi_bready (bready),
        .s_axi_araddr (araddr), .s_axi_arprot (3'b0), .s_axi_arvalid (arvalid), .s_axi_arready (arready),
        .s_axi_rdata (rdata), .s_axi_rresp (rresp), .s_axi_rvalid (rvalid), .s_axi_rready (rready),
        .m_axi_awaddr (mx_awaddr), .m_axi_awlen (mx_awlen), .m_axi_awsize (mx_awsize),
        .m_axi_awburst (mx_awburst), .m_axi_awvalid (mx_awvalid), .m_axi_awready (mx_awready),
        .m_axi_wdata (mx_wdata), .m_axi_wstrb (mx_wstrb), .m_axi_wlast (mx_wlast),
        .m_axi_wvalid (mx_wvalid), .m_axi_wready (mx_wready),
        .m_axi_bresp (2'b00), .m_axi_bvalid (mx_bvalid), .m_axi_bready (mx_bready),
        .pib_clk (pib_clk_w), .pib_data (pib_data_w)
    );

    // ---- Mini AXI slave memory model (PS DDR stand-in) --------------------
    // Word-for-word the same model as in tb_duo_ps_devmem: the mirror base is the
    // RESET window of ct_trace_sinks (DDR_BASE 0x5000_0000, read-only in
    // hardware since the earlier D2-era finding). This bench deliberately does NOT enable the
    // DDR sink (SINK_CTRL 0x18 stays 0) -- the model exists so the
    // m_axi INPUTS are driven instead of floating, and so that extending
    // this bench can enable the sink without further rework.
    localparam logic [31:0] DDR_BASE = 32'h5000_0000;
    localparam int unsigned DDR_MODEL_BYTES = 1 << 16;
    byte ddr_model [0:DDR_MODEL_BYTES-1];
    logic [31:0] ddr_cur_addr; logic ddr_in_burst;
    int unsigned ddr_beats_seen = 0;
    initial begin mx_awready = 1'b1; mx_wready = 1'b1; mx_bvalid = 1'b0; ddr_in_burst = 0; ddr_cur_addr = 0; end
    always_ff @(posedge clk) begin
        if (mx_awvalid && mx_awready) begin
            ddr_cur_addr <= mx_awaddr;
            ddr_in_burst <= 1'b1;
        end
        if (mx_wvalid && mx_wready && ddr_in_burst) begin
            for (int b = 0; b < 4; b++)
                if (ddr_cur_addr - DDR_BASE + b < DDR_MODEL_BYTES)
                    ddr_model[ddr_cur_addr - DDR_BASE + b] <= mx_wdata[8*b +: 8];
            ddr_cur_addr   <= ddr_cur_addr + 4;
            ddr_beats_seen <= ddr_beats_seen + 1;
            if (mx_wlast) begin
                ddr_in_burst <= 1'b0;
                mx_bvalid    <= 1'b1;
            end
        end
        if (mx_bvalid && mx_bready) mx_bvalid <= 1'b0;
    end

    // ---- PIB observer -------------------------------------------------------
    // This bench does not enable the PIB; the observer proves that too:
    // pib_toggles must stay 0 as long as SINK_CTRL is 0 (the reset inertness
    // that the D2 rebuild commit claims).
    int unsigned pib_toggles = 0;
    always @(posedge pib_clk_w) pib_toggles = pib_toggles + 1;

    // Handshake pattern as in ct_soc_ps_tb: hold valids, wait for registered bvalid/rvalid.
    task automatic axi_write(input logic [21:0] a, input logic [31:0] d);
        @(posedge clk);
        awaddr <= a; awvalid <= 1'b1; wdata <= d; wstrb <= 4'hF; wvalid <= 1'b1;
        do @(posedge clk); while (!bvalid);
        awvalid <= 1'b0; wvalid <= 1'b0;
    endtask

    task automatic axi_read(input logic [21:0] a, output logic [31:0] d);
        @(posedge clk);
        araddr <= a; arvalid <= 1'b1;
        do @(posedge clk); while (!rvalid);
        d = rdata; arvalid <= 1'b0;
    endtask

    string prog_bin;
    byte   img_bytes [0:MEM_WORDS*4-1];
    int    fd, nread, i, nbytes, nwords;
    logic [31:0] rd, w, word;

    initial begin
        awvalid = 0; wvalid = 0; bready = 1; arvalid = 0; rready = 1;
        wstrb = 4'hF; awaddr = 0; araddr = 0; wdata = 0;

        // Fixed name in the XSIM run dir (the runner copies the desired image there;
        // +PROG_BIN plusargs with Windows paths split xsim's option parser).
        if (!$value$plusargs("PROG_BIN=%s", prog_bin))
            prog_bin = "../../examples/kv260/mbv/sw/build/trace_test.bin";
        fd = $fopen(prog_bin, "rb");
        if (fd == 0) $fatal(1, "[ps_tb] program image missing: %s (+PROG_BIN=<path>)", prog_bin);
        nread = $fread(img_bytes, fd);
        $fclose(fd);
        $display("[ps_tb] image %s: %0d bytes", prog_bin, nread);

        repeat (10) @(posedge clk);
        resetn <= 1'b1;
        repeat (5) @(posedge clk);
        $display("[ps_tb] reset released, starting devmem sequence");

        // 1. Hold the core + clear the trace buffer.
        axi_write(CTRL_BASE, 32'h0000_0002);
        axi_write(CTRL_BASE, 32'h0000_0000);

        // 2. Load the program (little-endian bytes -> words).
        for (i = 0; i < (nread + 3) / 4; i++) begin
            word = {img_bytes[i*4+3], img_bytes[i*4+2], img_bytes[i*4+1], img_bytes[i*4+0]};
            axi_write(RAM_BASE + 22'(i*4), word);
        end
        $display("[ps_tb] program loaded (%0d words)", (nread + 3) / 4);

        // 2b. Read-back check (loader read path + word 0 matches).
        axi_read(RAM_BASE + 22'h0, rd);
        word = {img_bytes[3], img_bytes[2], img_bytes[1], img_bytes[0]};
        if (rd !== word) $error("[ps_tb] RAM readback mismatch @0: 0x%08x != 0x%08x", rd, word);

        // 3. Arm CTTE.
        axi_write(ENC_BASE + 22'h0, 32'h0106_8067);

        // 4. Start the core.
        axi_write(CTRL_BASE, 32'h0000_0001);
        $display("[ps_tb] core started");

        // Run phase. With +IRQ (interrupt_test): enable the HW IRQ pulse generator
        // (CONTROL b3 = enable; 1-cycle pulse every 4096 cycles -- as on the board).
        if ($test$plusargs("IRQ")) begin
            repeat (2000) @(posedge clk);              // wait out the program's CSR setup
            axi_write(CTRL_BASE, 32'h0000_0009);       // run + IRQ generator on
            repeat (RUN_CYCLES - 6000) @(posedge clk);
            axi_write(CTRL_BASE, 32'h0000_0001);       // generator off (core keeps running)
            repeat (2000) @(posedge clk);
            $display("[ps_tb] IRQ generator window ended");
        end
        else begin
            repeat (RUN_CYCLES) @(posedge clk);
        end

        // 5. Tracing off + flush.
        axi_write(ENC_BASE + 22'h0, 32'h0106_8063);
        repeat (200) @(posedge clk);
        axi_write(CTRL_BASE, 32'h0000_0005);
        repeat (3000) @(posedge clk);
        axi_write(CTRL_BASE, 32'h0000_0001);
        $display("[ps_tb] tracing off + flushed");

        // 6. Read out the capture.
        axi_read(CTRL_BASE + 22'hC, rd);  nbytes = rd;
        axi_read(CTRL_BASE + 22'h8, rd);
        $display("[ps_tb] %0d ATB bytes, %0d beats captured", nbytes, rd);

        fd = $fopen("tb_mbv_ps_devmem.atb.bin", "wb");
        nwords = (nbytes + 3) / 4;
        for (i = 0; i < nwords; i++) begin
            axi_read(TRACE_BASE + 22'(i*4), w);
            for (int b = 0; b < 4; b++)
                if (i*4 + b < nbytes) $fwrite(fd, "%c", w[b*8 +: 8]);
        end
        $fclose(fd);

        axi_read(CTRL_BASE + 22'h10, rd);
        $display("[ps_tb] AXIS beats (informational): %0d", rd);

        // D2 cross-check: SINK_CTRL (0x18) was never written, so the
        // DDR sink and the PIB must have stayed silent -- this is the reset inertness
        // the rebuild commit claims, measured here instead of assumed.
        if (ddr_beats_seen != 0)
            $error("[ps_tb] FAIL -- %0d DDR beats at SINK_CTRL=0 (sink not reset-inert)", ddr_beats_seen);
        if (pib_toggles != 0)
            $error("[ps_tb] FAIL -- %0d PIB cycles at SINK_CTRL=0 (PIB not reset-inert)", pib_toggles);

        if (nbytes == 0) $error("[ps_tb] FAIL -- no ATB bytes captured");
        else if (ddr_beats_seen == 0 && pib_toggles == 0)
            $display("[ps_tb] PASS -- tb_mbv_ps_devmem.atb.bin (%0d bytes) written, DDR/PIB reset-inert", nbytes);
        else             $display("[ps_tb] tb_mbv_ps_devmem.atb.bin (%0d bytes) written", nbytes);
        $finish;
    end

    // Retired-PC reference (golden hierarchical port of the wrapper): every retiring
    // instruction while the core runs. Comparison basis for check_pcout_vs_retired
    // (decode is a prefix of it -- the core keeps retiring after trace-off).
    int pcs_fd;
    initial pcs_fd = $fopen("tb_mbv_ps_devmem.retired.pcs", "w");
    always_ff @(posedge clk) begin
        if (resetn && dut.soc.core_trace_valid && pcs_fd != 0)
            $fwrite(pcs_fd, "0x%08h\n", dut.soc.core_trace_pc);
    end
    final if (pcs_fd != 0) $fclose(pcs_fd);

    initial begin
        #20ms;
        $error("[ps_tb] TIMEOUT");
        $finish;
    end

endmodule

`default_nettype wire
