# SPDX-FileCopyrightText: 2026 Accemic Technologies GmbH
# SPDX-License-Identifier: ISC
#
# The build profiles the measurement flows quote, in one place.
#
# doc/integration.adoc says "profile definitions are canonically those of
# scripts/phase_d_matrix_v2.sh" -- and for a while that was literally true:
# the definitions existed only as a sequence of sed calls interleaved with
# synthesis runs inside that one script. A second flow that wanted the same
# profile had to re-derive it by reading the sequence, which is a hand-edit
# of rtl/pkg/ct_pkg.sv by another name and the historical collision source
# of this campaign. So the sequence moved here, phase_d_matrix_v2.sh sources
# it, and every later flow (scripts/p10_timing_matrix.sh) uses the same
# functions rather than a copy of them.
#
# Source it near the top of a script:
#
#     . "$(cd "$(dirname "$0")/.." && pwd)/scripts/ct_profiles.sh"
#
# Provides:
#   set_sw_in PKG SW VAL       set `localparam bit SW = VAL;` in PKG
#   set_ts_in PKG WIDTH        set CT_TS_WIDTH
#   set_steps_in PKG STEPS     set CT_SLICER_STEPS
#   CT_GOLD_FEATS              the nine gold-standard feature switches
#   ct_gold_feats_in PKG VAL   set all nine at once
#   ct_profile_in PKG NAME     apply a named profile (see ct_profile_names)
#   ct_profile_names           the names ct_profile_in understands
#
# Every profile function writes ONLY rtl/pkg/ct_pkg.sv. The CSR block that
# belongs to the profile is regenerated by scripts/gen_rdl_profile.py, which
# reads the switches back out of the package -- callers run it after the
# profile call (phase_d_matrix_v2.sh: `regen`).

# --------------------------------------------------------------- setters ----
set_sw_in () { local pkg="$1" sw="$2" val="$3"; sed -i -E "s/(localparam bit ${sw}[[:space:]]*=[[:space:]]*)[01];/\1${val};/" "$pkg"; }
set_ts_in () { sed -i -E "s/(localparam int unsigned CT_TS_WIDTH = )[0-9]+;/\1${2};/" "$1"; }
set_steps_in () { sed -i -E "s/(localparam int unsigned CT_SLICER_STEPS = )[0-9]+;/\1${2};/" "$1"; }

# The nine switches the gold-standard round added (seq 24). A "_gold" profile
# is its base profile with these ON; the base profiles have them OFF.
CT_GOLD_FEATS="CT_EN_DEBUG_EVENTS CT_EN_POWER_EVENTS CT_EN_EVTI CT_EN_TRIG_SYNC CT_EN_SEQ_SYNC CT_EN_OWNERSHIP CT_EN_CONFIG_MSG CT_EN_IBHS CT_EN_REPEAT_INSTR"

ct_gold_feats_in () { local pkg="$1" val="$2" f; for f in $CT_GOLD_FEATS; do set_sw_in "$pkg" "$f" "$val"; done; }

# ------------------------------------------------------------- profiles ----
# featparity base: the control-flow-only profile -- data trace, DAQ/ACT,
# filters and the compression suite compiled out, single clock, 32-bit
# timestamp, one slicer step, compact packer egress, serialize off. It is the
# feature set a control-flow-only tracer needs and nothing beyond it, which is
# why it is the denominator of every cost table in doc/integration.adoc.
#
# RENAMED 2026-08-19 (AW decision E1). It was called `amdcmp` and the name
# invited a misreading that a publication audit duly made: that these are
# measurements OF a vendor's IP, and therefore a licence question. They are
# not -- every number in these profiles is measured on Accemic's own RTL, and
# the profile only describes WHICH of our own features are compiled in. The
# name now says that.
# CT_EN_WATCHPOINT_MSG and CT_EN_AXIS_TS follow CT_EN_ACT and CT_EN_DF_DROP /
# CT_EN_DF_ADDR_COMPRESS follow CT_EN_DATA_TRACE: those are elaboration
# dependencies, not taste (scripts/check_profile_deps.py).
ct_profile_featparity_base_in () {
	local pkg="$1" f
	set_sw_in "$pkg" CT_EN_DAQ 0; set_sw_in "$pkg" CT_EN_DATA_TRACE 0; set_sw_in "$pkg" CT_EN_ACT 0; set_sw_in "$pkg" CT_EN_FILTERS 0; set_sw_in "$pkg" CT_EN_FILTER_SYNC 0; set_sw_in "$pkg" CT_EN_WATCHPOINT_MSG 0; set_sw_in "$pkg" CT_EN_AXIS_TS 0; set_sw_in "$pkg" CT_EN_DF_DROP 0; set_sw_in "$pkg" CT_EN_DF_ADDR_COMPRESS 0
	for f in CT_EN_IMPLICIT_RETURN CT_EN_REPEATED_HISTORY CT_EN_WIDE_ICNT CT_EN_REPEAT_BRANCH CT_EN_JTC CT_EN_BP; do set_sw_in "$pkg" $f 0; done
	set_sw_in "$pkg" CT_SINGLE_CLOCK 1; set_ts_in "$pkg" 32; set_steps_in "$pkg" 1
	set_sw_in "$pkg" CT_COMPACT_PACKER 1; set_sw_in "$pkg" CT_ETIP_CDC_SLIM 0
	set_sw_in "$pkg" CT_EN_ETIP_WATERMARK 1; set_sw_in "$pkg" CT_EN_TIMESTAMP 1
	set_sw_in "$pkg" CT_MICRO_CSR 0
	set_sw_in "$pkg" CT_ETIP_SERIALIZE 0
	ct_gold_feats_in "$pkg" 0
}

# voll base: the maximum configuration -- everything on, multi-clock, 64-bit
# timestamp, two slicer steps, Nexus formatter egress, serialize on.
ct_profile_voll_base_in () {
	local pkg="$1" f
	set_sw_in "$pkg" CT_EN_DAQ 1; set_sw_in "$pkg" CT_EN_DATA_TRACE 1; set_sw_in "$pkg" CT_EN_ACT 1; set_sw_in "$pkg" CT_EN_FILTERS 1; set_sw_in "$pkg" CT_EN_FILTER_SYNC 1; set_sw_in "$pkg" CT_EN_WATCHPOINT_MSG 1; set_sw_in "$pkg" CT_EN_AXIS_TS 1; set_sw_in "$pkg" CT_EN_DF_DROP 1; set_sw_in "$pkg" CT_EN_DF_ADDR_COMPRESS 1
	for f in CT_EN_IMPLICIT_RETURN CT_EN_REPEATED_HISTORY CT_EN_WIDE_ICNT CT_EN_REPEAT_BRANCH CT_EN_JTC CT_EN_BP; do set_sw_in "$pkg" $f 1; done
	set_sw_in "$pkg" CT_SINGLE_CLOCK 0; set_ts_in "$pkg" 64; set_steps_in "$pkg" 2
	set_sw_in "$pkg" CT_COMPACT_PACKER 0; set_sw_in "$pkg" CT_ETIP_CDC_SLIM 0
	set_sw_in "$pkg" CT_EN_ETIP_WATERMARK 1; set_sw_in "$pkg" CT_EN_TIMESTAMP 1
	set_sw_in "$pkg" CT_MICRO_CSR 0
	set_sw_in "$pkg" CT_ETIP_SERIALIZE 1
	ct_gold_feats_in "$pkg" 0
}

# The named profiles. `_gold` = base + the nine gold switches; `slimfull` =
# featparity_gold with the slim eTIP CDC, no watermark and no timestamp unit.
# The protocol pair (nonly/eonly) is the committed full profile with the
# back-end selector flipped -- that is how P9 measured it, and the two
# selectors are what a single encoder instance chooses between.
ct_profile_names () { echo "voll_gold featparity_gold slimfull_gold nonly eonly"; }

ct_profile_in () {
	local pkg="$1" name="$2"
	case "$name" in
		voll_gold)
			ct_profile_voll_base_in "$pkg"; ct_gold_feats_in "$pkg" 1
			set_sw_in "$pkg" CT_EN_NTRACE 1; set_sw_in "$pkg" CT_EN_ETRACE 0 ;;
		featparity_gold)
			ct_profile_featparity_base_in "$pkg"; ct_gold_feats_in "$pkg" 1
			set_sw_in "$pkg" CT_EN_NTRACE 1; set_sw_in "$pkg" CT_EN_ETRACE 0 ;;
		slimfull_gold)
			ct_profile_featparity_base_in "$pkg"; ct_gold_feats_in "$pkg" 1
			set_sw_in "$pkg" CT_ETIP_CDC_SLIM 1
			set_sw_in "$pkg" CT_EN_ETIP_WATERMARK 0
			# CT_EN_AXIS_TS requires CT_EN_TIMESTAMP (already 0 via the
			# featparity base, restated so this leg carries the dependency).
			set_sw_in "$pkg" CT_EN_TIMESTAMP 0
			set_sw_in "$pkg" CT_EN_AXIS_TS 0
			set_sw_in "$pkg" CT_EN_NTRACE 1; set_sw_in "$pkg" CT_EN_ETRACE 0 ;;
		nonly)
			ct_profile_voll_base_in "$pkg"; ct_gold_feats_in "$pkg" 1
			set_sw_in "$pkg" CT_EN_NTRACE 1; set_sw_in "$pkg" CT_EN_ETRACE 0 ;;
		eonly)
			ct_profile_voll_base_in "$pkg"; ct_gold_feats_in "$pkg" 1
			set_sw_in "$pkg" CT_EN_NTRACE 0; set_sw_in "$pkg" CT_EN_ETRACE 1 ;;
		*)
			echo "ct_profiles: unknown profile '$name' (have: $(ct_profile_names))" >&2
			return 2 ;;
	esac
	return 0
}
