#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Accemic Technologies GmbH
# SPDX-License-Identifier: ISC
"""Regenerate the CSR regblock for the build profile in rtl/pkg/ct_pkg.sv.

Reads the CT_EN_* switches from ct_pkg.sv, rewrites rdl/ct_profile.inc.rdl
with the matching CT_PROFILE_NO_* defines, runs PeakRDL-regblock and copies
the (SPDX-prefixed) outputs into rtl/pkg/. The other generated files
(ct_cs_cpuif_wb_pkg.sv, types, TB helper) are profile-INDEPENDENT (the
address map never changes -- gated fields become read-only constants, they
do not disappear) and are left untouched; use scripts/gen_rdl.sh for those.

Full profile (all CT_EN_* = 1) reproduces the committed files up to the
gen_rdl.sh post-processing: this script writes the RAW PeakRDL output
(space indentation, no editor modelines), gen_rdl.sh additionally applies
`canonicalize_ws` and the modeline banner. A profile flip therefore leaves
the two generated files cosmetically dirty -- `git checkout` them, or
regenerate the committed form with scripts/gen_rdl.sh (verified against
peakrdl-regblock 1.3.1 / systemrdl 1.32.2: content-identical, whitespace
and modelines aside).

OUT-OF-TREE MODE (--pkg/--rdl-dir/--out-dir): read the switches from a COPY
of ct_pkg.sv and write the profile include plus the regenerated regblock
next to that copy, leaving the repository untouched. That is what the
profile-flipping test scripts use, so a flip can never race a parallel
worker's edit in rtl/pkg (and no `git checkout --` is needed to undo it).
"""

import argparse
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

# The license literals below are injected verbatim into the generated RTL and
# RDL, which stay dual-licensed. They are not this script's own license, so
# REUSE must not parse them as such.
# REUSE-IgnoreStart
SPDX = ("// SPDX-FileCopyrightText: 2026 Accemic Technologies GmbH\n"
        "// SPDX-License-Identifier: "
        "CERN-OHL-S-2.0 OR LicenseRef-Accemic-Commercial\n\n")

# ct_pkg switch -> RDL define emitted when the switch is 0
SWITCH_TO_DEFINE = {
    "CT_EN_FILTERS":          "CT_PROFILE_NO_FILTERS",
    "CT_EN_DATA_TRACE":       "CT_PROFILE_NO_DATA_TRACE",
    "CT_EN_ACT":              "CT_PROFILE_NO_ACT",
    "CT_EN_IMPLICIT_RETURN":  "CT_PROFILE_NO_IMPLICIT_RETURN",
    "CT_EN_BP":               "CT_PROFILE_NO_BP",
    "CT_EN_JTC":              "CT_PROFILE_NO_JTC",
    "CT_EN_REPEATED_HISTORY": "CT_PROFILE_NO_REPEATED_HISTORY",
    "CT_EN_REPEAT_BRANCH":    "CT_PROFILE_NO_REPEAT_BRANCH",
    "CT_EN_WIDE_ICNT":        "CT_PROFILE_NO_WIDE_ICNT",
    "CT_EN_TIMESTAMP":        "CT_PROFILE_NO_TIMESTAMP",
    "CT_EN_IBHS":             "CT_PROFILE_NO_IBHS",
    "CT_EN_REPEAT_INSTR":     "CT_PROFILE_NO_REPEAT_INSTR",
    "CT_EN_TRIG_SYNC":        "CT_PROFILE_NO_TRIG_SYNC",
    "CT_EN_SEQ_SYNC":         "CT_PROFILE_NO_SEQ_SYNC",
    "CT_EN_OWNERSHIP":        "CT_PROFILE_NO_OWNERSHIP",
    "CT_EN_CONFIG_MSG":       "CT_PROFILE_NO_CONFIG_MSG",
    "CT_EN_SYNC_STATUS":      "CT_PROFILE_NO_SYNC_STATUS",
    "CT_EN_FIFO_HIST":        "CT_PROFILE_NO_FIFO_HIST",
    "CT_EN_QUOTA_SYNC":       "CT_PROFILE_NO_QUOTA_SYNC",
    "CT_EN_DF_ADDR_COMPRESS": "CT_PROFILE_NO_DF_ADDR_COMPRESS",
    "CT_EN_DEVICE_ID":        "CT_PROFILE_NO_DEVICE_ID",
    "CT_EN_WATCHPOINT_MSG":   "CT_PROFILE_NO_WATCHPOINT_MSG",
    "CT_EN_TRIG_REGS":        "CT_PROFILE_NO_TRIG_REGS",
    "CT_EN_DF_DROP":          "CT_PROFILE_NO_DF_DROP",
}

INC_HEADER = """\
// SPDX-FileCopyrightText: 2026 Accemic Technologies GmbH
// SPDX-License-Identifier: CERN-OHL-S-2.0 OR LicenseRef-Accemic-Commercial
//
// Build-profile defines for ct_cs_cpuif.rdl.
//
// GENERATED by scripts/gen_rdl_profile.py from the CT_EN_* switches in
// rtl/pkg/ct_pkg.sv -- do not edit by hand unless you know why.
//
// The COMMITTED default is the FULL profile: no defines active, register
// map identical to the historical one. A slim build regenerates
// rtl/pkg/ct_cs_cpuif.sv via:
//
//     python3 scripts/gen_rdl_profile.py
//
// after editing the CT_EN_* switches in ct_pkg.sv; the script rewrites
// this file and the generated regblock together (revert both to return
// to the full profile).
//
// Available defines (each turns its group's config fields into sw=r
// constants; storage and write decode vanish, hwif members stay):
//   CT_PROFILE_NO_FILTERS          <- CT_EN_FILTERS = 0
//   CT_PROFILE_NO_DATA_TRACE       <- CT_EN_DATA_TRACE = 0
//   CT_PROFILE_NO_ACT              <- CT_EN_ACT = 0
//   CT_PROFILE_NO_IMPLICIT_RETURN  <- CT_EN_IMPLICIT_RETURN = 0
//   CT_PROFILE_NO_BP               <- CT_EN_BP = 0
//   CT_PROFILE_NO_JTC              <- CT_EN_JTC = 0
//   CT_PROFILE_NO_REPEATED_HISTORY <- CT_EN_REPEATED_HISTORY = 0
//   CT_PROFILE_NO_REPEAT_BRANCH    <- CT_EN_REPEAT_BRANCH = 0
//   CT_PROFILE_NO_WIDE_ICNT        <- CT_EN_WIDE_ICNT = 0
//   CT_PROFILE_NO_TIMESTAMP        <- CT_EN_TIMESTAMP = 0
//   CT_PROFILE_NO_IBHS             <- CT_EN_IBHS = 0
//   CT_PROFILE_NO_REPEAT_INSTR     <- CT_EN_REPEAT_INSTR = 0
//   CT_PROFILE_NO_TRIG_SYNC        <- CT_EN_TRIG_SYNC = 0
//   CT_PROFILE_NO_SEQ_SYNC         <- CT_EN_SEQ_SYNC = 0
//   CT_PROFILE_NO_OWNERSHIP        <- CT_EN_OWNERSHIP = 0
//   CT_PROFILE_NO_CONFIG_MSG       <- CT_EN_CONFIG_MSG = 0 (also flips SendConfig reset to CFG_NONE)
//   CT_PROFILE_NO_SYNC_STATUS      <- CT_EN_SYNC_STATUS = 0 (register OMITTED from the map)
//   CT_PROFILE_NO_FIFO_HIST        <- CT_EN_FIFO_HIST = 0 (registers OMITTED from the map)
//   CT_PROFILE_NO_QUOTA_SYNC       <- CT_EN_QUOTA_SYNC = 0 (documentation-only: InstSyncMode
//                                     1/4 stay writable but inert -- no WARL clamp, no
//                                     structural register change; D6 structure stability)
//   CT_PROFILE_NO_DF_ADDR_COMPRESS <- CT_EN_DF_ADDR_COMPRESS = 0 (DataAddrCompress becomes a
//                                     read-only constant 0; the wrapper WARL additionally
//                                     legalizes any write to 0)
//   CT_PROFILE_NO_DEVICE_ID        <- CT_EN_DEVICE_ID = 0 (SendDeviceId becomes a read-only
//                                     constant DID_NONE)
//   CT_PROFILE_NO_WATCHPOINT_MSG   <- CT_EN_WATCHPOINT_MSG = 0 (trWpMask.WEM becomes a
//                                     read-only constant 0 -- no hit can be reported)
//   CT_PROFILE_NO_TRIG_REGS        <- CT_EN_TRIG_REGS = 0 (trTeTrigExtInControl.ExtInAction0
//                                     becomes a read-only constant 0 = "no action"; the two
//                                     non-existent-trigger registers 0x050/0x058 are RO 0 anyway)
//   CT_PROFILE_NO_DF_DROP          <- CT_EN_DF_DROP = 0 (trTeDataControl.DataDropEna becomes a
//                                     read-only constant 0 -- the drop policy can never arm)
"""
# REUSE-IgnoreEnd


def read_switches(ct_pkg: Path) -> dict:
    text = ct_pkg.read_text(encoding="utf-8")
    values = {}
    for name in SWITCH_TO_DEFINE:
        m = re.search(rf"localparam\s+bit\s+{name}\s*=\s*([01])\s*;", text)
        if not m:
            sys.exit(f"ERROR: {name} not found (or not a 0/1 literal) in {ct_pkg}")
        values[name] = int(m.group(1))
    return values


def venv_roots() -> list:
    """This tree, then the MAIN working tree the venv actually lives in.

    A linked `git worktree` has no .venv-rdl* of its own -- it is gitignored
    and belongs to the main checkout. `git rev-parse --git-common-dir` names
    the shared .git, whose parent IS that checkout. Without this the lookup
    below fell through to the PATH `peakrdl`, whose (older) output carries no
    addrmap localparams, and the entire xsim battery then died with
    "'NUM_PERFCNT_IFETCH_TH_RANGES' is not declared" -- silently wrong tools,
    loudly wrong build (P8 audit C-1, third incident of the class).
    """
    roots = [REPO]
    try:
        out = subprocess.run(["git", "-C", str(REPO), "rev-parse", "--git-common-dir"],
                             capture_output=True, text=True, check=True)
        common = Path(out.stdout.strip())
        if not common.is_absolute():
            common = REPO / common
        main = common.resolve().parent
        if main != REPO:
            roots.append(main)
    except (OSError, subprocess.CalledProcessError):
        pass
    return roots


def find_peakrdl() -> list:
    # Invoke peakrdl as "<venv-python> -m peakrdl": the console-script .exe
    # shim silently exits 1 once the venv's embedded interpreter path goes
    # stale (observed 2026-07-24); the module launch is move-robust.
    for root in venv_roots():
        for cand in (root / ".venv-rdl-win" / "Scripts" / "python.exe",
                     root / ".venv-rdl" / "Scripts" / "python.exe",
                     root / ".venv-rdl" / "bin" / "python"):
            if cand.exists():
                return [str(cand), "-m", "peakrdl"]
    exe = shutil.which("peakrdl")
    if exe:
        # Deliberately NOT a silent fallback: an unpinned PeakRDL produces
        # output that compiles differently (or not at all), and the failure
        # surfaces hours later in xvlog. Ask for it explicitly or fix the venv.
        if os.environ.get("GEN_RDL_ALLOW_PATH_PEAKRDL"):
            print(f"WARNING: using UNPINNED peakrdl from PATH ({exe}) -- "
                  f"output is not the pinned toolchain's", file=sys.stderr)
            return [exe]
        sys.exit(f"ERROR: no pinned peakrdl venv found in "
                 f"{', '.join(str(r) for r in venv_roots())} -- refusing the "
                 f"PATH peakrdl at {exe} (its output has no addrmap "
                 f"localparams). Run scripts/gen_rdl.sh once, or set "
                 f"GEN_RDL_ALLOW_PATH_PEAKRDL=1 to override deliberately.")
    sys.exit("ERROR: peakrdl not found (.venv-rdl-win/.venv-rdl/PATH) -- run scripts/gen_rdl.sh once")


def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser(
        description="Regenerate the CSR regblock for a build profile.")
    ap.add_argument("--pkg", type=Path, default=REPO / "rtl" / "pkg" / "ct_pkg.sv",
                    help="ct_pkg.sv to read the CT_EN_* switches from "
                         "(default: the repository's own)")
    ap.add_argument("--rdl-dir", type=Path, default=REPO / "rdl",
                    help="directory holding ct_cs_cpuif.rdl; ct_profile.inc.rdl "
                         "is written THERE (the addrmap includes it by name)")
    ap.add_argument("--out-dir", type=Path, default=REPO / "rtl" / "pkg",
                    help="where ct_cs_cpuif.sv / ct_cs_cpuif_pkg.sv are written")
    return ap.parse_args()


def main() -> None:
    args = parse_args()
    switches = read_switches(args.pkg)
    defines = [d for sw, d in SWITCH_TO_DEFINE.items() if switches[sw] == 0]

    # No protocol define (P9, AW directive 2026-08-04): the back end is a
    # per-INSTANCE synthesis parameter of ct_encoder, so the discovery
    # registers trTeProtocolSel.Protocol / trTeImpl.ProtocolMajor are driven
    # by hardware (sw=r, hw=w) instead of being baked into the profile. A
    # profile-wide RDL constant would lie in a mixed SoC.
    inc = args.rdl_dir / "ct_profile.inc.rdl"
    body = INC_HEADER + "\n"
    if defines:
        body += "".join(f"`define {d}\n" for d in defines)
    else:
        body += "// (Full profile: intentionally empty.)\n"
    inc.write_text(body, encoding="utf-8", newline="\n")
    print(f"[gen_rdl_profile] {inc.name}: "
          + (", ".join(defines) if defines else "full profile (no defines)"))

    with tempfile.TemporaryDirectory() as tmp:
        subprocess.run(find_peakrdl() + ["regblock", str(args.rdl_dir / "ct_cs_cpuif.rdl"),
                        "-o", tmp, "--cpuif", "passthrough", "--type-style", "hier"],
                       check=True)
        for fname in ("ct_cs_cpuif.sv", "ct_cs_cpuif_pkg.sv"):
            src = Path(tmp) / fname
            dst = args.out_dir / fname
            dst.write_text(SPDX + src.read_text(encoding="utf-8"), encoding="utf-8", newline="\n")
            try:
                shown = dst.relative_to(REPO)
            except ValueError:
                shown = dst
            print(f"[gen_rdl_profile] wrote {shown}")

    print("[gen_rdl_profile] done.")


if __name__ == "__main__":
    main()
