#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 Accemic Technologies GmbH
# SPDX-License-Identifier: ISC
# Copy a gate VERDICT into the versioned evidence tree (verification/evidence/README.md).
#
# The transcript stays in bld/ and is regenerated by re-running the command;
# the verdict is what a later reader cannot reconstruct once bld/ has been
# reused for the next run. Every file gets a header naming the command, the
# repository HEAD and the time, so a number can never drift away from what
# produced it (P7 audit B-5).
#
#   usage: scripts/keep_evidence.sh <package> <gate> <command> [-- <grep-ERE>]
#          ... < transcript          (reads the transcript on stdin)
#
#   e.g.   bash scripts/keep_evidence.sh P7 off_neutrality \
#            "bash scripts/p7_off_neutrality.sh" \
#            -- 'reference family|BYTE NEUTRALITY|OVERALL|cli_[a-z]+:' \
#            < bld/p7r_off_neutrality.log
#
# Without a filter the whole input is kept -- use that only for output that
# IS the verdict (a summary block), never for a raw simulator log.
set -u
repo="$(cd "$(dirname "$0")/.." && pwd)"
[ $# -ge 3 ] || { echo "usage: $0 <package> <gate> <command> [-- <grep-ERE>]" >&2; exit 2; }
pkg="$1"; gate="$2"; cmd="$3"; shift 3
filter=""
if [ "${1:-}" = "--" ]; then filter="${2:-}"; fi

out="$repo/verification/evidence/$pkg"
mkdir -p "$out"
dst="$out/$gate.log"
{
	echo "# gate    : $gate"
	echo "# package : $pkg"
	echo "# command : $cmd"
	echo "# HEAD    : $(git -C "$repo" rev-parse --short HEAD 2>/dev/null || echo '?')"
	echo "# when    : $(date '+%Y-%m-%d %H:%M:%S %Z')"
	echo "# note    : verdict only -- the full transcript is regenerated by the"
	echo "#           command above (verification/evidence/README.md)"
	echo "# ----------------------------------------------------------------"
	if [ -n "$filter" ]; then grep -aE "$filter"; else cat; fi
} > "$dst"
echo "[keep_evidence] $dst ($(grep -c . "$dst") lines)"
